- services/gitea/4.1.1/defaults/cm.yaml
- services/traefik/10.3.0/defaults/cm.yaml
This is needed so that attached clusters can access the Git
repository.
All repositories are accessed through the URL
https://INGRESS_HOST/dkp/kommander/gitserver/USER|ORG/REPO
refs https://jira.d2iq.com/browse/D2IQ-80105
> feat: create Ingress for Gitea

- services/istio/1.9.1/helmrelease.yaml
- services/istio/1.9.1/helmrelease/helmrelease.yaml
- services/istio/1.9.1/istio-ca.yaml
- services/istio/1.9.1/istio-ca/istio-ca.yaml
- services/istio/1.9.1/istio-system-namespace.yaml
- services/istio/1.9.1/istio-system-namespace/istio-system.yaml
- services/istio/1.9.1/kustomization.yaml
- services/jaeger/2.21.0/jaeger.yaml
Now that Istio is installed into the `istio-system` namespace, two more changes are needed  to make the clean install work:
- the namespace itself needs to be created before additional objects (`istso-ca` Certificate, etc.) can be created in it
- we have to switch to using the ClusterIssuer instead of an Issuer, as there are no Issuers in the `istio-system` NS
> fix: make clean install of Istio work again

- services/fluent-bit/0.16.2/defaults/cm.yaml
- services/grafana-loki/0.33.1/defaults/cm.yaml
- services/kommander-flux/0.17.2/templates/apps_v1_deployment_source-controller.yaml
- services/project-grafana-loki/0.33.1/defaults/cm.yaml
This change is required to make http proxing support in k20 work. 
The http libraries do not strip trailing dots when checking the `no_proxy` variable contents. This results in requests that would normally not be proxied (e.g. for `....cluster.local`) to be forwarded to http proxy. The proxy then rejects these requests 
as these addresses are local to the cluster thus resulting in breakage.
https://jira.d2iq.com/browse/D2IQ-80589
> Remove trailing dots in hostnames

- services/kommander-flux/0.17.2/templates/apps_v1_deployment_source-controller.yaml
https://jira.d2iq.com/browse/D2IQ-80649
Some of the changes that #23 introduced into the repo will be overridden by next flux update. This PR realigns the repo back with what flux uses.
The `--storage-adv-addr=source-controller.$(RUNTIME_NAMESPACE).svc` string  is originating from [here](https://github.com/vespian/flux2/blob/8ec5492d87c2891ddc7e8c6b691e7246b8c027a2/pkg/manifestgen/install/templates.go#L88) So we would need to remove the trailing dot here as well. The container it is running in is debian-based so this should not cause issues.
I am to just update the docs though. This is starting to be cat and mouse chase and there is no guarantee that flux people will not add new urls ending in dots as well. This is perfectly OK approach according to RFC and it is just that http proxy …
> fix: align with flux's upstream manifests

- services/traefik/10.3.0/defaults/cm.yaml
This URL is still used in chart-bootstrapped Kommander clusters so as
long as we haven't completely transitioned to the CLI for
bootstrapping Kommander we need to have both URLs for the different
Git Ingresses in here.
> fix: re-add gitserver URL to list of prefixes to strip

- services/traefik/10.3.0/defaults/cm.yaml
Traefik prefix stripping is order-sensitve - first match wins, not the longest one. 
The incomming request has format:
```
172.18.0.3 - - [05/Nov/2021:12:28:28 +0000] "GET /dkp/kommander/gitserver/repo/info/refs?service=git-upload-pack HTTP/2.0" 404 0 "-" "-" 1155 "git-repository-kommander-dkp-kommander-gitserver@kubernetes" "https://192.168.173.21:443" 1ms
```
Traefik was stripping the first matching prefix, but due to the fact that the shorter one was listed first, instead of URLs like 
```
192.168.173.26 - - [05/Nov/2021:12:29:09 +0000] "GET /repo/info/refs?service=git-upload-pack HTTP/1.1" 401 179 "-" "git/2.0 (libgit2 1.1.0)" "-
```
traefik was forwarding URLs without the `server` part stripped:
```
192.168.173.68 - git [05/Nov/2021:12:28:28 +0000] "GET …
```
> fix: user correct ordering for prefix stripping

- services/centralized-kubecost/0.19.0/centralized-kubecost.yaml
- services/thanos/0.4.5/thanos.yaml
Hooks are not used in flux, they are a helm construct, so they are all getting run immediately by flux, which can end up in a race for certain jobs that create and delete configmaps. This is the likely cause for the `centralized-kubecost` timeout flakes that have been happening.
To unblock the release, let's remove the cleanup job. The effect is that we leave behind 2 configmaps if those apps get disabled (centralized-kubecost and thanos) which doesn't seem like the worst outcome. Longer term, we can move the hooks into the helm charts (we already maintain a kubecost parent chart so that would be easy, but for thanos which we're directly pulling from upstream we would have to create a parent chart).
> fix: Remove hooks and cleanup jobs from centralized-kubecost/thanos

- services/centralized-grafana/17.2.1/defaults/cm.yaml
- services/centralized-kubecost/0.19.0/kustomization.yaml
- services/centralized-kubecost/0.19.0/post-install-jobs.yaml
- services/centralized-kubecost/0.19.0/post-install-jobs/post-install-jobs.yaml
- services/centralized-kubecost/0.19.0/release.yaml
- services/centralized-kubecost/0.19.0/release/release.yaml
- Found a typo in centralized-grafana
- At some point may have introduced a flake in the `centralized-monitoring` kuttl test (e.g. https://teamcity.mesosphere.io/buildConfiguration/ClosedSource_Kommander2_KuttlTests/3276741?expandedTest=build%3A%28id%3A3276741%29%2Cid%3A2005&showLog=3276741_2005_118.1976.2005&logFilter=debug) https://jira.d2iq.com/browse/D2IQ-80889
```
kuttl-default.centralized-monitoring
failed in step 0-
resource Job:kubecost/copy-kubecost-grafana-datasource-cm: .status.succeeded: key is missing from map
```
```
status:
-  succeeded: 1
+  conditions:
+  - lastProbeTime: "2021-11-06T02:20:59Z"
+    lastTransitionTime: "2021-11-06T02:20:59Z"
+    message: Job has reached the specified backoff limit
+    reason: BackoffLimitExceeded
+    status: "True"
+    type: Failed
+ …
```
> fix: Typo, check cm in retry loop

- services/centralized-kubecost/0.19.0/defaults/cm.yaml
Setting some defaults for thanos query in centralized-kubecost (used recs from upstream chart)
> chore: Set resource requests/limits for centralized-kubecost thanos

- services/kubefed/0.8.1/defaults/cm.yaml
- services/kubefed/0.8.1/federatedtypeconfigs.yaml
- services/kubefed/0.8.1/federatedtypeconfigs/federatedtypeconfigs.yaml
- services/kubefed/0.8.1/kube-federation-system-namespace.yaml
- services/kubefed/0.8.1/kube-federation-system-namespace/kube-federation-system.yaml
- services/kubefed/0.8.1/kustomization.yaml
- services/kubefed/0.8.1/release.yaml
- services/kubefed/0.8.1/release/release.yaml
Deploy kubefed control plane to dedicated `kube-federation-system` namespace instead of deploying it to `kommander`. This is mainly done so that we are able to federate the `kommander` namespace to use it as the workspace ns. I was unable to federate that namespace until I moved the kubefed control plane out of it (looks like this is by design in kubefed https://github.com/kubernetes-sigs/kubefed/blob/master/pkg/controller/sync/accessor.go#L183-L186).
Regardless of when we get the change in to use `kommander` ns for the kommander workspace, I still think it's a good idea to deploy kubefed to a dedicated namespace, that seems to be the recommended way of doing things. And in case we ever need to federate anything to itself in the `kommander` ns, we wouldn't get blocked by this kubefed …
> refactor: Deploy kubefed to kube-federation-system

- services/kube-prometheus-stack/17.2.1/defaults/cm.yaml
applied the same thing to the centralized grafana already but missed this one
> fix: allow plugin for kube-prome-stack

- services/dex-k8s-authenticator/1.2.8/dex-k8s-authenticator.yaml
Adding these dependencies prevents the respective apps' installations from timing out.
> fix: add Traefik dependencies

- services/kommander/0.1.0/kommander.yaml
The Kommander chart cannot be uninstalled so it isn't worth even
trying to remediate any installation failure.
> fix: don't retry installing Kommander

- .tool-versions
- Dockerfile.ci
- Makefile
- hack/flux/flux-update-kustomization.yaml
- hack/flux/templates/networking.k8s.io_v1_networkpolicy_allow-source.yaml
- hack/flux/update-flux.sh
- make/all.mk
- make/ci.mk
- make/docker.mk
- make/flux.mk
- make/help.mk
- make/make.mk
- make/repo.mk
- make/shell.mk
- make/tools.mk
This change bootstraps a Make configuration for running targets in CI
as well as a 'flux-update' target that updates the manifests of Flux
to the latest Flux version.
https://jira.d2iq.com/browse/D2IQ-81179
> feat: add tooling for updating Flux

- services/project-grafana-logging/6.13.9/defaults/cm.yaml
We shouldn't be deploying cluster scoped resources in project apps
> fix: Disable clusterroles in project-grafana-logging

- services/cert-manager/0.2.7/release/release.yaml
- services/dex-k8s-authenticator/1.2.8/dex-k8s-authenticator.yaml
- services/dex/2.9.10/dex.yaml
- services/external-dns/2.20.5/external-dns.yaml
- services/grafana-logging/6.13.9/grafana.yaml
- services/kube-oidc-proxy/0.2.5/kube-oidc-proxy.yaml
- services/kube-prometheus-stack/17.2.1/kube-prometheus-stack.yaml
- services/nvidia/0.4.3/nvidia.yaml
- services/project-grafana-logging/6.13.9/project-grafana.yaml
- services/prometheus-adapter/2.11.1/prometheus-adapter.yaml
- services/reloader/0.0.99/reloader.yaml
- services/traefik-forward-auth-mgmt/0.3.2/traefik-forward-auth-mgmt.yaml
I changed the following 
to 
To prevent errors in CI like: 
```
+      Helm install failed: namespaces is forbidden: User "system:serviceaccount:kuttl-prj-2:kuttl-prj-2" cannot create resource "namespaces" in API group "" at the cluster scope
```
when using SA on HelmRelease - https://teamcity.mesosphere.io/buildConfiguration/ClosedSource_Kommander2_KuttlTestsMultiCluster/3290430?buildTab=tests&expandedTest=build%3A%28id%3A3290430%29%2Cid%3A3950&showLog=3290430_3950_467.3941.3950&logFilter=debug
> feat: set namespace creation to false in project grafana

- services/gatekeeper/0.6.8/constrainttemplates.yaml
- services/gatekeeper/0.6.8/kustomization.yaml
- services/gatekeeper/0.6.8/release.yaml
A dedicated Kustomization gatekeeper-release is created that the other
two Kustomizations can depend on other than depending on a
Kustomization that isn't maintained as part of this repository. This
makes the whole gatekeeper service self-contained and less prone to
bugs.
This follows the same pattern we use for kubefed so we don't use
different approaches within this repo.
> fix: use release Kustomization for Gatekeeper

- services/karma/2.0.0/karma.yaml
Making sure `karma` is not installed without `karma-traefik`.
https://jira.d2iq.com/browse/D2IQ-81449
> fix: Make karma depend on karma-traefik

- services/logging-operator/3.13.0/defaults/cm.yaml
Other containers deployed as part of Kommander use v0.5.0 while the
default of the logging-operator is v0.4.0. To bring down the number of
different images used on a Kommander cluster we're aligning the
different tags of the same image.
> feat: align configmap-reload image tag with other containers

- grafana-dashboards/logging/audit.json
- grafana-dashboards/logging/kustomization.yaml
- services/fluent-bit/0.16.2/defaults/cm.yaml
- services/grafana-logging/6.13.9/defaults/cm.yaml
- services/grafana-logging/6.13.9/kustomization.yaml
This adds an approximate feature parity with the Kibana dashboard in 1.8 (https://jira.d2iq.com/browse/D2IQ-78016)
Tested manually on top of Konvoy 2.1 on AWS:
Note that we could have been better off if we made Grafana parse out verb/username/namespace/resource from the Loki response instead of adding labels when sending the audit log into Loki. Unfortunately, this requires a newer Grafana - and we want to backport this into 2.1.1.  Thus, this PR makes use of what we have in the current version of Grafana.
> feat: add an audit dashboard to grafana-logging

- services/dex/2.9.10/defaults/cm.yaml
This PR updates the image tag to use the CVE fixed image.
Resolves: [D2IQ-81265](https://jira.d2iq.com/browse/D2IQ-81265)
> chore: update docker image tag for dex

- services/kubecost/metadata.yaml
Expected Behavior
The Centralized Cost Monitoring link should go to:
https://docs.d2iq.com/dkp/kommander/latest/monitoring/centralized-cost-monitoring/
Actual behavior
The Centralized Cost Monitoring link goes to:
https://docs.d2iq.com/dkp/kommander/latest/centralized-cost-monitoring/
This updates that link
> fix: updating docs link to kubecost

- services/nfs-server-provisioner/0.6.0/defaults/cm.yaml
- services/nfs-server-provisioner/0.6.0/defaults/kustomization.yaml
- services/nfs-server-provisioner/0.6.0/kustomization.yaml
- services/nfs-server-provisioner/0.6.0/nfs-server-provisioner.yaml
- services/nfs-server-provisioner/metadata.yaml
Resolves [D2IQ-81559](https://jira.d2iq.com/browse/D2IQ-81559).
This PR adds the `nfs-server-provisioner` based on https://github.com/mesosphere/charts/tree/master/staging/nfs-server-provisioner chart to Kommander applications.
> Add NFS Server Provisioner service

- services/traefik-forward-auth/0.3.2/traefik-forward-auth.yaml
We originally needed a separate `traefikNamespace` substitution variable when traefik wasn't installed in the workspace namespace, but now that it is (`kommander` ns is workspace ns) we can remove the var and just use `workspaceNamespace` instead.
> chore: Use workspaceNamespace instead of traefikNamespace

- services/centralized-kubecost/0.20.2/defaults/cm.yaml
- services/centralized-kubecost/0.20.2/defaults/kustomization.yaml
- services/centralized-kubecost/0.20.2/kustomization.yaml
- services/centralized-kubecost/0.20.2/post-install-jobs.yaml
- services/centralized-kubecost/0.20.2/post-install-jobs/post-install-jobs.yaml
- services/centralized-kubecost/0.20.2/release.yaml
- services/centralized-kubecost/0.20.2/release/release.yaml
- services/kubecost/0.20.2/defaults/cm.yaml
- services/kubecost/0.20.2/defaults/kustomization.yaml
- services/kubecost/0.20.2/kubecost.yaml
- services/kubecost/0.20.2/kustomization.yaml
Bumps kubecost + bumps sidecar image to address CVE
https://jira.d2iq.com/browse/D2IQ-81263
New version is added here instead of overwriting the older version in case we need to retain 2.1.0 versions for upgrades.
> chore: Add kubecost 0.20.2

- services/dex-k8s-authenticator/1.2.8/defaults/cm.yaml
This PR updates the image tag to use the CVE fixed image.
Resolves: [D2IQ-81264](https://jira.d2iq.com/browse/D2IQ-81264)
> chore: update docker image tag for dex-k8s-auth

- services/kube-prometheus-stack/18.1.1/defaults/cm.yaml
https://jira.d2iq.com/browse/D2IQ-82012
Caveat from KSM docs: https://github.com/kubernetes/kube-state-metrics/blob/master/docs/cli-arguments.md#available-options
> A single '\*' can be provided per resource instead to allow any labels, but that has severe performance implications (Example: '=pods=[*]').
Should we come up with a targeted list of labels instead?
> fix: Restore all pod labels to metrics emitted by kube-state-metrics

- services/knative/metadata.yaml
Having Knative in the foundational category leads to the UI issuing a
warning about not all foundational components being installed and thus
the UI blocks any deployment of additional applications.
As long as we haven't settled on the right category for Knative, I'm
just moving it to "general" for now to enable users to deploy apps
again.
> bug: move Knative to "general" category

- services/centralized-grafana/18.1.1/defaults/cm.yaml
- services/grafana-logging/6.16.14/defaults/cm.yaml
- services/kube-prometheus-stack/18.1.1/defaults/cm.yaml
See https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-43798.
This PR is tested against kommander at https://github.com/mesosphere/kommander/pull/1246.
https://jira.d2iq.com/browse/D2IQ-82337
> fix: Upgrade Grafana to pull in a fix for CVE-2021-43798

- services/kubecost/0.20.2/defaults/cm.yaml
- services/project-grafana-logging/6.16.14/defaults/cm.yaml
Missed updating grafana img in project-grafana-logging and kubecost grafana. Looks like kubecost already caught the CVE (https://github.com/kubecost/cost-analyzer-helm-chart/pull/1171) but it hasn't been released yet. Let's backport the image bump here to `release-2.1`, but we can remove this image bump with the next kubecost bump for `main`.
> fix: Bump project-grafana-logging/kubecost graf img to pull in a fix for CVE-2021-43798

- common/helm-repositories/mesosphere-spark.yaml
- common/helm-repositories/pravega.yaml
https://jira.d2iq.com/browse/D2IQ-82477
Add the helmrepos required for dkp-catalog-applications to kommander-applications to bundle them with kommander installation. This is meant to be a temporary change (hack) for 2.1.1 until we come up with a plan for airgapped support for external catalog repos. Not putting this in `main` since we will implement the actual airgapped solution for 2.2.
> [release-2.1] feat: Add mesosphere-spark and pravega helmrepos

- services/knative/0.18.3/knative-serving.yaml
Forward-porting this fix that we made on the release branch https://github.com/mesosphere/kommander-applications/pull/102/commits/8cd83e2c789b3bfa1d3bc6a0a313789e0e3bbe2c
> fix: Remove kube-prometheus-stack dep from knative

- services/knative/0.18.3/knative-serving.yaml
Move `dependsOn` field to the `spec` section.
> Fix misplaced `dependsOn` property for KNative

- common/helm-repositories/kaptain.yaml
I propose that kaptain Helm repository can be added here even though it points to helm mirror.
> feat: Add kaptain helm repository

- services/kommander/0.1.0/dynamic-helmreleases/README.txt
- services/kommander/0.1.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
- services/kommander/0.1.0/dynamic-helmreleases/cluster-observer/kustomization.yaml
- services/kommander/0.1.0/dynamic-helmreleases/mtls-proxy/kustomization.yaml
- services/kommander/0.1.0/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
This PR is meant to unblock https://jira.d2iq.com/browse/D2IQ-82657 on one hand and on the other - enable pararelising the upgrades work as once it gets merged it can be worked on independently.
The idea behind this PR is to add dummy helm releases that will replace dynamic helm releases generated by:
* federation/pkg/controllers/kommandercluster_prometheus_proxy.go
* federation/pkg/controllers/kommandercluster_observer_controller.go
This way the charts parsing logic that populates helm-mirror/chartmuseum in https://github.com/mesosphere/kommander-cli/pull/298 will be able to determine versions of charts to download while still letting controllers create helm releases dynamically. The only difference is going to be that the controllers will be creating Flux kustomizations that point to …
> feat: add dummy helm releases

- services/kommander-appmanagement/0.2.0/defaults/cm.yaml
- services/kommander-appmanagement/0.2.0/defaults/kustomization.yaml
- services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml
- services/kommander-appmanagement/0.2.0/kustomization.yaml
- services/kommander/0.2.0/defaults/cm.yaml
- services/kommander/0.2.0/defaults/kustomization.yaml
- services/kommander/0.2.0/dynamic-helmreleases/README.txt
- services/kommander/0.2.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
- services/kommander/0.2.0/dynamic-helmreleases/cluster-observer/kustomization.yaml
- services/kommander/0.2.0/dynamic-helmreleases/mtls-proxy/kustomization.yaml
- services/kommander/0.2.0/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
- services/kommander/0.2.0/kommander.yaml
- services/kommander/0.2.0/kustomization.yaml
Resolves [D2IQ-82656](https://jira.d2iq.com/browse/D2IQ-82656)
This PR does the following:
- Bump the `kommander` from `0.1.0` to `0.2.0`
- Bump the `kommander-appmanagement` from `0.1.0` to `0.2.0`
Corresponding Kommander PR: [mesosphere/kommander#1330](https://github.com/mesosphere/kommander/pull/1330)
> chore: bump kommander and kommander-application to 0.2.0

- services/kubetunnel/0.0.10/kubetunnel.yaml
kubetunnel chart defines version v0.0.8 in Chart.yaml :
```
$ tar -O -xvf charts-bundle.tar.gz kubetunnel-v0.0.8.tgz | tar -O -xzvf - kubetunnel/Chart.yaml
kubetunnel-v0.0.8.tgz
kubetunnel/Chart.yaml
apiVersion: v1
appVersion: v0.0.8
description: Kubernetes Tunneling
home: https://github.com/mesosphere/kubetunnel
maintainers:
- name: mhrabovcin
- name: jongiddy
- name: tillt
- name: hectorj2f
name: kubetunnel
sources:
- https://github.com/mesosphere/kubetunnel
version: v0.0.8
```
whereas helmrelease uses version 0.0.8:
```
1 ---
2 apiVersion: helm.toolkit.fluxcd.io/v2beta1
3 kind: HelmRelease
4 metadata:
5   name: kubetunnel
6   namespace: ${releaseNamespace}
7 spec:
8   chart:
9     spec:
10       chart: kubetunnel
11       sourceRef:
12         kind: HelmRepository
13         name: …
```
> fix: synchronize kubetunmnel versioning scheme

- common/helm-repositories/banzaicloud.yaml
- common/helm-repositories/dashboard.yaml
- common/helm-repositories/fluent.yaml
- common/helm-repositories/gitea.yaml
- common/helm-repositories/grafana.yaml
- common/helm-repositories/jaegertracing.yaml
- common/helm-repositories/kaptain.yaml
- common/helm-repositories/kiali.yaml
- common/helm-repositories/kommander-ui.yaml
- common/helm-repositories/kommander.yaml
- common/helm-repositories/kubefed.yaml
- common/helm-repositories/kubetunnel.yaml
- common/helm-repositories/mesosphere-repos.yaml
- common/helm-repositories/minio.yaml
- common/helm-repositories/prometheus-community.yaml
- common/helm-repositories/reloader.yaml
- common/helm-repositories/traefik.yaml
This is a bit of a hack meant to enable k-cli to inject chartmuseum's CA certificate when airgapped deployment is in place and skip this step otherwise.
The idea is to use variable substitution - in case of airgapped install we provide variable, in non-airgapped install - we do not which results in the field's value being empty-string, which in turn results in disabling custom CA certificate option.
https://jira.d2iq.com/browse/D2IQ-83371
> feat: make helmrepositories use chartmuseum's CA certificate

- common/helm-repositories/banzaicloud.yaml
- common/helm-repositories/dashboard.yaml
- common/helm-repositories/fluent.yaml
- common/helm-repositories/gitea.yaml
- common/helm-repositories/grafana.yaml
- common/helm-repositories/jaegertracing.yaml
- common/helm-repositories/kaptain.yaml
- common/helm-repositories/kiali.yaml
- common/helm-repositories/kommander-ui.yaml
- common/helm-repositories/kommander.yaml
- common/helm-repositories/kubefed.yaml
- common/helm-repositories/kubetunnel.yaml
- common/helm-repositories/mesosphere-repos.yaml
- common/helm-repositories/minio.yaml
- common/helm-repositories/prometheus-community.yaml
- common/helm-repositories/reloader.yaml
- common/helm-repositories/traefik.yaml
Reverts mesosphere/kommander-applications#149
We need a better way to handle null-ing `secretRef`field in HelmRepository object. See also the discussion in https://mesosphere.slack.com/archives/C01LNF6KML5/p1642433423286400
> Revert "feat: make helmrepositories use chartmuseum's CA certificate"

- services/kube-prometheus-stack/18.1.2/defaults/cm.yaml
https://jira.d2iq.com/browse/D2IQ-78014
Centralized Grafana's home dashboard isn't getting set - we should be enabling the cronjob to set it. The required `dkp-credentials` will always exist in the workspace namespace that this grafana instance is deployed to on the mgmt cluster (centralized-grafana only deployed to mgmt-cluster, so we can enable it at the top-level here vs in overrides like we do for kube-prometheus-stack).
> fix: Enable home dashboard in centralized grafana

- services/centralized-grafana/18.1.2/defaults/cm.yaml
- services/kube-prometheus-stack/18.1.2/defaults/cm.yaml
https://jira.d2iq.com/browse/D2IQ-78014
The cronjob was enabled in the wrong app 🤦🏻‍♀️ it should be enabled in centralized-grafana, but I had mistakenly enabled it in kps instead.
> fix: Enable home dash on centralized-grafana not kps

- services/kommander/0.2.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
- services/kommander/0.2.0/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
Introduces substitutions in dynamic HelmReleases so the definitions can be reused.
Jira: https://jira.d2iq.com/browse/D2IQ-83144
Changes are used in: https://github.com/mesosphere/kommander/pull/1355
> feat: Kustomize dynamic helmreleases

- services/kube-prometheus-stack/18.1.3/defaults/cm.yaml
Fixes https://jira.d2iq.com/browse/D2IQ-81451.
The config-reloader container was failing due to not being able to expand the `CLUSTER_ID` environment variable in the config file (line 140). The service wouldn't actually fail/exit, it will just hang out and not watch for config changes which is curious.
Here's the error:
```
expand environment variables: found reference to unset environment variable \"CLUSTER_ID\""
```
We pass in this env var in the config reload init container but not the container i.e.
```
initContainers:
- name: init-config-reloader
envFrom:
- configMapRef:
name: cluster-info-configmap
```
I tested this by first installing Kommander then adding a test `remote_write` config to the kps ConfigMap override, and re-running the install command. It took about 
``` …
```
> fix: Add required env var to config reloader container

- services/chartmuseum/3.4.0/defaults/cm.yaml
We need to let Traefik now that chartmuseum is served over HTTPS and
not HTTP. Since the chart doesn't allow us to directly change the port
name from http to https, we add the annotation here as is documented
at
https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/#communication-between-traefik-and-pods
> fix: promote HTTPS chartmuseum to Traefik

- services/kube-oidc-proxy/0.3.0/defaults/cm.yaml
- services/kube-oidc-proxy/0.3.0/kube-oidc-proxy.yaml
This was missed during the `kube-oidc-proxy` bump.
> fix: kube-oidc-proxy default cm name

- services/kommander/0.2.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
Bump cluster observer as a follow up on https://github.com/mesosphere/kommander/pull/1409.
I'll likely have to create another PR for the release-2.1 branch in the kommander repo since the cluster observer version/helm release was managed in the cluster observer controller in 2.1.1.
Here's the kommander PR to make sure tests pass https://github.com/mesosphere/kommander/pull/1432
> chore: bump cluster observer

- services/kommander/0.1.0/defaults/cm.yaml
This commit provides defaults for the new values in the kommander
chart that were introduced in
https://github.com/mesosphere/kommander/pull/1438.
> feat: provide defaults for new kommander chart values

- services/centralized-grafana/32.0.2/defaults/cm.yaml
- services/grafana-logging/6.20.6/defaults/cm.yaml
- services/kube-prometheus-stack/32.0.2/defaults/cm.yaml
- services/project-grafana-logging/6.20.6/defaults/cm.yaml
We bumped kube-prometheus-stack and grafana charts recently which bumped the grafana image to 8.3.4, so we need to remove the override when we were setting it to 8.2.7 to fix a CVE. 8.3.4 also includes the CVE fix.
Same deal with a sidecar img we were overriding, and also explicitly enabled a few things in kps just in case upstream ever decided to disable things by default
> fix: Remove grafana img overrides

- services/centralized-grafana/32.0.2/defaults/cm.yaml
- services/kube-prometheus-stack/32.0.2/defaults/cm.yaml
https://jira.d2iq.com/browse/D2IQ-84982
Newer versions of grafana added automatic reloading of datasources by hitting the Admin API. However, the API only works with basic authentication, which we disable.
https://grafana.com/docs/grafana/latest/http_api/admin
Upstream PR fix: https://github.com/grafana/helm-charts/pull/1046 we can bump to this once it is merged
> fix: Disable grafana datasource reload url

- services/cert-manager/0.2.7/root-ca.yaml
- services/cert-manager/0.2.7/root-ca/root-ca.yaml
This is a quick fix of the issue where attached clusters are missing the kommander root-ca bootstrap cert resources. 
https://jira.d2iq.com/browse/D2IQ-84510
kuttl test PR: https://github.com/mesosphere/kommander/pull/1422
> drop the dependson of root-ca resources and change the issuer type&name

- hack/validate-default-apps-versions.sh
- services/kommander/0.2.0/defaults/cm.yaml
jira: https://jira.d2iq.com/browse/D2IQ-85356
An example of failing `pre-commit` check: https://teamcity.mesosphere.io/buildConfiguration/ClosedSource_Kommander2_KommanderApplications_PreCommitChecks/3357848?buildTab=log&focusLine=1865&linesState=450
> feat: Add versions of default enterprise apps (kommander-licensing)

- services/centralized-kubecost/0.22.1/defaults/cm.yaml
- services/centralized-kubecost/0.22.1/release/release.yaml
- services/dex/2.9.12/defaults/cm.yaml
- services/kubecost/0.22.1/defaults/cm.yaml
- services/kubecost/0.22.1/kubecost.yaml
JIRA: https://jira.d2iq.com/browse/D2IQ-81723
* Fixes use of outdated networking APIs in `kubecost` chart
* Updates dex to the latest version to be compatible with 1.22
Tests: https://github.com/mesosphere/kommander/pull/1480
> fix: add k8s 1.22 support for various configurations

- services/jaeger/2.29.0/defaults/cm.yaml
- services/jaeger/2.29.0/helmrelease.yaml
- services/jaeger/2.29.0/pre-upgrade.yaml
- services/jaeger/2.29.0/pre-upgrade/delete-jaeger-deployment.yaml
Better to use label selectors to select for the deployment to delete in pre-upgrade, to avoid deleting the newer deployment in any races. Newer jaeger versions added a label to the deployment that wasn't in the previous version, so using that to select against newer deployments.
> fix: Use label selector for jaeger pre-upgrade

- services/kommander-appmanagement/0.2.0/defaults/cm.yaml
- services/kommander/0.2.0/defaults/cm.yaml
This is a followup for following PRs:
* https://github.com/mesosphere/kommander-cli/pull/381
* https://github.com/mesosphere/kommander-applications/pull/228
* https://github.com/mesosphere/kommander-applications/pull/221
There were two problems that this PR solves:
* we need to define a default version for kommander-licensing subchart as it does not define sane defaults by itself. Cleaning it up is beyond the scope of the UniversalUpdater work.
* the substitute variable names in kommander v2.2.0 need to be different than the ones in kommander v2.1.0
The second bulletpoint requires some clarification - in v2.2.0 we are changing the way we supply the default version of kommander and kommander-appmanagement charts. 
Instead of storing it in k-cli, we moved it to k-apps repo. The substitute …
> refactor: rename kommander version variables

- services/kommander/0.2.0/defaults/cm.yaml
https://jira.d2iq.com/browse/D2IQ-85872
Kubecost will now be considered an enterprise app (and will be removed from the default set of apps)
> feat: Add kubecost as a default enterprise app

- services/kube-prometheus-stack/33.1.1/defaults/cm.yaml
https://jira.d2iq.com/browse/D2IQ-84979
This restores grafana metrics. Without this change, the default ServiceMonitor selector omits the grafana ServiceMonitor, and its metrics are not scraped.
> fix: Restore grafana metrics

- services/kube-prometheus-stack/33.1.1/defaults/cm.yaml
CI was failing with this:
```
kube-prometheus-stack         False   Helm install failed: unable to build kubernetes objects from release manifest: unable to decode "": json: cannot unmarshal bool into Go struct field ObjectMeta.metadata.labels of type string
```
https://teamcity.mesosphere.io/buildConfiguration/ClosedSource_Kommander2_Nightly_KommanderNonAirgappedTestsMultiCluster/3375632?buildTab=log&focusLine=3825&linesState=596 
I'm not sure a good way to integrate a check for this in k-apps CI/bloodhound without doing a full install of the chart 🤔
> fix: make the select label a string

- services/kommander-appmanagement/0.2.0/defaults/cm.yaml
Adds `airgapped.enabled` value to kommander-appmanagement chart
See why this change is required in description of https://github.com/mesosphere/kommander/pull/1534
Corresponding CLI change made at https://github.com/mesosphere/kommander-cli/pull/397
> chore: inject airgappedEnabled to kommander-appmanagement

- services/kube-prometheus-stack/33.1.4/defaults/cm.yaml
https://jira.d2iq.com/browse/D2IQ-86480
Fix to target all servicemonitors. Previously the ones defined in the chart weren't getting the necessary label; the only way to set the label on those servicemonitors is to add the label to the top-level `commonLabels` which get set on every resource. This means that we can't define them separately on other servicemonitors created via config in the chart, so removing those here.
> fix: Define servicemonitor labels at the top level

- services/gitea/4.1.1/defaults/cm.yaml
> The kubelet uses startup probes to know when a container application has started. If such a probe is configured, it disables liveness and readiness checks until it succeeds, making sure those probes don't interfere with the application startup. This can be used to adopt liveness checks on slow starting containers, avoiding them getting killed by the kubelet before they are up and running.
By adding a startupProbe gitea pod readiness check will be delayed and it will not accept commits when it is just beginning to initialize. Needed for https://github.com/mesosphere/kommander/pull/1562
> feat: enable startupProbe for gitea pod

- services/grafana-loki/0.33.2/defaults/cm.yaml
testing in https://github.com/mesosphere/kommander/pull/1612.
> chore(loki): Bump gateway nginx image tag

- services/kommander/0.2.0/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
https://jira.d2iq.com/browse/D2IQ-86874
If name is set, name will be used. If name is `""`, generateName will generate a name.
goes along with https://github.com/mesosphere/kommander/pull/1618
> fix: Add metadata name to mtls-proxy

- make/release.mk
Noticed a slight discrepancy between the gitrepo tarballs. Using `-` everywhere so switching the `_` here to `-`
```
Git Repo tarballs:
- dkp-catalog-applications: https://downloads.d2iq.com/dkp/v2.2.0-rc.3/dkp-catalog-applications-v2.2.0-rc.3.tar.gz
- kommander-applications: https://downloads.d2iq.com/dkp/v2.2.0-rc.3/kommander-applications_v2.2.0-rc.3.tar.gz
```
> fix: Use - instead of _ in arch name

- services/logging-operator/3.17.3/logging-operator-logging.yaml
- services/logging-operator/3.17.3/logging-operator.yaml
Logging operator fails to be upgraded with:
```
Helm Release logging-operator-logging NOT READY reason: UpgradeFailed message: Helm upgrade failed: [unable to recognize "": no matches for kind "EventTailer" in version "logging-extensions.banzaicloud.io/v1alpha1", unable to recognize "": no matches for kind "HostTailer" in version "logging-extensions.banzaicloud.io/v1alpha1"]
```
This PR solves the problem
> fix: Logging operator upgrade process

- services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml
- services/kommander/0.2.0/kommander.yaml
ensures CRDs are updated during kommander core upgrades - https://jira.d2iq.com/browse/D2IQ-87196
testing in https://github.com/mesosphere/kommander/pull/1648
> fix: Add crd policy to kommander HelmReleases

- services/centralized-kubecost/0.23.3/post-install-jobs/post-install-jobs.yaml
- services/centralized-kubecost/0.23.3/release/release.yaml
- services/gatekeeper/3.7.0/cleanup/cert-cleanup.yaml
- services/grafana-loki/0.33.2/minio.yaml
- services/jaeger/2.29.0/pre-upgrade/delete-jaeger-deployment.yaml
- services/minio-operator/4.4.10/minio-operator-pre-upgrade/delete-minio-operator-deployment.yaml
- services/project-grafana-loki/0.33.2/minio.yaml
- services/thanos/0.4.6/thanos.yaml
~Revert the kubectl revert (so, this PR brings them back) and~ set `ttlSecondsAfterFinished` on all jobs defined in kapps to ensure they are deleted after completion to avoid upgrade "immutable field" errors due to updated images etc.
Let's wait to bump images (except for CVE migitations) till after 2.2 GA.
> fix: Add ttl to jobs

- .gitignore
- make/release.mk
need to test this with kommander-cli
Right now, this prefix causes the UX for installing in an airgapped env a bit weird because users would have to do something like this:
```
dkp upgrade kommander --charts-bundle dkp-kommander-charts-bundle-v2.2.0.tar.gz --kommander-applications-repository kommander-applications-v2.2.0.tar.gz//kommander-applications
```
I tested this locally and it looked good!
```
➜  ~/Documents/projects/d2iq/kommander-cli git:(release-2.2) ✗ ./dist/kommander_darwin_amd64/kommander upgrade kommander --kommander-applications-repository ~/Documents/projects/d2iq/kommander-applications/kommander-applications-v2.2.0-dev.tar.gz 
✓ Ensuring upgrading conditions are met
✓ Ensuring application definitions are updated           <----- it would have failed here
✓ Ensuring …
```
> build: Remove prefix from git archive

- services/centralized-kubecost/0.23.3/post-install-jobs/post-install-jobs.yaml
- services/centralized-kubecost/0.23.3/release/release.yaml
- services/gatekeeper/3.7.0/cleanup/cert-cleanup.yaml
- services/grafana-loki/0.33.2/minio.yaml
- services/jaeger/2.29.0/pre-upgrade/delete-jaeger-deployment.yaml
- services/minio-operator/4.4.10/minio-operator-pre-upgrade/delete-minio-operator-deployment.yaml
- services/project-grafana-loki/0.33.2/minio.yaml
- services/thanos/0.4.6/thanos.yaml
This reverts commit 20a81bb8670e72fdd36f28d7045853972221ffbb.
Reverting adding ttl to our jobs defined in kapps since they should not get re-run (specifically, the gatekeeper cleanup job getting re-run would end up deleting secrets that may not get recreated in the helm chart is already deployed)
```
// Force instructs the controller to recreate resources
// when patching fails due to an immutable field change.
// +kubebuilder:default:=false
// +optional
Force bool `json:"force,omitempty"`
```
Post release, we will revisit setting these kustomizations `Force` to `true` to avoid the `immutable field` errors if we want to update the images in the jobs (instead of setting ttl).
> Revert "fix: Add ttl to jobs (#301)"

- .go-tools
- make/repo.mk
- `v2.2.0` is on `release-2.2` branch so in the current state, the daily
release tag is still `v2.2.0-dev`. With this commit, the daily release will be `v2.3.0-dev`.
- When releasing a rc, a daily tag should be bumped to the next minor, e.g., after releasing v2.3.0-rc.1, a daily tag should become v2.4.0-dev
jira: https://jira.d2iq.com/browse/D2IQ-87570
> fix: Produce correct tag for a daily release

- make/repo.mk
TeamCity doesn't fetch all tags when cloning the repo.
> fix: Fetch all tags before checking the most recent

- services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml
- services/kommander/0.2.0/kommander.yaml
Since v2.2.0 is released, let's use v2.3.0-dev as a default kommander version.
Depends on https://github.com/mesosphere/kommander/pull/1668
Depends on https://github.com/mesosphere/kommander-applications/pull/336
> feat: Bump default kommander to a new daily release

- services/istio/1.11.6/defaults/cm.yaml
https://jira.d2iq.com/browse/D2IQ-84836
Tested at https://github.com/mesosphere/kommander/pull/1639
> chore: Set istio's kubectl image to the latest release

- services/centralized-grafana/34.9.0/centralized-grafana.yaml
- services/kube-prometheus-stack/34.9.0/kube-prometheus-stack.yaml
- services/kube-prometheus-stack/metadata.yaml
- services/kubetunnel/0.0.12/kubetunnel.yaml
kube-prometheus-stack has been updating CRDs across upgrades, but we didn't ste the upgrade policy to `CreateReplace` so we're not actually updating the CRDs during upgrade. We'll need to backport this to get it into the next 2.2 patch.
Also saw that kubetunnel CRDs policy was only set on `install` not `upgrade`, I think we probably need both?
testing in https://github.com/mesosphere/kommander/pull/1687
> fix: Set CreateReplace upgrade policy on kps

- services/grafana-loki/0.48.3/minio.yaml
- services/project-grafana-loki/0.48.3/minio.yaml
This defines a set of user credentials for the MinIO Tenant used by Loki. This is necessary in order for minio-operator to create buckets when reconciling the Tenant.
Tested against kommander at https://github.com/mesosphere/kommander/pull/1718.
Tested manually on kind:
```
branden@crateria ~ % kubectl curl -n kommander "http://$(kubectl -n kommander get pod -l app.kubernetes.io/name=loki-distributed -l app.kubernetes.io/instance=grafana-loki -l app.kubernetes.io/component=gateway --no-headers -o custom-columns=:metadata.name)/loki/api/v1/labels"
{"status":"success","data":["__name__","alertmanager","app","app_kubernetes_io_component","app_kubernetes_io_instance","app_kubernetes_io_managed_by","app_kubernetes_io_name","app_kubernetes_io_part_of","app_kubernetes_io_version","chart","compone …
```
> fix: Set user creds on minio tenant

- services/grafana-loki/0.48.3/minio.yaml
- services/project-grafana-loki/0.48.3/minio.yaml
https://jira.d2iq.com/browse/D2IQ-88873
This renames the secret that contains root credentials for the MinIO tenant back to what it was in Kommander 2.2. This can help to prevent a situation where a MinIO tenant upgrade may become stuck if it was attempted while the tenant's MinIO API was unavailable. See https://jira.d2iq.com/browse/D2IQ-88873 for additional context.
Tested against kommander at https://github.com/mesosphere/kommander/pull/1744.
> fix: Put minio creds secret back at old name

- services/kommander/0.3.0/defaults/cm.yaml
https://jira.d2iq.com/browse/D2IQ-87209 
See https://github.com/mesosphere/kommander/pull/1698 and https://github.com/mesosphere/kommander-cli/pull/501 for more context
CLI generates git credentials and sops age secret to encrypt those
credentials and commit to the management git repository itself
during install time. After these are created, kommander
controllers should be responsible (implemented in [mesosphere/kommander#1698 (files)](https://github.com/mesosphere/kommander/pull/1698/files#diff-ecb9f4538d65070683a35f68a1214c4b76b0aa48121a150fb9feba4764de8320)) to ensure the secrets are kept
up-to-date (such as when the Certificate information changes) and
this change ensures that the necessary variables are set in
kommander-vars configmap (see …
> chore: sops encryption config params in kommander-vars cm

- services/minio-operator/4.4.16/minio-operator-helmrelease/release.yaml
While testing the grafana-loki upgrade from 2.1 -> 2.2, I found that this [change](https://github.com/mesosphere/kommander-applications/pull/390) allowed the tests to pass. However, in addition to the change, I needed to set this CRD policy on the `HelmRelease` so the Tenant CRD is updated with the new functionality introduced in  https://github.com/mesosphere/kommander-applications/pull/390.
> feat: add crds policy to minio-operator HelmRelease

- .tool-versions
- make/pre-commit.mk
As it was changed in release-2.2 a while ago, let's also fix git linting here.
> fix: Lint against release-2.1 branch, update tools

- services/grafana-loki/0.48.3/minio.yaml
When upgrading loki, there are a number of issues
when the tenant is upgraded. There was a permission
change in the minio-operator (see comment) and minio was OOMKilled
during the upgrade causing it to fail.
See https://jira.d2iq.com/browse/D2IQ-88873?focusedCommentId=382031&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-382031 for more info.
> fix: Update Loki tenant to support minio-operator upgrade

- .github/workflows/backport.yaml
Refer https://github.com/marketplace/actions/backport-action
If we decide to merge this change as-is, we will start labelling our PRs with 
```
auto-backport, backport-to-release-2.2
```
to backport a PR to `release-2.2` branch.
> build: add backport-action to repo

- .github/workflows/backport.yaml
action is currently failing with 
```
"status": "unhandled-error",
"error": {
"name": "SpawnError",
"context": {
"cmdArgs": [
"commit",
"--no-edit",
"--no-verify"
],
"code": 128,
"stderr": "Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <runner@fv-az119-428.ca0t41jjrjaujd4nublazzptxb.cx.internal.cloudapp.net>) not allowed\n",
"stdout": ""
}
}
}
```
https://github.com/mesosphere/kommander-applications/runs/6561494321?check_suite_focus=true 
this is an attempt to fix it.
> build: add backport-action user/email to GH action config

- services/grafana-loki/0.48.3/minio.yaml
- services/project-grafana-loki/0.48.3/minio.yaml
https://jira.d2iq.com/browse/D2IQ-88867
This PR expands Loki's storage from 40 GB to 80 GB. The daily cluster (7 nodes) consumes about 5 GB a day, which is 70 GB every two weeks. Loki's default retention period is two weeks.
This PR also updates the project Loki MinIO Tenant to match the workspace Loki, pulling in changes from #401.
This will need to be backported to release-2.2.
Tested against kommander at https://github.com/mesosphere/kommander/pull/1871.
> fix: Expand Loki storage

- services/grafana-loki/0.33.2/minio.yaml
- services/project-grafana-loki/0.33.2/minio.yaml
https://github.com/mesosphere/kommander-applications/pull/428
https://jira.d2iq.com/browse/D2IQ-88867
This PR expands Loki's storage from 40 GB to 80 GB. The daily cluster (7 nodes) consumes about 5 GB a day, which is 70 GB every two weeks. Loki's default retention period is two weeks.
This PR also updates the project Loki MinIO Tenant to match the workspace Loki, pulling in changes from #401.
This will need to be backported to release-2.2.
Tested against kommander at https://github.com/mesosphere/kommander/pull/1878.
> [release-2.2][BACKPORT] fix: Expand Loki storage

- services/kommander/0.3.0/defaults/cm.yaml
This static parameter was replaced with the dynamic value from KommanderCluster status in https://github.com/mesosphere/kommander/pull/1892.
> chore: kommander: remove unused parameter `ingressCertificateSecret`

- .gitignore
- Dockerfile.ci
- Makefile
- make/all.mk
- make/test.mk
- mergebot-config.json
Add e2e testing for kommander-applications
Tests:
- install, 
- upgrade - single cluster
Make commands:
- `make test.e2e.install VERBOSE=true`
- `make test.e2e.upgrade.singlecluster VERBOSE=true`
Remaining work:
> ci: add make targets to execute e2e tests

- hack/flux/update-flux.sh
zillionth attempt to make both the pre-commit and the kommander PR happy. 
https://github.com/mesosphere/kommander/pull/2003 and https://github.com/mesosphere/kommander-applications/pull/467 are created from the latest run so i think this should be the last PR.
> fix: usage of readonly var in `update-flux.sh`

- .github/pull_request_template.md
- adds a pull request template.
- This came up in sprint retro and the concern was that when bumping a chart, we _might_ forget to look at any intricacies in Licensing changes and as a first measure, lets add a template to remind that licensing is something that needs to be kept in mind when bumping upstream charts.
> build: add pull request template

- .go-tools
- .tool-versions
- make/repo.mk
- make/tools.mk
The current setup calculates `v2.2.2-dev` tag for `release-2.2` branch. it should be `v2.2.3-dev`.
Depends on https://github.com/mesosphere/gh-dkp/pull/88
https://jira.d2iq.com/browse/D2IQ-91465
```release-note
```
> feat: Use gh-dkp tool for calculating dev release name

- services/kommander-appmanagement/0.3.0/defaults/cm.yaml
when running in CI with konvoy on aws clusters, we need to override the images for the recently added appmanagement webhook and this change propagates the images from installer config into `kommander-vars` config map.
relates to https://github.com/mesosphere/kommander-cli/pull/628
> chore: wire appmgmt webhook images from installer config

- services/kube-prometheus-stack/34.9.3/kube-prometheus-stack.yaml
The KPS upgrade failed in this [test](https://teamcity.mesosphere.io/buildConfiguration/ClosedSource_Kommander2_KommanderCli_UpgradeE2eTestsMultiCluster/3542098?buildTab=log&focusLine=3005&expandAll=true) with a timeout of 1m. I am still not sure how that value is being set so lets set 5m for the install and upgrade sections.
```release-note
```
> fix: Add timeouts in install/upgrade

- .tool-versions
- make/repo.mk
- make/tools.mk
We need to use gh-dkp for daily tag calculation since the release tag is not in the release brach (but on a separate branch created specifically for the release).
- https://jira.d2iq.com/browse/D2IQ-91920
```release-note
```
> feat: Use gh-dkp tool for calculating dev release name (#474)

- mergebot-config.json
We haven't released 2.3.0 yet, so `release-2.3` needs to still be pointing to 2.3.0 until after GA, then we can update to 2.3.1
```release-note
```
> build: Bump mergebot release-2.3 version back to 2.3.0

- services/project-grafana-logging/metadata.yaml
- services/project-grafana-loki/metadata.yaml
- services/project-logging/metadata.yaml
https://github.com/mesosphere/kommander-applications/pull/497
Project logging apps should be platform apps, not catalog apps.
Dependent on UI piece of work https://jira.d2iq.com/browse/D2IQ-91829
depends on https://github.com/mesosphere/kommander/pull/2108
https://jira.d2iq.com/browse/D2IQ-91739
https://jira.d2iq.com/browse/D2IQ-91831
```release-note
```
> [release-2.3][BACKPORT] fix: Change project logging app metadata to type platform

- services/dex/2.9.19/dex.yaml
Bumps dex-controller chart from https://github.com/mesosphere/dex-controller/releases/tag/v0.6.21 
Depends on  https://github.com/mesosphere/charts/pull/1347
https://jira.d2iq.com/browse/D2IQ-91972 
```release-note
```
> feat: Bump `dex-controller` to `v0.6.21` by bumping `dex` to `2.9.19`

- services/fluent-bit/0.19.20/defaults/cm.yaml
- services/grafana-loki/0.48.4/defaults/cm.yaml
- This keeps it consistent with the limit used for the fluentbit deployed by logging-operator-logging here https://github.com/mesosphere/kommander-applications/blob/f36ee1ebe81bc0cb8dff171317f3afc39bfd5c28/services/logging-operator/3.17.7/defaults/cm.yaml#L104
- Bumps the fluentbit image to be consistent with fluentbit deployed by loki
- Bumps the grafana-loki nginx server client payload size to prevent these errors by fluentbit : 
```
[2022/07/28 20:14:29] [error] [output:loki:kubernetes_host] grafana-loki-loki-distributed-gateway.kommander.svc:80, HTTP status=413
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.22.0</center>
</body>
</html>
```
We can relax the constraints a bit more based …
> chore: relax logging stack resource limitations

- hack/release/cmd/prerelease/prerelease.go
- hack/release/pkg/chartversion/chartversion.go
- hack/release/pkg/chartversion/chartversion_test.go
Making a function public so it can be reused by post-release script.
- https://jira.d2iq.com/browse/D2IQ-91716
```release-note
```
> refactor: Make chart version updater functionality public

- services/grafana-loki/0.48.4/defaults/cm.yaml
Follow up of #516 
acc. to https://grafana.com/docs/loki/latest/configuration/#limits_config docs, since #516 bumped the max client payload to 10Mb we should bump ingester burst size to be at least 10Mb
```release-note
```
> chore: bump loki ingester limits as a precaution

- services/project-grafana-logging/metadata.yaml
- services/project-grafana-loki/metadata.yaml
- services/project-logging/metadata.yaml
Project logging apps should be platform apps, not catalog apps.
Dependent on UI piece of work https://jira.d2iq.com/browse/D2IQ-91829
https://jira.d2iq.com/browse/D2IQ-91739
https://jira.d2iq.com/browse/D2IQ-91831
```release-note
```
> fix: Change project logging app metadata to type platform

- services/fluent-bit/0.19.20/defaults/cm.yaml
- services/grafana-loki/0.48.4/defaults/cm.yaml
Backport of #516 #520 and #521 
See the stability of fix on daily at https://a05b80baca80e4e0a91eddd0c9f4b044-1570651377.us-west-2.elb.amazonaws.com/dkp/grafana/d/ZHfDq4kVz/test-mesosphere-kommander-applications-pull-520?orgId=1&from=now-6h&to=now 
or see the output of this cmd on daily:
```
k logs -nkommander daemonset/kommander-fluent-bit 
```
https://jira.d2iq.com/browse/D2IQ-91518
```release-note
```
> [release-2.3] chore: relax logging stack resource limitations

- services/grafana-loki/0.48.4/defaults/cm.yaml
follow up for #520 
i saw these errors on daily:
```
[2022/07/29 14:52:49] [error] [output:loki:kubernetes_audit] grafana-loki-loki-distributed-gateway.kommander.svc:80, HTTP status=500
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5458785 vs. 4194304)
[2022/07/29 14:52:49] [ warn] [engine] failed to flush chunk '1-1659070758.859689762.flb', retry in 794 seconds: task_id=849, input=kubernetes_audit > output=kubernetes_audit (out_id=0)
```
```release-note
```
> chore: bump grpc client size

- hack/release/cmd/postrelease/postrelease.go
- hack/release/pkg/appversion/appversion.go
- hack/release/pkg/appversion/appversion_test.go
- hack/release/pkg/chartversion/chartversion.go
- hack/release/pkg/constants/constants.go
Depends on #513
Moving kommander apps to new directories
https://jira.d2iq.com/browse/D2IQ-91716
```release-note
```
> feat: Move kommander apps into a new directory

- hack/release/pkg/appversion/appversion.go
Move shouldn't be performed if destination is the same as the source (the kommander version didn't change).
```release-note
```
> fix: Do not move if target is the same

- services/kommander-flux/0.31.5/templates/apps_v1_deployment_helm-controller.yaml
https://mesosphere.slack.com/archives/C01LNF6KML5/p1659625343482829
Based on some upgrade testing, it looks like the helm-controller was OOMKilled during the platform upgrade. Looking at the metrics from that cluster, we need to bump the memory and CPU limits which spike heavily during the upgrade.
https://aca569ee7816f4e62a18a4e21fe8eb8e-877128020.us-west-2.elb.amazonaws.com/dkp/grafana/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?var-datasource=default&var-cluster=&var-namespace=kommander-flux&var-pod=helm-controller-59758cb7d8-fgdqc&orgId=1&refresh=10s&from=now-6h&to=now
```release-note
```
**If the PR …
> fix: increase flux helm-controller memory/CPU limit

- services/grafana-loki/0.48.4/defaults/cm.yaml
- services/project-grafana-loki/0.48.4/defaults/cm.yaml
https://github.com/mesosphere/kommander-applications/pull/534
Implements https://jira.d2iq.com/browse/D2IQ-92137
which also fixes https://jira.d2iq.com/browse/D2IQ-91518
See
https://grafana.com/docs/loki/v2.3.x/configuration/#limits_config
https://grafana.com/docs/loki/v2.3.x/configuration/#compactor_config
https://grafana.com/docs/loki/v2.3.x/operations/storage/retention/
```release-note
```
> feat: enable compaction in grafana-loki defaults cm

- services/fluent-bit/0.19.20/defaults/cm.yaml
- services/grafana-loki/0.48.4/defaults/cm.yaml
- services/project-grafana-loki/0.48.4/defaults/cm.yaml
We found this on soak cluster
which means logging stack is generating the most amount of logs. This PR adds three changes:
1. Upgrades fluentbit log level from info to warn
2. Upgrades log level from info to warn in loki `config.server` block which applies to `querier`, `ingester` and other components.
3. Removes the `$objectRef[namespace]` reference in audit log output of fluentbit configuration.
For 3 above, this is a sample audit log:
```
tail  /var/log/kubernetes/audit/kube-apiserver-audit-2022-08-10T19-07-59.340.log -n1
.........(pretty formatted)....
{
"kind": "Event",
"apiVersion": "audit.k8s.io/v1",
"level": "Metadata",
"auditID": "dd8a547a-2c25-49f7-bd78-5337cd3b0bb2",
"stage": "ResponseComplete",
"requestURI": …
```
> fix: `warn` log level for multiple logging stack components

- services/grafana-loki/0.48.4/defaults/cm.yaml
- services/project-grafana-loki/0.48.4/defaults/cm.yaml
As a part of https://jira.d2iq.com/browse/D2IQ-91707, it was found that the `flush_op_timeout` is defaulted to 10s in Loki <2.5.0 and that was causing issues with Loki failing to startup as the object storage was down for a long time and the WAL built up so the initial flushing of the WAL was taking longer than 10s.
We should set the default here to avoid issues in the future with respect to changing Loki versions.
```release-note
```
> fix(loki): set flush_op_timeout to 10m

- services/dex/2.9.18/dex.yaml
https://github.com/mesosphere/kommander-applications/pull/518
This will backport the following commits from `main` to `release-2.3`:
- [feat: Bump dex-controller chart to v0.6.21 (#517)](https://github.com/mesosphere/kommander-applications/pull/517)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
> feat: Bump dex-controller chart to v0.6.21

- services/grafana-loki/0.48.4/defaults/cm.yaml
- services/project-grafana-loki/0.48.4/defaults/cm.yaml
- ~It looks like `ruler` was meant to be enabled, but it defaults to false so we need to explicitly set it to true. This was overlooked probably because a few other components are always enabled and do not have the enabled field to set.~  Wrangled with this a bit, and kept it disabled because it probably just makes sense for a user to enable it if they actually want to add some rules to evaluate. I at least updated the fields with some working values so that if it is enabled, the user just needs to add some rules and it shouldn't error otherwise.
- Updated project-grafana-loki values to be the same as grafana-loki (except for `ruler` which was explicitely set to `enabled: false` so I left that). We probably made changes to grafana-loki and forgot to …
> feat: Update project-grafana-loki values

- services/gatekeeper/3.8.1/defaults/cm.yaml
This disables the option of injecting an ignore label on the namespace where gatekeeper is installed (kommander). If enabled, gatekeeper ignores all policies set in the kommander namespace. This explicitly disables this behavior (we accidentally were doing this in kommander code; see https://github.com/mesosphere/kommander/pull/2173 and https://mesosphere.slack.com/archives/C02JG0RHADR/p1660852024096139?thread_ts=1660848620.702489&cid=C02JG0RHADR)
https://jira.d2iq.com/browse/D2IQ-91794
```release-note
```
> fix: Prevent gatekeeper from ignoring the kommander namespace

- make/test.mk
- mergebot-config.json
Bumps e2e upgrade from version and release-2.3 version mregebot-config post-2.3.0. Might have missed automating these in k-apps post-release bumps? But we are hoping to replace these e2e tests, so maybe we can leave that one out.
```release-note
```
> build: Bump e2e and mergebot config versions post-2.3

- services/fluent-bit/0.20.5/kustomization.yaml
- services/fluent-bit/0.20.5/resource-quota.yaml
- services/fluent-bit/0.20.5/resource-quota/resourcequota.yaml
Installing fluent-bit with priorityClass: system-critical-nodes on a GKE cluster resulted in these errors:
```
Events:
Type     Reason        Age                  From                  Message
----     ------        ----                 ----                  -------
Warning  FailedCreate  24s (x16 over 3m8s)  daemonset-controller  Error creating: insufficient quota to match these scopes: [{PriorityClass In [system-node-critical system-cluster-critical]}]
```
Fluent-bit fails to deploy on GKE clusters since GKE limits priority class consumption by default. See https://github.com/open-policy-agent/gatekeeper/issues/1120 for more info - we are running into the same issue with fluent-bit because we specify a priority class by default in our config. …
> feat: Deploy resource quota with fluent-bit

- services/grafana-loki/0.48.4/defaults/cm.yaml
While doing some Loki debugging and what not I noticed we are not collecting metrics from the distributor, this PR adds the required labels to the distributor service so it is targeted by the existing Prometheus ServiceMonitor
```release-note
```
> feat: collect Loki distributor metrics

- .github/workflows/kommander-revert-kapps-ref.yaml
Adds a new workflow that updates the same kommander branch (created from `open-kommander-pr` label) to point the k-apps ref in the Makefile back to `main`, when the k-apps PR is merged.
I tested this on my fork of kommander-applications -- see this kommander PR that was opened and then updated: https://github.com/mesosphere/kommander/pull/2294
https://jira.d2iq.com/browse/D2IQ-92487
```release-note
```
>  build: New workflow to revert k-apps ref

- .github/workflows/kommander-branch.yaml
- Use static commit message in case the message is too long
- Add step to post a comment with link to kommander branch (next iteration can be figuring out how to get the kommander PR #)
```release-note
```
> build: Improve kommander branch workflow

- services/cert-manager/1.7.1/release/release.yaml
Changes the ordering of the helmreleases for cert-manager so that dkp-bloodhound picks up the "primary" helmrelease first (the one that points to the upstream helm chart). This is because there's no way for our automated chart bump tool to know which of the two is the main one (without doing an explicit check).
https://jira.d2iq.com/browse/D2IQ-92952
```release-note
```
> chore: Switch cert-manager helmrelease order

- .github/workflows/stale-prs.yaml
Add workflow to mark PRs stale after 30d of inactivity, and to automatically close them if no activity is seen on it for another 10d
```release-note
```
> build: Add workflow for stale prs

- common/helm-repositories/kustomization.yaml
- common/helm-repositories/nvidia.yaml
- services/nvidia-gpu-operator/1.11.1/defaults/cm.yaml
- services/nvidia-gpu-operator/1.11.1/defaults/kustomization.yaml
- services/nvidia-gpu-operator/1.11.1/helmrelease.yaml
- services/nvidia-gpu-operator/1.11.1/helmrelease/nvidia.yaml
- services/nvidia-gpu-operator/1.11.1/kustomization.yaml
- services/nvidia-gpu-operator/metadata.yaml
Adds new `nvidia-gpu-operator` app which will be used instead of `nvidia` starting in 2.4
**The metadata.yaml file needs to be updated with new copy** --> https://jira.d2iq.com/browse/D2IQ-92963
https://jira.d2iq.com/browse/D2IQ-92632
I referenced https://docs.google.com/document/d/1Jj5SU1cz4TBZ0sUnczSCxq2cZtCeWMwdmR0I9LJ9PNk/edit and used the values passed into the `helm install` command there to set our defaults cm
```release-note
```
> feat: Add new nvidia-gpu-operator app

- services/kube-prometheus-stack/40.0.0/grafana-dashboards/calico.json
Using https://grafana.com/grafana/dashboards/12175-felix-dashboard-calico/, the same dashboard [from Calico's docs](https://projectcalico.docs.tigera.io/maintenance/monitor/monitor-component-visual).
1. ab01eca3d14bbc9788cdccc0ce4f4a625b730643 just imports the upstream json.
2. c37ccfdcf4679a51cf5d62a5233bcfc10b5a9fe9 reverts some of the changes for the datasource.
PR in Konvoy to enable metrics https://github.com/mesosphere/konvoy2/pull/1604
https://d2iq.atlassian.net/browse/D2IQ-90846
```release-note
```
> fix: Calico dashboard

- .github/workflows/kommander-branch.yaml
- .github/workflows/kommander-revert-kapps-ref.yaml
Improve workflows to support release branches, not just changes against `main`
- Instead of hardcoding the k-apps ref to `main` to sub in the Makefile, should use the base branch
- Include base branch in kommander branch name, to be used to create kommander PRs against (instead of creating them all against `main` -- kommander workflow updates: https://github.com/mesosphere/kommander/pull/2357)
```release-note
```
> build: Improve workflows to support release branches

- .github/workflows/kommander-branch.yaml
- .github/workflows/kommander-revert-kapps-ref.yaml
Hopefully the last fix to get the workflows working for release branches!
I tested these changes with https://github.com/mesosphere/kommander/pull/2362 - here is the successful run https://github.com/mesosphere/kommander-applications/actions/runs/3093745463/jobs/5006447769
```release-note
```
> build: Fix revert kapps workflow to work with release branches

- .github/workflows/kommander-branch.yaml
- .github/workflows/kommander-revert-kapps-ref.yaml
Backport the new workflows to create kommander branch if pr is labeled, and revert the k-apps ref when pr is closed
```release-note
```
> build: Add workflow to open kommander pr

- services/logging-operator/3.17.8/grafana-dashboards/kustomization.yaml
- services/logging-operator/3.17.8/grafana-dashboards/logging-stack-stress.json
A grafana dashboard for logging stack scale test specifically looking at logging stack stress(pod restart, terminate, component buffer/queue length)
https://d2iq.atlassian.net/browse/D2IQ-92686
```release-note
```
> feat: logging stack stress dashboard

- hack/release/cmd/postrelease/postrelease.go
- hack/release/cmd/prerelease/prerelease.go
- hack/release/cmd/root.go
- hack/release/go.mod
- hack/release/go.sum
- hack/release/pkg/chartversion/chartversion.go
- hack/release/pkg/chartversion/chartversion_test.go
https://github.com/mesosphere/kommander-applications/pull/513
Depends on #511
Ref. https://d2iq.atlassian.net/browse/D2IQ-92812?atlOrigin=eyJpIjoiZTQ1Y2I3NTNkN2UzNGU0Zjg2MDM4N2E0OTQ0NjRkMTgiLCJwIjoiaiJ9
- https://jira.d2iq.com/browse/D2IQ-91716
```release-note
```
> [release-2.2][BACKPORT] feat: Add post-release command

- services/nvidia-gpu-operator/1.11.1/defaults/cm.yaml
- services/nvidia-gpu-operator/1.11.1/grafana-dashboards/gpu-operator.json
- services/nvidia-gpu-operator/1.11.1/grafana-dashboards/kustomization.yaml
- services/nvidia-gpu-operator/1.11.1/kustomization.yaml
Creates a default configuration for GPU 
https://d2iq.atlassian.net/browse/D2IQ-93019
https://d2iq.atlassian.net/browse/D2IQ-92880
1. Create a GPU nodepool 
```
$ dkp create nodepool aws -c dkp-daily-3620240 --ami=ami-063f93c870491b17b --instance-type=p2.xlarge ubuntu20-p2
```
2. Enable the application 
3. apply the override cm 
```
apiVersion: v1
kind: ConfigMap
metadata:
namespace: kommander
name: nvidia-operator-overrides-cm
data:
values.yaml: |
nfd:
enabled: false
driver:
enabled: false
toolkit:
version: v1.11.0-ubuntu20.04
gfd:
enabled: true
dcgm:
enabled: true
version: 2.3.6-1-ubuntu20.04
dcgmExporter:
enabled: true
version: 2.4.6-2.6.10-ubuntu20.04
validator:
image: …
```
> feat: adds a default config for daily cluster for gpus

- services/dkp-insights-management/0.3.0/defaults/cm.yaml
- services/dkp-insights-management/0.3.0/helmrelease/helmrelease.yaml
Set DKP Insights Management to use `v0.3.0-beta.1` charts and images for the Beta release.
```release-note
```
> chore: Bump DKP Insights to v0.3.0-beta.1

- services/rook-ceph-cluster/1.10.1/defaults/cm.yaml
to make both linter and ceph happy
encountered this problem in CI, where the pvc of s3 bucket fails to bound due to storageclass being `""`
```release-note
```
> fix: explicitly set null for the sc

- services/kommander/0.4.0/defaults/cm.yaml
The nightly e2e tests failed because of https://github.com/mesosphere/kommander-applications/pull/687. 
The tests ended up trying to pull `999867407951.dkr.ecr.us-west-2.amazonaws.com/mesosphere/kommander2-kubetools:1.24.1` which doesn't exist. This is because we explicitly set the kubetools image repository in the CLI config file (https://github.com/mesosphere/kommander/blob/main/hack/cli-config-templates/kommander-cli-installer-config-konvoy-template.yaml#L92) but not the image.
To avoid changes to how things are setup, we can just not pass through a kubectl image and rely on our kubetools image.
```release-note
```
**If the …
> fix: do not set kubetools var for kommander

- .github/workflows/backport.yaml
- .github/workflows/kommander-branch.yaml
- .github/workflows/kommander-revert-kapps-ref.yaml
- .github/workflows/rebase.yaml
- .github/workflows/update-service-labeler.yaml
Now that we have GPG secrets in the repo, use them to sign commits in GH workflows
Was able to test service-labeler and komm pr workflows on this branch
but rebase is still using `main`, will have to try it once this merges.
```release-note
```
> build: Sign commits in gh workflows

- services/rook-ceph-cluster/1.10.3/defaults/cm.yaml
- services/rook-ceph-cluster/1.10.3/helmrelease/dashboard-cm.yaml
- services/rook-ceph-cluster/1.10.3/object-bucket-claims.yaml
- services/rook-ceph-cluster/1.10.3/objectbucketclaims/helmrelease.yaml
- services/rook-ceph-cluster/1.10.3/objectbucketclaims/kustomization.yaml
Creates `ObjectBucketClaims` for workspace level loki and velero services by default. The buckets are consumed by loki and velero in their configurations.
TODO:
https://d2iq.atlassian.net/browse/D2IQ-92897
```release-note
```
> feat: `ObjectBucketClaim`s from `rook-ceph-cluster` service

- services/kube-prometheus-stack/40.0.0/defaults/cm.yaml
This PR adds an override to the KPS default config-map, removing the newly added inhibition rules introduced in this [KPS Upstream PR](https://github.com/prometheus-community/helm-charts/pull/2115).
The reason for removing these inhibitions is that Insights needs Alertmanager to propagate all alerts to its webhook, even if there are `Info` and `Warning` alerts firing when a `Critical` alert is firing. The upstream PR specifically suppresses this behaviour as stated in the upstream PR:
https://d2iq.atlassian.net/browse/D2IQ-93506
This PR takes [Mesosphere KPS 40.0.0 chart values](https://github.com/mesosphere/charts/blob/master/staging/kube-prometheus-stack/values.yaml#L167-L208) …
> fix: Remove default inhibit-rules from KPS v40.0.0

- services/logging-operator/3.17.9/grafana-dashboards/logging-stack-stress.json
Found issue in logging scale test where all the legends in logging stress dashboard has `__auto` as the text.
https://d2iq.atlassian.net/browse/D2IQ-93354
```release-note
```
> fix: legendformat of logging stack stress dash

- services/rook-ceph-cluster/1.10.3/defaults/cm.yaml
- services/rook-ceph/1.10.3/defaults/cm.yaml
Resolves following polaris warning given by insights in daily cluster. I just bumped the value to a "next" reasonable threshold, no scaletesting or any other performance gauging was done to come up with these numbers:
```
$ k get insights -nkommander -ogo-template='{{range .items}}{{.spec.severity}} : {{.spec.description}}{{"\n"}}{{end}}' | grep ceph  | sort | grep -i cpu 
Critical : 65% throttling of CPU in namespace kommander for container watch-active in pod rook-ceph-mgr-b-785d77958d-4jmfw.<br>- 1 out of 1 pods in ReplicaSet **rook-ceph-mgr-b-785d77958d** in namespace **kommander** have an issue of this kind.
Notice : 29.79% throttling of CPU in namespace kommander for container rook-ceph-operator in pod rook-ceph-operator-5797b47886-nbp5w.<br>- 1 …
```
> chore: high cpu limits to avoid throttling

- .github/workflows/kommander-branch.yaml
- .github/workflows/kommander-revert-kapps-ref.yaml
Following GITHUB deprication of set-output command, I'm changing our jobs:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
```release-note
```
> chore: Set output of github actions in the new way

- mergebot-config.json
Post-release bumps are PRs created by [gh-dkp](https://github.com/mesosphere/gh-dkp/)
to adjust repositories after releases.
> feat: post release bumps

- services/gatekeeper/3.9.1/release/release.yaml
This is a forward port of https://github.com/mesosphere/kommander-applications/pull/642.
Once gatekeeper 3.10 is released, we can remove this patch and use helm values to set the TLS version
(https://github.com/open-policy-agent/gatekeeper/releases/tag/v3.10.0-beta.2)
https://d2iq.atlassian.net/browse/D2IQ-93143
```release-note
```
> fix: patch gatekeeper deployment to support FIPS clusters

- services/grafana-loki/0.48.6/defaults/cm.yaml
- services/grafana-loki/0.48.6/grafana-loki.yaml
- services/project-grafana-loki/0.48.6/defaults/cm.yaml
- services/project-grafana-loki/0.48.6/project-grafana-loki.yaml
- services/velero/3.3.0/defaults/cm.yaml
not sure why the looks like the s3 bucket secret can change after kommander install.
https://d2iq.atlassian.net/browse/D2IQ-92639
```release-note
```
> fix: make sure to reload upon s3 secret refresh

- services/logging-operator/3.17.9/grafana-dashboards/logging-stack-stress.json
fix the y axis labels to pick up kb/mb/gb unit
related to https://d2iq.atlassian.net/browse/D2IQ-93354
```release-note
```
> chore: use data unit for panels that counts bytes

- services/logging-operator/3.17.9/defaults/cm.yaml
- services/project-logging/1.0.3/project-logging.yaml
to help exploit the whole CPU
when log workload ramps up, fluentd might still not utilize the whole CPU. This helps 
details: https://docs.fluentd.org/deployment/performance-tuning-single-process#use-flush_thread_count-parameter
https://d2iq.atlassian.net/browse/D2IQ-93354
```release-note
```
> feat: enable multiple flush thread

- services/kommander-flux/0.35.0/templates/apps_v1_deployment_helm-controller.yaml
https://d2iq.atlassian.net/browse/D2IQ-92700
After upgrading to flux 0.33.0, the helm controller often got OOMKilled in the daily cluster. Despite these OOM kills no longer happening after the latest flux upgrade, the helm-controller memory consumption stays consistently over the declared requests (2x). This may expose the helm-controller to unwanted OOM restarts (which it may not tolerate well due to a known bug [D2IQ-92045](https://d2iq.atlassian.net/browse/D2IQ-92045) ) if memory is scarce on the local node. This PR increases requests to 250m to reflect the actual memory requirements.
```release-note
```
**If the PR adds a …
> fix: increase memory requests for helm-controller

- make/test.mk
- services/project-grafana-loki/0.48.6/defaults/cm.yaml
- services/rook-ceph-cluster/1.10.3/defaults/cm.yaml
Add erasure coded config for object store dataPool - See https://ceph.io/en/news/blog/2015/ceph-erasure-coding-overhead-in-a-nutshell/ to understand more about storage overhead.
With this PR we have parity with 2.3.x:
- Default capacity of storage is 160G. (we have 33% storage overhead, so this is ~106G usable space.)
- For reference, In 2.3.x we shipped with 80G x 3 (1xvelero, 1xgrafana-loki, 1xproject-grafana-loki) = 240G total space. And storage overhead was 50% so we had 120G usable space.
- Bumps the number of replicas for rados gateway pods. these are responsible for providing the S3 API on top of OSDs(object storage daemons that are responsible for raw storage).
- Caps the project logging at 5G. This is easily overridable by user when deploying …
> chore: erasure coded replication for ceph object store

- .github/pull_request_template.md
Updates pull request template to remind ourselves to bump the app version if/when needed.
```release-note
```
> chore: app version bump reminder in pull req template

- README.md
- hack/release/cmd/prerelease/prerelease.go
- hack/release/pkg/chartversion/chartversion_test.go
- hack/release/pkg/constants/constants.go
- hack/release/pkg/updatecapimate/updatecapimate.go
- hack/release/pkg/updatecapimate/updatecapimate_test.go
- licenses.d2iq.yaml
- services/kommander/0.4.0/defaults/cm.yaml
Closes D2IQ-93749
This adds CAPIMate to kommander applications and automatically updates it when pre release is ran.
https://d2iq.atlassian.net/browse/D2IQ-93749
To test this, run:
`cd hack/release`
`go run main.go pre-release --repo ~/Documents/d2iq/kommander-applications --version v2.4.0`
Note that the CAPIMate tag in the `cm.yaml` has been updated to 2.4.0
> chore: added capimate and automation script

- .github/workflows/validate-licenses.yaml
This update pulls in additional checks for unused image-source mappings and no longer suggests used image versions as upgradable.
https://d2iq.atlassian.net/browse/D2IQ-93766
```release-note
```
> chore: bump license check

- services/rook-ceph-cluster/1.10.3/defaults/cm.yaml
- services/velero/metadata.yaml
Ceph OSDs needs to be marked as portable so that when we drain a node, pods can be hopped from one node to another.
I tested this by doing the following:
```
$ dkp23 create cluster ... # create a 2.3 konvoy cluster 
$ dkp install kommander --kommander-applications-repository "github.com/mesosphere/kommander-applications.git?ref=tga%2Fportable-ceph-osds" ... # install kommander on 2.3 cluster from this PR
$ dkp23 update nodepool aws <name> --cluster-name=${CLUSTER_NAME} --kubernetes-version=v1.24.7 
```
And I made sure that the PDBs are created/destroyed acc. to guide at https://github.com/rook/rook/blob/release-1.10/design/ceph/ceph-managed-disruptionbudgets.md correctly.
I was able to drain all nodes and ceph is healthy post upgrade.
**Which issue(s) …
> chore: make ceph osds portable

- services/dkp-insights-management/0.3.0/defaults/cm.yaml
This makes DKP Insights aware of whether they should run in an airgapped mode or not.
https://d2iq.atlassian.net/browse/D2IQ-92403
This PR is a port of the airgapped flag propagation already working in the dev app (one in the `dkp-insights` repo) to a production app.
On its own, no.
**Checklist**
> feat: set dkp-insights-management `airgapped.enabled` from kommander var

- services/kube-prometheus-stack/40.0.0/defaults/cm.yaml
- services/velero/metadata.yaml
KPS prometheus-operator was using tls1.3 by default, set `tlsMinVersion` to 1.2
https://d2iq.atlassian.net/browse/D2IQ-93914
```release-note
```
**Checklist**
> fix: Override KPS tlsMinVersion to 1.2

- services/velero/3.3.0/defaults/cm.yaml
This PR solves a potential upgrade problem if Velero is configured to use AWS S3 for storage. In 2.3, `useSecret` was set to `true` (the default in the chart). In 2.4, we set it to `false` so an existing configuration that relied on that being `true` would break upon upgrade. 
We can keep the chart default value of `true` and also still be able to leverage `extraSecretRef` to load the Ceph creds into Velero via env vars. 
```release-note
```
**Checklist**
> fix: use default value for useSecret configuration

- licenses.d2iq.yaml
This PR fixes incorrect mappings discovered during the scan.
https://d2iq.atlassian.net/browse/D2IQ-91611
```release-note
```
**Checklist**
> fix: incorrect licenses mappings

- licenses.d2iq.yaml
The version of `kommander` container image is defined and updated in the `kommander` repository. This repository refers to `kommander` chart rolling version that changes its definition without event related to the `kommander-applciations` repo. This way the `kommander-ui` license mapping will go out of sync. 
This PR replaces static `kommander-ui` version with `${kommander-ui}` variable that will be provided when generating scan definition.
JIRA: https://d2iq.atlassian.net/browse/D2IQ-91611
```release-note
```
**Checklist**
> fix: use variable for kommander ui container license mapping

- licenses.d2iq.yaml
PR https://github.com/mesosphere/kommander-applications/pull/765 introduced var for `kommander-ui`. The envsubst library that `licenses` CLI uses for variable substituion https://github.com/drone/envsubst supports functions https://github.com/drone/envsubst#supported-functions where `${var-default}` means default variable value if not provided.
This PR fixes incorrect `${kommander-ui}` replacement var with `${kommander_ui}`.
JIRA: https://d2iq.atlassian.net/browse/D2IQ-91611
```release-note
```
**Checklist**
> fix: kommander-ui licenses variable name

- services/rook-ceph-cluster/1.10.3/defaults/cm.yaml
ceph dashboard is currently missing data. this is due to lack of the label in servicemonitor.
```release-note
```
**Checklist**
> fix: add kommander prometheus label

- licenses.d2iq.yaml
- services/grafana-logging/6.38.1/defaults/cm.yaml
- services/project-grafana-logging/6.38.1/defaults/cm.yaml
to workaround upstream issue for crash when looking at audit dashboard
https://d2iq.atlassian.net/browse/D2IQ-94038
```release-note
```
**Checklist**
> fix: use 8.5.14 for grafana-logging

- services/fluent-bit/0.20.9/resource-quota.yaml
- services/rook-ceph-cluster/1.10.3/defaults/cm.yaml
- Adjusts limits for CephCluster resources so that the default DKP installation requirement still stay somewhat reasonable (See 
how Ceph is an outlier here - https://d2iq.atlassian.net/wiki/spaces/DENT/pages/68124702/Workspace+Platform+Application+Defaults+and+Resource+Requirements )
- Increases the velero bucket maxSize so that backups size is similar to what was in 2.3.x 
Following screenshots are from @cwyl02's scaletesting cluster:
<details>
<summary>50 Node Cluster With Audit Logs Disabled, 400G (10% filled) space for CephCluster</summary>
OSD
MGR
MON
</details>
```release-note
```
**Checklist**
> feat: scale tested resources for ceph cluster

- services/rook-ceph-cluster/1.10.3/defaults/cm.yaml
- services/rook-ceph-cluster/1.10.3/grafana-dashboards/kustomization.yaml
- services/rook-ceph-cluster/1.10.3/grafana-dashboards/rook-ceph-cluster.json
- services/rook-ceph-cluster/1.10.3/grafana-dashboards/rook-ceph-osd.json
- services/rook-ceph-cluster/1.10.3/grafana-dashboards/rook-ceph-pools.json
- services/rook-ceph/1.10.3/defaults/cm.yaml
`label_values(cluster)` would be grabbing every possible value for the label `cluster` across all metrics. The label that ceph metrics use is actually called `rook_cluster`. We should be looking at an actual ceph metric and grabbing the possible values of the `rook_cluster` label instead. (I'm not sure how this worked in the past, maybe some other metrics somwhere happened to set a `cluster` label to `kommander` at some point?)
From https://grafana.com/docs/grafana/latest/datasources/prometheus/#query-variable
Also, noticed that duplicate metrics were getting scraped - looks like we were already scraping ceph metrics via our `kubernetes-pods` scrapeconfig which is scraping pods with the deprecated prometheus scrape annotations. We should disable that …
> fix: Fix cluster label var for rook ceph dashboard

- services/rook-ceph-cluster/1.10.3/defaults/cm.yaml
- services/rook-ceph-cluster/1.10.3/grafana-dashboards/rook-ceph-osd.json
Adjusting velero bucket size from 40G to 20G.
A single backup of a 50 node cluster took 10Mb:
Even if we create a hourly backups (which is very aggressive), 20G should save backups for close to 90days. 
Increases the grafana-loki bucket size so we have more room to grow there.
```release-note
```
**Checklist**
> chore: decrease velero capacity

- .github/workflows/validate-licenses.yaml
- licenses.d2iq.yaml
Enables source repo validation for the license mappings.
https://d2iq.atlassian.net/browse/D2IQ-94118
```release-note
```
**Checklist**
> build: enable license mapping source validation

- services/grafana-loki/0.48.6/defaults/cm.yaml
@cwyl02 found this error in the scale test environment:
```
2022-11-08 15:37:34 +0000 [warn]: #0 [clusterflow:small-7tkv6-k88ck:cluster-containers:clusteroutput:small-7tkv6-k88ck:loki] failed to write post to http://grafana-loki-loki-distributed-gateway.small-7tkv6-k88ck.svc.cluster.local/loki/api/v1/push (400 Bad Request entry for stream '{app="rook-ceph-osd", app_kubernetes_io_component="cephclusters.ceph.rook.io", app_kubernetes_io_created_by="rook-ceph-operator", app_kubernetes_io_instance="3", app_kubernetes_io_managed_by="rook-ceph-operator", app_kubernetes_io_name="ceph-osd", app_kubernetes_io_part_of="dkp-ceph-cluster", ceph_daemon_id="3", ceph_daemon_type="osd", ceph_osd_id="3", ceph_rook_io_DeviceSet="rook-ceph-osd-set1", …
```
> chore: bump label limit in workspace loki

- licenses.d2iq.yaml
- services/centralized-grafana/40.0.0/centralized-grafana.yaml
- services/grafana-logging/6.38.1/grafana.yaml
- services/jaeger/2.36.0/helmrelease/release.yaml
- services/kiali/1.57.1/defaults/cm.yaml
- services/kiali/1.57.1/kiali.yaml
- services/kube-prometheus-stack/40.0.0/helmrelease/kube-prometheus-stack.yaml
- services/kubecost/0.28.0/kubecost.yaml
- services/kubernetes-dashboard/5.11.0/kubernetes-dashboard.yaml
- services/traefik/10.30.1/traefik.yaml
- Just noticed that we are overriding kiali image for some reason, and that the chartbumper missed updating the image. I've removed the image override, not sure why it was there but we should always be using the version deployed with the chart (chart version looks to be aligned with img version).
- Also noticed that we missed bumping most of the app versions we are included in dashboard configmaps.
We'll need to cut another RC with these fixes.
```release-note
```
**Checklist**
> fix: Update dashboard app versions, bump Kiali img

- hack/release/cmd/postrelease/postrelease.go
- hack/release/cmd/root.go
- hack/release/go.mod
- hack/release/go.sum
- hack/release/pkg/appversion/appversion.go
- hack/release/pkg/appversion/appversion_test.go
- hack/release/pkg/chartversion/chartversion.go
- hack/release/pkg/chartversion/chartversion_test.go
- hack/release/pkg/constants/constants.go
- licenses.d2iq.yaml
It seems that post-release scripts were not present in release-2.3
```release-note
```
**Checklist**
> feat: Backport post-release script

- .github/workflows/validate-licenses.yaml
- licenses.d2iq.yaml
Fixes for `release-2.2` branch.
* Bumps license validation tool to `v0.0.6`
* Fixes discovered validation mappings when running tool with `check-sources` flag.
https://d2iq.atlassian.net/browse/D2IQ-91611
```release-note
```
**Checklist**
> chore: bump license validation tool to v0.0.6

- .github/workflows/validate-licenses.yaml
- licenses.d2iq.yaml
Fixes for `release-2.3` branch.
* Bumps license validation tool to `v0.0.6`
* Fixes discovered validation mappings when running tool with `check-sources` flag.
https://d2iq.atlassian.net/browse/D2IQ-91611
```release-note
```
**Checklist**
> fix: license mapping (2.3)

- .github/workflows/validate-licenses.yaml
https://d2iq.atlassian.net/browse/D2IQ-94119
```release-note
```
**Checklist**
> build: use pre-built Docker image for license check

- services/reloader/0.0.121/defaults/cm.yaml
When Loki is deployed, the ceph operator can delete and recreate the dkp-loki secret. We need reloader to reload the loki deployments when the secret
is recreated.
https://d2iq.atlassian.net/browse/D2IQ-94260
```release-note
```
**Checklist**
> fix: enable reloading on creation of secrets

- licenses.d2iq.yaml
- services/velero/3.3.0/defaults/cm.yaml
https://github.com/mesosphere/kommander-applications/pull/808
Co-Authored-by: <mikolajb@gmail.com>
https://d2iq.atlassian.net/browse/D2IQ-94272
```release-note
```
**Checklist**
> fix: bump velero aws plugin for compatibility

- licenses.d2iq.yaml
License check is failing on main and this fixes it
```release-note
```
**Checklist**
> chore: bump reloader image in licenses

- services/rook-ceph-cluster/1.10.3/kustomization.yaml
- services/rook-ceph-cluster/1.10.3/pre-install.yaml
- services/rook-ceph-cluster/1.10.3/pre-install/ceph-crd-check.yaml
- services/rook-ceph-cluster/1.10.3/rook-ceph-cluster.yaml
To reuse an existing ceph operator, this PR removes the dependson for ceph cluster with a pre install CRD presence check.
https://d2iq.atlassian.net/browse/D2IQ-94295
```release-note
```
**Checklist**
> chore: simply wait for CRDs instead of operator

- services/traefik/10.30.1/traefik.yaml
Noticed that the traefik docs link pointed in UI was stale
```release-note
```
**Checklist**
> fix: bump version in traefik docs link

- .tool-versions
- hack/release/go.mod
Bump go version to 1.19 for release hack
--
--
--
**Checklist**
Depends on #831
> build(deps): use go 1.19

- .github/workflows/validate-licenses.yaml
This pulls in this fix: https://github.com/mesosphere/dkp-infra-tools/pull/118
```release-note
```
**Checklist**
> build: bump license check

- make/ci.mk
- make/test.mk
This problem fixes some missing variables in the install-e2e pipeline.
```release-note
```
**Checklist**
> fix: add license variables to fix install-e2e check

- .bloodhound.yml
Now that all apps are updated, check for compatibility.
https://d2iq.atlassian.net/browse/D2IQ-94158
```release-note
```
**Checklist**
> build: enable K8s 1.25 in Bloodhound checks

- services/logging-operator/3.17.10/defaults/cm.yaml
The logging-operator [switch to using a new repository](https://github.com/banzaicloud/logging-operator/pull/1108/files#diff-911a398d9218f00dc5749daedc4d64b64f16f2f8b010c898dc28393b3454fd0dR134) for the config-reloader image so we should use that by default. 
We bumped the logging-operator which changed the default repo but since we override the tag, its trying to pull the wrong image.
More context: https://mesosphere.slack.com/archives/C03P4F14M7E/p1671204117585399
```release-note
```
**Checklist**
> fix: use default fluentd image

- .github/workflows/kommander-branch.yaml
This automates updating tests and docs where the application name and version are specified to match the following syntax: `{appname}-{semver}` (i.e. `external-dns-1.2.3`).
Note that these cases are not covered in docs since the application name does not match:
```
export EXTERNAL_DNS_VERSION=6.11.3
```
https://d2iq.atlassian.net/browse/D2IQ-94403
See results in test PR (due to this branch name): https://github.com/mesosphere/kommander/pull/2691
```release-note
```
**Checklist**
> feat: open-kommander-pr modifies kommander tests for auto bumps

- .bloodhound.yml
- make/validate.mk
Bump outdated bloodhound on `release-2.2`, which leads to failing checks
```release-note
```
**Checklist**
> build: bump bloodhound to 0.8.1

- common/helm-repositories/bitnami.yaml
https://github.com/bitnami/charts/issues/10833
> On June 2nd, the Helm chart index stored at https://charts.bitnami.com/bitnami was truncated only containing entries for the latest 6 months (from January 2022 on).
> 🔧 Where can I find the full index.yaml?
The whole index.yaml is being generated and stored in GitHub, not in the CDN. You can find it in the [archive-full-index branch](https://github.com/bitnami/charts/tree/archive-full-index). If you want to keep using older versions and the size or speed is not critical, feel free to use this one.
> $ helm repo add bitnami-full-index https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
"bitnami-full-index" has been added to your repositories …
> fix: Use archive full index bitnami helmrepo url

- make/test.mk
No need to create lvms in release-2.3 as ceph was first introduced in 2.4
```release-note
```
**Checklist**
> test: disable lvm in release-2.3

- .github/services-pr-labeler.yaml
Block PRs from getting merged if they have corresponding kommander PRs that require tests to pass first.
```release-note
```
**Checklist**
> ci: Add DNM label to bump PRs requiring komm pr

- hack/flux/flux-update-kustomization.yaml
- services/kommander-flux/0.38.2/templates/apps_v1_deployment_kustomize-controller.yaml
Increases the `kustomize-controller` concurrency to 15, mainly to speed up the installation process. We have a ton of kustomizations (half of which are just ConfigMaps), so an easy win for speeding up the installation process is to increase the concurrency from 4 to 15. In a few tests, this saved 10-15 minutes while waiting for all the platform applications to be ready.
I made this change on the daily and saw some CPU spikes so I've bumped that as a extra precaution (memory seemed fine):
https://d2iq.atlassian.net/browse/D2IQ-95122
```release-note
```
**Checklist**
> feat: bump kustomize-controller concurrency to 15

- hack/release/pkg/constants/constants.go
- hack/release/pkg/updatecapimate/updatecapimate_test.go
- services/kommander/0.3.2/defaults/cm.yaml
there are no nightly capimate dev builds for previous releases. update the image to use the last stable version instead.
```release-note
```
**Checklist**
> fix: Use last stable capimate build (2.3)

- services/kommander/0.5.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
Bumping cluster observer to https://github.com/mesosphere/kommander-auditing-pipeline/releases/tag/1.1.0
https://d2iq.atlassian.net/browse/D2IQ-94892
```release-note
```
**Checklist**
> feat: bump cluster observer to `1.1.0`

- hack/release/pkg/constants/constants.go
- hack/release/pkg/updatecapimate/updatecapimate_test.go
- services/kommander/0.2.4/defaults/cm.yaml
for release branches, pin the capimate image to the latest stable release. when konvoy starts releasing dailies from release branches, we can adjust these to be the relevant dev versions
```release-note
```
**Checklist**
> fix: Fix capimate image to be last stable (2.2)

- .github/workflows/validate-licenses.yaml
- make/release.mk
- make/validate.mk
Moves from downloads.mesosphere.io -> downloads.d2iq.com
CI on main is failing due to the deprecation of the mesosphere cloudfront distribution
```release-note
```
**Checklist**
> build: use downloads.d2iq.com

- hack/release/pkg/constants/constants.go
- hack/release/pkg/updatecapimate/updatecapimate_test.go
- services/kommander/0.4.1/defaults/cm.yaml
for release branches, pin the capimate image to the latest stable release. when konvoy starts releasing dailies from release branches, we can adjust these to be the relevant dev versions
```release-note
```
**Checklist**
> fix: Fix capimate image to be last stable (2.4)

- services/traefik/20.8.0/defaults/cm.yaml
I found a comment that mentions to remove the settings after the migration. Because migration is not supported in the current version, let's try to remove it.
```release-note
```
**Checklist**
> feat: Remove allowcrossnamespace from traefik configuration

- charts/kommander-operator/values.yaml
Use kommander operator image in a chart.
Depends on https://github.com/mesosphere/kommander/pull/2920
```release-note
```
**Checklist**
> feat: Use newly created operator image

- make/release.mk
Reverting the s3 bucket name change in #935  since we changed only the URL, not the bucket name.
```release-note
```
**Checklist**
> fix: revert s3 bucket name

- charts/kommander-operator/templates/deployment.yaml
- charts/kommander-operator/templates/rback_v1_clusterrole_binding_operator_kommander-operator.yaml
- charts/kommander-operator/templates/rback_v1_clusterrole_operator_kommander-operator.yaml
It was missing a few permissions
```release-note
```
**Checklist**
> fix: Add necessary permissions to kommander-operator chart

- charts/kommander-operator/crds/crd_kommandercores.yaml
Bumps the KommanderCore CRD to a version with Status as Subresource.
```release-note
```
**Checklist**
> chore: update crd kommandercore

- make/release.mk
Include `charts` directory in a release
```release-note
```
**Checklist**
> fix: Include charts in kommander applications release

- .github/workflows/labeler.yaml
Avoid creating kommander branch/pr for PRs that are not automated chart bump PRs
```release-note
```
**Checklist**
> ci: Only run pr labeler on chartbump prs

- services/rook-ceph-cluster/1.10.10/pre-install.yaml
- services/rook-ceph-cluster/1.10.10/pre-install/ceph-crd-check.yaml
Alternative of #965 
With current ceph upgrade of 1.10.6 -> 1.10.10 which is flaking, i think the problem is : 
```
t=0 | everything was healthy, both rook-ceph and rook-ceph-cluster were running at 1.10.6
t=1 | kicked off upgrade to 1.10.10 for both rook-ceph and rook-ceph-cluster  HelmReleases
t=2 | rook-ceph was in process of deleting the webhook.
t=2 | (same time as above) rook-ceph-cluster helm upgrade tried to mutate CephCluster and other resources. The ValidatingWebhookConfiguration is still present but probably the pod/service is being terminated.
The problem is last two actions happen at t=2 . instead rook-ceph-cluster should be upgraded AFTER completing the upgrade of rook-ceph.
```
Based on how the last two actions happen, we hit the flake …
> feat: wait for ceph operator in ceph cluster preupgrade

- charts/kommander-operator/values.yaml
- common/kommander-operator/helmrelease.yaml
- hack/release/pkg/chartversion/chartversion.go
- hack/release/pkg/chartversion/chartversion_test.go
To make it easier to test kommander operator, let's make it possible to override the version with kommander-vars.
```release-note
```
**Checklist**
> feat: Automate kommander operator docker images versioning

- services/rook-ceph-cluster/1.10.8/pre-install.yaml
- services/rook-ceph-cluster/1.10.8/pre-install/ceph-crd-check.yaml
Backport of #968 
https://d2iq.atlassian.net/browse/D2IQ-95736
See #968 for details
```release-note
```
**Checklist**
> feat: wait for ceph operator in ceph cluster preupgrade (2.4)

- licenses.d2iq.yaml
- services/dex/2.10.0/defaults/cm.yaml
Allows dex server to start even if one or more connectors is misconfigured.
This change does not affect any other dex functionality, and we want to automatically apply this fix, so I'm not bumping the chart version.
https://d2iq.atlassian.net/browse/D2IQ-95346
```release-note
dex: Allow server to start even if one or more connector is misconfigured.
```
**Checklist**
> feat: Enable "lazy" connector initialization in dex

- .github/workflows/kommander-branch.yaml
- services/istio/metadata.yaml
- services/jaeger/metadata.yaml
- services/kiali/metadata.yaml
This PR categorizes istio as an platform application.
https://d2iq.atlassian.net/browse/D2IQ-95625
```release-note
* Istio, kiali and jaeger are now a platform applications
```
**Checklist**
> feat: recategorize istio, kiali, jaeger as platform app, add supported and certified bages

- licenses.d2iq.yaml
- services/traefik/20.8.0/defaults/cm.yaml
- services/velero/3.4.0/defaults/cm.yaml
- services/velero/3.4.0/helmrelease/helmrelease.yaml
- services/velero/3.4.0/kustomization.yaml
- services/velero/3.4.0/post-install/post-install-job.yaml
- services/velero/3.4.0/velero-post-install.yaml
Prior to migrating to ceph from minio, we had an initContainer defined in velero that updated the s3Url config in velero to point to the public endpoint for the minio bucket. ~This brings back that initContainer~ to update the config to point to the ceph `dkp-velero` bucket public endpoint. This enables users to be able to use the velero cli to view logs.
Doing this in an initContainer no longer worked, because the backupstoragelocation is created in a post-install hook so the object doesn't exist when the initcontainer runs, which tries to update that object. In our velero forked helm chart, we disabled helm hooks, so the object existed and was able to be updated in the initcontainer. Instead, I have added a post-install kustomization that runs a job …
> feat: Add post-install job to overwrite velero s3Url

- services/gatekeeper/3.11.0/release/release.yaml
This PR works around a recent change to the gatekeeper mutating and validation webhooks in `v3.11.0`. 
The release namespace is now being ignored in https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/templates/gatekeeper-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml#L29-L32. 
To work around this, we can patch the hardcoded matchExpressions that ignores the release namespace until we can move it to a different namespace (hopefully next release).
https://d2iq.atlassian.net/browse/D2IQ-95922
```release-note
```
**Checklist**
> fix: patch mutating/validating gatekeeper webhooks

- .github/workflows/validate-licenses.yaml
- licenses.d2iq.yaml
Automates the process of bumping images in licenses.d2iq.yaml by using the new 'update' flag for image mapping. 
https://d2iq.atlassian.net/browse/D2IQ-95738 
The last commit in this PR is and example run of an automated image bump. Two images were manually changed to outdated versions. Mergebot created a pr to remedy this.
As comments are not included in new versions of licenses.d2iq.yaml, there will be a follow-up pr which updates the documentation in this repo's README.
```release-note
```
**Checklist**
> feat: automate image bump for licenses.d2iq.yaml

- services/kommander/0.5.0/defaults/cm.yaml
Add `managementApps` to kommander default values to go along with https://github.com/mesosphere/kommander/pull/3088
https://d2iq.atlassian.net/browse/D2IQ-96050
```release-note
```
**Checklist**
> feat: Add managementApps to kommander default values

- .github/workflows/validate-licenses.yaml
- licenses.d2iq.yaml
makes GHA to update license.d2iq.yaml optional based on the use of the 'update-licenses' label until check licenses is debugged
Ex. of incorrect bug in check-licenses: https://github.com/mesosphere/kommander-applications/pull/1008/commits/f4b46edb84153fbdfa29c0a71c0acf8542f2a194 
```release-note
```
**Checklist**
> fix: update validate license to be opt-in

- services/kommander/0.5.0/defaults/cm.yaml
Kubetunnel is a mgmt only application, we can ignore it while copying over appdeployments during expansion.
```release-note
```
**Checklist**
> fix: Add kubetunnel to list of management apps

- services/dex/2.11.1/defaults/cm.yaml
noticed the indentation was off here
partially mentioned in https://d2iq.atlassian.net/browse/D2IQ-96189
```release-note
```
**Checklist**
> fix: Fix indentation in dex defaults cm

- services/kube-prometheus-stack/44.2.1/defaults/cm.yaml
This bumps it up to match what we were originally setting in the KPS overrides (for mgmt cluster). The diff in resources here is small and doesn't hurt to bump here to be the default. This allows us to also remove this override from the KPS overrides.
goes with https://github.com/mesosphere/kommander-cli/pull/986
https://d2iq.atlassian.net/browse/D2IQ-96187
```release-note
```
**Checklist**
> feat: Bump up alertmanager resource requests

- services/karma-traefik/0.0.1/karma-traefik.yaml
- services/kubecost-thanos-traefik/0.0.1/kubecost-thanos-traefik.yaml
- services/prometheus-thanos-traefik/0.0.1/prometheus-thanos-traefik.yaml
This HelmRelease can exist without their dependencies, so lets remove them.
This will also allow us to deploy `kubecost-thanos-traefik` (and other) without requiring `kubecost` to be installed which will help with the expansion feature.
relates to https://github.com/mesosphere/kommander/pull/3128/files
```release-note
```
**Checklist**
> fix: remove thanos-traefik HR dependsOn

- services/kube-prometheus-stack/44.2.1/grafana-dashboards/controller-runtime.json
- services/kube-prometheus-stack/44.2.1/grafana-dashboards/kustomization.yaml
Adds a very basic dashboard to visualize some controller-runtime metrics grabbed from https://book.kubebuilder.io/plugins/grafana-v1-alpha.html. 
https://d2iq.atlassian.net/browse/D2IQ-94330
Open to discussing where to put this dashboard but this seems like a neutral place, let me know if there's a better spot!
```release-note
```
**Checklist**
> feat: Add controller-runtime Grafana dashboard

- services/kiali/1.63.2/defaults/cm.yaml
- use correct grpc port for jaeger in kiali config (`use_grpc` defaults to `true`, so just explicitly setting it here to prevent future confusion)
- add prometheus health check endpoint explicitly, which fixes the "Unreachable" errors
- overwrite the istio components to not include "istio-egressgateway" component since it is not deployed in our istio app by default
https://d2iq.atlassian.net/browse/D2IQ-96214
```release-note
```
**Checklist**
> fix: Fix errors in kiali config

- services/kiali/1.63.2/defaults/cm.yaml
I haven't been able to figure out how to fix the `grafana URL is not set in Kiali configuration` error, but since this just enables links to grafana directly from the kiali dashboard, I think we can just disable the integration and avoid the error in the UI. This is technically a "feature" so if we feel like we must provide this feature in the future, then we can come back to this bug.
https://d2iq.atlassian.net/browse/D2IQ-96214
```release-note
```
**Checklist**
> fix: Disable grafana links in kiali dashboard

- common/base/kustomization.yaml
This change was applying automatically to ALL attached clusters during mgmt cluster upgrade (upgrade of k-apps repo) which had their kustomization still pointing to the ./common/base. In order to avoid this, we need to move koperator path out of ./common/base resources and only install it on the mgmt cluster during install and upgrade (being done in https://github.com/mesosphere/kommander-cli/pull/990).
To test, I tagged `v2.5.0-dev` off my kcli branch (https://github.com/mesosphere/kommander-cli/pull/990) and am running kommander CI pointing to this kapps branch https://github.com/mesosphere/kommander/pull/3146
https://d2iq.atlassian.net/browse/D2IQ-96232
**Does this PR …
> fix: Remove koperator from base kustomization

- .github/workflows/kommander-branch.yaml
Automated chart bump removes parts of image refs, ex: https://github.com/mesosphere/kommander/pull/2852/files#diff-43b0f650494b2bde2938c28871eab2581680248ffa7014c60a2d798629cd9b2dR9
https://d2iq.atlassian.net/jira/software/c/projects/D2IQ/boards/61?modal=detail&selectedIssue=D2IQ-95823&sprint=1950
Example kommander branch created without this fix: https://github.com/mesosphere/kommander/pull/3143/files#diff-43b0f650494b2bde2938c28871eab2581680248ffa7014c60a2d798629cd9b2dR9
Example of kommander branch created with this fix: https://github.com/mesosphere/kommander/pull/3148/files#diff-43b0f650494b2bde2938c28871eab2581680248ffa7014c60a2d798629cd9b2dR9
**Does this PR introduce a …
> fix: Kommander bump PRs overwriting suffixes

- services/kubecost/0.33.1/defaults/cm.yaml
In light of https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/ we can anticipate a future cops issue when a customer tries to pull the image from the old registry. Until we can bump kubecost (its right around the corner - https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.101.0-rc.3 ) we can override configmap values to not use the `k8s.gcr.io` registry.
```release-note
```
**Checklist**
> fix: use registry.k8s.io image

- licenses.d2iq.yaml
- services/velero/3.4.0/post-install/deployment_update-backupstoragelocation.yaml
Create a deployment to run an informer watching velero BackupStorageLocation objects to update the s3Url in the config to point to the publicly exposed endpoint so that the "velero backup logs" command succeeds. This replaces the job that would have only run the update once at installation -- subsequent upgrades would have reset the endpoint back to the default internal svc address.
depends on https://github.com/mesosphere/kubeaddons-extrasteps/pull/378 + release. When that is released, I will update the tag here.
https://d2iq.atlassian.net/browse/D2IQ-95509
```release-note
```
**Checklist**
> fix: Run informer in deployment for velero post-install

- licenses.d2iq.yaml
- services/velero/3.3.1/post-install/deployment_update-backupstoragelocation.yaml
backports #1048 
```release-note
```
**Checklist**
> fix: Run informer in deployment for velero post-install (2.4)

- services/kommander/0.5.0/defaults/cm.yaml
keep the old gitea instance on the essential cluster
https://d2iq.atlassian.net/browse/D2IQ-96394
```release-note
```
**Checklist**
> fix: keep gitea during expansion workflow

- services/kube-prometheus-stack/44.2.1/helmrelease/kube-prometheus-stack.yaml
Always add optional CM for KPS HR for mgmt specific overrides that will be created in the kcli. This is so that we can allow users to use the workspace configOverrides for their own custom configuration. Right now, users would edit and existing `kube-prometheus-stack-overrides` CM with our mgmt override values, and because of that, we have not been able to automatically update that CM for existing versions if we had any updates, and also results in a bug during expansion, since the mgmt overrides are not compatible with an attached cluster setup.
This work is done in tandem with changes in the CLI to create a new `kube-prometheus-stack-mgmt-overrides` CM that also gets updated during upgrades. To assist with upgrades from previous versions, we will …
> feat: Add optional mgmt overrides cm to KPS HR

- .github/workflows/validate-licenses.yaml
This check has been silently failing because of the `continue-on-error: true`. We previously used that to know when to run the update step but that has since been disabled by default.
For now, lets remove those steps and ensure this check fails if the images aren't up to date and prioritize https://d2iq.atlassian.net/browse/D2IQ-96183 to fix the automation.
```release-note
```
**Checklist**
> fix: ensure license check fails check

- services/logging-operator/3.17.9/defaults/cm.yaml
This PR sets the default image repo for the config reloader image used in the logging-operator-logging chart. 
This should fix an upgrade issue from 2.4 to 2.5 where the logging-operator fluentd pod fails to pull an image post-upgrade.
This happens because we upgrade the `logging-operator` first, then the `logging-operator-logging` HR. The `logging-operator` upgrades and applies the new default image repo for the config-reload image (`ghcr.io/banzaicloud/config-reloader`). But the `logging-operator-logging` HR hasn't been upgraded yet (it depends on the logging-operator), so the `Logging` CR still references the `v0.7.1` tag but is using the new default image repo. This results in the fluentd pod trying to pull …
> fix: set config reloader image repo explicitly (2.4)

- licenses.d2iq.yaml
- services/rook-ceph-cluster/1.10.11/defaults/cm.yaml
In certain vsphere environments @jonathanbeber has found that `CephObjectStore` does not get healthy ootb. Upon further investigation done by @cbuto the error seems to be 
```
k describe cephobjectstore -nkommander dkp-object-store     
....
Events:
Type     Reason           Age                   From                         Message
----     ------           ----                  ----                         -------
Warning  ReconcileFailed  8m42s (x20 over 71m)  rook-ceph-object-controller  failed to reconcile CephObjectStore "kommander/dkp-object-store". failed to create object store deployments: failed to configure multisite for object store: failed create ceph multisite for object-store ["dkp-object-store"]: failed to commit config changes after …
```
> feat: run ceph toolbox deployment by default

- .github/workflows/validate-licenses.yaml
Integrates fix in dkp-infra-tools to remove automated license removal for unused licenses. Check licenses automation continues to be 'opt-in' via the 'update-licenses' label
For: https://d2iq.atlassian.net/jira/software/c/projects/D2IQ/boards/61?modal=detail&selectedIssue=D2IQ-96183&sprint=1959&assignee=63289bb1748d1bfcb855df3a
```release-note
```
**Checklist**
> fix: update automatic license bump to run with label

- common/priority-classes/dkp-priority-classes.yaml
- common/priority-classes/kustomization.yaml
Add new DKP priority class manifests directly to the gitrepo under `/common/base` since these manifests should always be deployed to both the mgmt cluster and the attached clusters. These will automatically get applied during upgrade first (with gitrepo update), before other apps are upgraded, which is required since these upgraded apps will be updated to use the priority classes.
This works for attached cluster upgrades as well, because the kommander flux controller will be upgraded already with kommander upgrade, and once the upgraded flux controller is running, it will automatically apply the new "federated global manifests" (which include the kustomization pointing to `./common/priority-claasses/` -- added in …
> feat: Add dkp priority class manifests to common/base

- services/dex-k8s-authenticator/1.2.14/defaults/cm.yaml
This PR increases to 6 the failureThreshold for the DKA liveness probe to prevent failures when the number of clusters to parse is >=50. The long time required to read the configuration file made the application to not respond correctly to liveness probe, resulting in CrashLoopBackoff. 
Ref. https://d2iq.atlassian.net/browse/D2IQ-94340
Ref. https://d2iq.atlassian.net/browse/D2IQ-96636
```release-note
```
**Checklist**
> fix: increase the failureThreshold of the DKA liveness probe #1407

- services/grafana-logging/metadata.yaml
- services/grafana-loki/metadata.yaml
- services/kube-oidc-proxy/metadata.yaml
- services/kubernetes-dashboard/metadata.yaml
- services/project-grafana-logging/metadata.yaml
- services/project-grafana-loki/metadata.yaml
- services/project-logging/metadata.yaml
- services/rook-ceph-cluster/metadata.yaml
- services/traefik/metadata.yaml
- services/velero/metadata.yaml
Closes [D2IQ-96389](https://d2iq.atlassian.net/browse/D2IQ-96389)
Ok back to the drawing board. So here is how this works. We have three types of dependencies. Please let me know if I am incorrect... 😅 
I made a spreadsheet to help:
https://docs.google.com/spreadsheets/d/1Z9nzVdcACXk3nZx7eEQw2Zf3tuZAXogUl-ATU4ifO9Q/edit#gid=0
And the docs:
https://beta-docs.d2iq.com/dkp/2.5/platform-application-dependencies
https://beta-docs.d2iq.com/dkp/2.5/project-platform-application-dependencies
**Hard dependencies**
You CANNOT deploy an app if these are deployed. These are under `requiredDependencies` in this repo. They are under required dependencies in docs. 
**Soft dependencies** 
You CAN deploy an app if these are deployed, but you must confirm. They are …
> feat: update dependencies to match docs

- licenses.d2iq.yaml
Backport https://github.com/mesosphere/kommander-applications/pull/1084
Kommander is a single module.
```release-note
```
**Checklist**
> fix: licenses for kommander single module (2.5)

- services/centralized-kubecost/0.33.1/release/release.yaml
- services/centralized-kubecost/metadata.yaml
- services/dkp-insights-management/0.4.1/helmrelease/helmrelease.yaml
- services/dkp-insights-management/metadata.yaml
- services/kube-prometheus-stack/44.2.1/helmrelease/kube-prometheus-stack.yaml
- services/kube-prometheus-stack/metadata.yaml
- services/kubecost/0.33.1/kubecost.yaml
- services/kubecost/metadata.yaml
There were a few apps that had traefik set as a HR dependency, when they are technically not dependent on it (they successfully deploy if traefik is not deployed).
```release-note
```
**Checklist**
> fix: Remove unnecessary traefik dependency from apps

- .bloodhound.yml
Validates manifests against 1.27.0 using bloodhound
https://d2iq.atlassian.net/browse/D2IQ-96921
```release-note
```
**Checklist**
> build: validate manifests against 1.27.0

- .github/services-pr-labeler.yaml
gatekeeper bumps require bumps in kommander repo as well (licenses file, install configs)
this pr is config change only, doesn't require tests to pass
```release-note
```
**Checklist**
> ci: Add gatekeeper to auto apply open-kommander-pr

- services/kube-prometheus-stack/44.2.1/defaults/cm.yaml
Fixes [D2IQ-96783].
This commit sets new default values for grafana installation. It also restores the commented but not followed practice of using the same request and limits to use a guaranteed class.
Based on the usage in the soak cluster where the pods were in constant crashloopback (OOMKilled).
```release-note
```
[D2IQ-96783]: https://d2iq.atlassian.net/browse/D2IQ-96783
> fix: new default resources for grafana

- .github/services-pr-labeler.yaml
auto apply `open-kommander-pr` to thanos bumps since bumps are required in kommander tests. does not require tests to pass on this pr
```release-note
```
**Checklist**
> ci: Auto apply open-kommander-pr to thanos bumps

- licenses.d2iq.yaml
use envsubst strip func to get github ref for thanos
```release-note
```
**Checklist**
> chore: use envsubst strip func

- services/logging-operator/3.17.8/defaults/cm.yaml
otherwise there is no readinessProbe for fluentd STS
add readinessProbe for fluentd statefulset
```release-note
```
> feat: readinessProbe for fluentd

- services/chartmuseum/3.9.0/defaults/cm.yaml
- services/gitea/8.2.0/defaults/cm.yaml
apply dkp critical priority class for gitea and chart museum
https://d2iq.atlassian.net/browse/D2IQ-96267
```release-note
```
**Checklist**
> feat: dkp critical for gitea&chartmuseum

- hack/flux/flux-update-kustomization.yaml
- services/kommander-flux/0.41.2/templates/apps_v1_deployment_helm-controller.yaml
- services/kommander-flux/0.41.2/templates/apps_v1_deployment_kustomize-controller.yaml
- services/kommander-flux/0.41.2/templates/apps_v1_deployment_notification-controller.yaml
- services/kommander-flux/0.41.2/templates/apps_v1_deployment_source-controller.yaml
Sets the priority class to `dkp-critical-priority` on Flux manifests
https://d2iq.atlassian.net/browse/D2IQ-96282
```release-note
```
**Checklist**
> feat: Set priority class on Flux manifests

- hack/flux/flux-update-kustomization.yaml
- services/kommander-flux/0.41.2/templates/apps_v1_deployment_helm-controller.yaml
- services/kommander-flux/0.41.2/templates/apps_v1_deployment_kustomize-controller.yaml
- services/kommander-flux/0.41.2/templates/apps_v1_deployment_notification-controller.yaml
- services/kommander-flux/0.41.2/templates/apps_v1_deployment_source-controller.yaml
This reverts commit ddb996ea5568e2250df4374b1914c3ba64d650ae.
https://github.com/mesosphere/kommander-applications/pull/1227 needed more work and will break CI as is. 
```release-note
```
**Checklist**
> revert: "feat: Set priority class on Flux manifests (#1227)"

- hack/release/pkg/constants/constants.go
- services/kommander/0.3.4/defaults/cm.yaml
Although we have a script to do this on release, this updates the default CAPIMate versions for 2.3.
https://d2iq.slack.com/archives/C01LNF6KML5/p1681920802932859
> ci: update capimate to 2.3.3

- .github/service-labeler.yaml
- services/kommander-ui/9.11.11/defaults/cm.yaml
- services/kommander-ui/9.11.11/defaults/kustomization.yaml
- services/kommander-ui/9.11.11/kommander-ui.yaml
- services/kommander-ui/9.11.11/kustomization.yaml
- services/kommander-ui/metadata.yaml
- services/kommander/0.6.0/defaults/cm.yaml
This change creates a separate service for kommander-ui.
https://d2iq.atlassian.net/browse/D2IQ-92244
```release-note
Kommander-ui is a separate service now and it is deployed thourhg appdeployment like other services.
```
**Checklist**
> feat: Introduce kommander-ui service

- .github/services-pr-labeler.yaml
- .github/workflows/kommander-branch.yaml
- hack/update-nvidia.sh
updates `hack/airgapped/missing-images.json` in kommander repo from local values here for the nvidia operator 
```release-note
```
**Checklist**
> ci: adds missing-images automation

- services/rook-ceph-cluster/1.10.8/pre-install/ceph-crd-check.yaml
- services/rook-ceph/1.10.8/defaults/cm.yaml
This PR solves potential upgrade issues that can occur when the `rook-ceph` HelmRelease is upgraded, then the `rook-ceph-cluster` HelmRelease is upgraded but the admission controller isn't ready yet. 
The admission controller was disabled by default upstream in `v1.10.9` to fix an issue with cert expiration - https://github.com/rook/rook/issues/10719
https://d2iq.atlassian.net/browse/D2IQ-97225
```release-note
```
**Checklist**
> fix: disable rook-ceph admission controller (2.4)

- services/kommander/0.6.0/kommander.yaml
add retry to kommander chart. In the case where kommander chart never got installed this will be better than no retry.
https://d2iq.atlassian.net/browse/D2IQ-97081
```release-note
```
**Checklist**
> chore: kommander chart retry

- .github/services-pr-labeler.yaml
- hack/update-nvidia.sh
Previously the missing image script was not updating the dcgm exporter image in the kommander repo, despite changes.
I ran the automation locally and updated the kommander PR with https://github.com/mesosphere/kommander/pull/3407/commits/df4476dc7a1683391b3c7fb405f763b688eb3621
```release-note
```
**Checklist**
> ci: fix update missing images script for nvidia

- services/rook-ceph-cluster/1.10.8/pre-install.yaml
- services/rook-ceph-cluster/1.10.8/pre-install/ceph-crd-check.yaml
- services/rook-ceph-cluster/1.10.8/rook-ceph-cluster.yaml
Let's explicitly wait for the webhook config to be deleted. It turns out the operator manages the webhook config and not the helm chart.
```release-note
```
**Checklist**
> fix: wait for webhook to be deleted

- services/centralized-grafana/45.21.0/defaults/cm.yaml
- services/kommander-ui/9.28.3/defaults/cm.yaml
- services/kube-prometheus-stack/45.21.0/defaults/cm.yaml
- KPS charts missed setting priority class for the grafana subchart 
- kommander-ui chart was newly pulled into new app, setting to dkp-critical-priority
https://d2iq.atlassian.net/browse/D2IQ-97255
```release-note
```
**Checklist**
> feat: Set priority class for KPS (grafana) and kommander-ui

- services/rook-ceph-cluster/1.10.11/pre-install.yaml
- services/rook-ceph-cluster/1.10.11/pre-install/ceph-crd-check.yaml
- services/rook-ceph-cluster/1.10.11/rook-ceph-cluster.yaml
"backports" https://github.com/mesosphere/kommander-applications/pull/1246 to resolve potential issues while upgrading from 2.4.0 to 2.5.1.
https://d2iq.atlassian.net/browse/D2IQ-97225
```release-note
```
**Checklist**
> fix: wait for webhook to be deleted (2.5)

- services/rook-ceph/1.11.4/defaults/cm.yaml
We decided in https://d2iq.slack.com/archives/C04SS4T0EN9/p1684189296640239 to set rook-ceph operator priority to `system-cluster-critical` to match the priority class of rook-ceph-cluster, which depends on the operator.
```release-note
```
**Checklist**
> refactor: Use system-cluster-critical priority for rook-ceph

- services/dex/2.12.1/defaults/cm.yaml
- services/kube-oidc-proxy/0.3.2/kube-oidc-proxy.yaml
- services/kube-prometheus-stack/45.21.0/defaults/cm.yaml
- services/traefik-forward-auth-mgmt/0.3.9/traefik-forward-auth-mgmt.yaml
Set priority class on some missing components (part 1, will have more PRs to deal with others as I keep auditing)
- kube-prometheus-stack: kube-state-metrics, operator
- dex-controller
- kube-oidc-proxy HR version was not bumped (bug in chart bumper?)
- traefik-forward-auth-mgmt HR version was not bumped (bug in chart bumper?)
```release-note
```
**Checklist**
> feat: Set priority class on more components

- services/cert-manager/1.11.0/defaults/cm.yaml
- services/external-dns/6.18.0/defaults/cm.yaml
Update app configs to use DKP High PriorityClass for tools apps
https://d2iq.atlassian.net/browse/D2IQ-96663
```release-note
```
**Checklist**
> feat: add high priority for cert-manager external-dns

- charts/kommander-operator/Chart.yaml
- charts/kommander-operator/templates/deployment.yaml
- charts/kommander-operator/templates/post_install_kommandercore_hook.yaml
- charts/kommander-operator/values.yaml
- common/kommander-operator/helmrelease.yaml
Set default priority class on koperator. I bumped the versions here, not sure it matters... it seems like koperator will just be upgraded immediately/automatically when the kapps repo is updated? I guess that's fine for now because there's not much happening with this bump, but something to think about later if ordering matters and we can't upgrade koperator first before everything else (e.g. kommander/kommander-appmanagement)
```release-note
```
**Checklist**
> feat: Set default priority class on koperator

- services/rook-ceph-cluster/1.11.4/defaults/cm.yaml
Noticed these ceph components missing priority class:
- `rook-ceph-crashcollector-*` deployments
- `rook-ceph-tools` deployment
After applying this config:
```
k get deployments -A -o=jsonpath='{range .items[*]}{@.metadata.name}{"\t\t"}{@.spec.template.spec.priorityClassName}{" \n"}' | grep rook
rook-ceph-crashcollector-0afc3f63c87e8fbd2d737160a815af58		system-cluster-critical
rook-ceph-crashcollector-4e28b5dfc7ab3fb1ef0ccfa75ebb4e5e		system-cluster-critical
rook-ceph-crashcollector-a99c97a5e98b0753453efc74e029fcde		system-cluster-critical
rook-ceph-crashcollector-b65a830587be13131bf9a54364f22029		system-cluster-critical
rook-ceph-crashcollector-d883e3ac3e29c07c7b06d99c6bdd4c54		system-cluster-critical
rook-ceph-mgr-a		system-cluster-critical …
```
> feat: Set priority class on remaining ceph components

- services/kube-prometheus-stack/45.21.0/defaults/cm.yaml
missed this daemonset `kube-prometheus-stack-prometheus-node-exporter`
Looks good after pushing this change to the daily
```
kube-prometheus-stack-prometheus-node-exporter		dkp-critical-priority
```
```release-note
```
**Checklist**
> feat: Set priority for KPS node exporter

- .github/workflows/kommander-branch.yaml
https://d2iq.atlassian.net/browse/D2IQ-96950?focusedCommentId=558963
https://d2iq.atlassian.net/browse/D2IQ-96950
Inspect the PRs created using the updated automation:
* https://github.com/mesosphere/kommander/pull/3447
* https://github.com/mesosphere/kommander/pull/3448
To get the PRs above to work, I cherry-picked the commit into their corresponding k-apps branches and manually updated the PR descriptions to include the automation's expected inputs.
Future updates will depend on https://github.com/mesosphere/dkp-infra-tools/pull/169 getting merged in, which will set the same formatted input in the chartbump PR description body.
(Depends on …
> feat: create-kommander-branch workflow supports multiple apps

- services/istio/1.17.2/defaults/cm.yaml
istio components were missing priority class
after applying this config change:
```
istio-ingressgateway		dkp-critical-priority
istio-operator		dkp-critical-priority
istiod		dkp-critical-priority
```
```release-note
```
**Checklist**
> feat: Set priority for istio components

- services/rook-ceph-cluster/1.11.4/pre-install.yaml
- services/rook-ceph-cluster/1.11.4/pre-install/ceph-crd-check.yaml
- services/rook-ceph-cluster/1.11.4/rook-ceph-cluster.yaml
backports https://github.com/mesosphere/kommander-applications/pull/1246 minus the waiting for the webook since it will already be disabled in 2.5
https://d2iq.atlassian.net/browse/D2IQ-97225
```release-note
```
**Checklist**
> fix: ensure pre-upgrade runs prior to upgrade

- services/centralized-kubecost/0.34.0/post-install-jobs/post-install-jobs.yaml
- services/centralized-kubecost/0.34.0/release/release.yaml
- services/grafana-loki/0.69.14/grafana-loki-pre-install-jobs/pre-install.yaml
- services/grafana-loki/0.69.14/grafana-loki-pre-install.yaml
- services/rook-ceph-cluster/1.11.4/pre-install/ceph-crd-check.yaml
- services/thanos/12.4.3/jobs/jobs.yaml
- services/velero/4.0.1/pre-install/pre-install-job.yaml
- services/velero/4.0.1/velero-pre-install.yaml
Set priority class on pre/post-install jobs backed by kustomizations. These are one-off jobs that run at installation to properly set up the application, so I think that prioritizing them would be safe. Users won't be able to configure this, but as they run then exit, I don't think we would see that use case.
```release-note
```
**Checklist**
> feat: Set priority on kustomization jobs

- services/rook-ceph-cluster/1.11.4/defaults/cm.yaml
- services/rook-ceph-cluster/1.11.4/kustomization.yaml
- services/rook-ceph-cluster/1.11.4/obc-pre-upgrade.yaml
- services/rook-ceph-cluster/1.11.4/obc-pre-upgrade/delete-obc-jobs.yaml
- services/rook-ceph-cluster/1.11.4/objectbucketclaims/helmrelease.yaml
Add pre-upgrade job to delete OBC jobs before upgrading OBC helmreleases. This ensures that we won't run into immutable errors, which we are adding priority class to the Job spec (an immutable field). TTL is also being set on these Jobs so that we don't need this pre-upgrade script in the future.
depends on https://github.com/mesosphere/charts/pull/1431
```release-note
```
**Checklist**
> feat: Add pre-upgrade job to delete OBC jobs

- licenses.d2iq.yaml
- make/test.mk
- services/centralized-kubecost/0.34.0/post-install-jobs/post-install-jobs.yaml
- services/centralized-kubecost/0.34.0/release/release.yaml
- services/grafana-loki/0.69.14/grafana-loki-pre-install-jobs/pre-install.yaml
- services/istio/1.17.2/defaults/cm.yaml
- services/kubefed/0.10.2/defaults/cm.yaml
- services/kubetunnel/0.0.21/defaults/cm.yaml
- services/rook-ceph-cluster/1.11.4/obc-pre-upgrade/delete-obc-jobs.yaml
- services/rook-ceph-cluster/1.11.4/pre-install/ceph-crd-check.yaml
- services/thanos/12.6.2/jobs/jobs.yaml
- services/traefik/23.0.1/defaults/cm.yaml
- services/velero/4.0.1/defaults/cm.yaml
- services/velero/4.0.1/pre-install/pre-install-job.yaml
Bumps kubectl images to avoid having multiple versions of the image in the bundles
```release-note
```
**Checklist**
> chore: bump kubectl image tags

- .github/workflows/kommander-branch.yaml
- hack/update-nvidia.sh
fixes the automation condition for automated nvidia chart bumps to update the missing images
```release-note
```
**Checklist**
> fix: use a more generic contains for nvidia kommander automation

- services/grafana-loki/0.69.16/grafana-loki-helmrelease/grafana-loki.yaml
- services/project-grafana-loki/0.69.16/project-grafana-loki.yaml
- services/rook-ceph-cluster/1.11.7/helmrelease/helmrelease.yaml
in 2.5.0, we enabled deploying the rook ceph tools pod by default, which is deployed by the `rook-ceph-cluster` HelmRelease.
The rook ceph tools pod mounts secrets/configmap that are created by the rook operator. If the rook operator takes a while to create secrets, the entire CephCluster will be uninstalled and retried (the CephCluster cannot be deleted when there are object bucket claims referencing it… but i don't think we want to disable retries entirely because certain situations might benefit from retrying like if the helm-controller can't create the object at all for some reason 🤔). 
Bumping the timeout value might be a good middle ground to help resolve potential install issues. Relates to https://d2iq.atlassian.net/browse/D2IQ-97063
Also, …
> fix: bump rook-ceph-cluster/loki HelmRelease timeout

- services/grafana-loki/0.69.4/grafana-loki-helmrelease/grafana-loki.yaml
- services/project-grafana-loki/0.69.4/project-grafana-loki.yaml
- services/rook-ceph-cluster/1.10.11/helmrelease/helmrelease.yaml
backports https://github.com/mesosphere/kommander-applications/pull/1261
```release-note
```
**Checklist**
> fix: bump rook-ceph-cluster/loki HelmRelease timeout (backport) (2.5)

- .github/services-pr-labeler.yaml
kubecost bumps require some changes in the Kommander repo 
i.e. https://github.com/mesosphere/kommander/pull/3525/commits/9cef08bf076d56be75ea2cdd0ee6bb9b607ac84d
```release-note
```
**Checklist**
> ci: Open Kommander PR for kubecost bumps

- services/fluent-bit/0.30.3/defaults/cm.yaml
The key for priority class is duplicated at https://github.com/mesosphere/kommander-applications/blob/04fd26194dee601b01a3bd482618daa2b393dd68/services/fluent-bit/0.30.3/defaults/cm.yaml#L13 and https://github.com/mesosphere/kommander-applications/blob/04fd26194dee601b01a3bd482618daa2b393dd68/services/fluent-bit/0.30.3/defaults/cm.yaml#L21
Found this when testing out the new config service endpoint.
```release-note
```
**Checklist**
> fix: duplicate key in fluentbit config defaults

- services/istio/1.17.2/defaults/cm.yaml
Fixes the metrics scraping issue found via the daily cluster alerts.
The istio metrics host defaults to `127.0.0.1`, which doesn't allow prometheus to scrape the istio operator metrics. 
I'm not sure if this fix should go into the [chart defaults](url) or here, open to suggestions!
https://d2iq.atlassian.net/browse/D2IQ-97182
```release-note
```
**Checklist**
> fix(istio): expose metrics to allow prometheus scraping

- services/kommander/0.6.0/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
Bumps mtls-proxy to latest chart as introduced by https://github.com/mesosphere/charts/pull/1440/files
```release-note
```
**Checklist**
> chore: bumps mtls-proxy to latest chart

- services/kommander-appmanagement/0.6.0/defaults/cm.yaml
[Kommander Non Airgapped Tests Multi Cluster](https://teamcity.mesosphere.io/viewType.html?buildTypeId=ClosedSource_Kommander2_Nightly_KommanderNonAirgappedTestsMultiCluster&branch_ClosedSource_Kommander2_Nightly=ychen%2Ffix-kuttl-multi-cluster-konvoy) is failing due to config api image not pointed to ECR
```release-note
```
**Checklist**
> feat: config api image subst var

- services/kommander-appmanagement/0.6.0/defaults/cm.yaml
Address https://d2iq.atlassian.net/browse/D2IQ-97950
We will drop this in 2.7
```release-note
```
**Checklist**
> chore: disable config-api by default

- services/cert-manager/1.12.2/release/release.yaml
Not sure why we never set the `valuesFrom` field on the cert-manager HR, but, adding it now so that the default CM is actually getting used.
Tested manually on the daily cluster with a managed cluster. After applying the fix to the gitrepo, cert-manager pods came back up with priority class set.
```
cert-manager-746b9c846d-nlnfx		system-cluster-critical
cert-manager-cainjector-579c8768d8-v4j9s		system-cluster-critical
cert-manager-webhook-69d5d5bfd8-66k77		system-cluster-critical
```
Will backport.
https://d2iq.atlassian.net/browse/D2IQ-98166
```release-note
```
**Checklist**
> fix: Set cert-manager HR valuesFrom to use default cm

- licenses.d2iq.yaml
- services/kube-prometheus-stack/46.8.0/etcd-metrics-proxy/kube-rbac-proxy.yaml
This PR changes how etcd certificates are handled in `etcd-metrics-proxy` by copying original certs and modifying the copy. The existing approach modifies the original files, which causes the CIS benchmark to fail: 
```
Failed a CIS Benchmark test 1.1.19: Ensure that the Kubernetes PKI directory and file ownership is set to root:root (Automated)
```
Also, the PR bumps the `kube-rbac-proxy` image to the latest version.
https://d2iq.atlassian.net/browse/D2IQ-97242
```release-note
```
**Checklist**
> fix: Don't change original permissions of etcd certificates

- licenses.d2iq.yaml
- services/kommander/0.6.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
Bumps cluster-observer to 1.1.2 to pull in the kubectl image bump
https://d2iq.atlassian.net/browse/D2IQ-98236
```release-note
```
**Checklist**
> feat: bump cluster-observer to 1.1.2

- licenses.d2iq.yaml
- services/kommander/0.6.0/dynamic-helmreleases/mtls-proxy/list-images-values.yaml
Bumps the ghostunnel image used in the airgapped bundle
https://d2iq.atlassian.net/browse/D2IQ-98180
```release-note
```
**Checklist**
> chore: bump ghostunnel image for airgapped bundle

- licenses.d2iq.yaml
- services/grafana-logging/6.57.4/grafana.yaml
- services/jaeger/2.46.2/defaults/cm.yaml
- services/jaeger/2.46.2/helmrelease/release.yaml
- services/karma/2.0.2/karma.yaml
- services/kiali/1.70.0/kiali.yaml
- services/kube-prometheus-stack/46.8.0/helmrelease/kube-prometheus-stack.yaml
- services/kubecost/0.35.1/kubecost.yaml
- services/traefik/23.1.0/traefik.yaml
noticed that the jaeger `allinone` image was using a pretty outdated version -- updating it to the same version that the operator is running.
ALSO: noticed most of our dashboard cm's had outdated versions, updated them here as well
```release-note
```
**Checklist**
> feat: Update jaeger allinone img to match operator version

- services/jaeger/2.46.2/pre-upgrade.yaml
- services/jaeger/2.46.2/pre-upgrade/delete-jaeger-hr.yaml
- services/jaeger/2.46.2/pre-upgrade/kustomization.yaml
For some reason, the newly added `priorityClassName` field to the jaeger spec in the default cm is not getting applied to the existing jaeger CR in the cluster on upgrade. There may be a race when the jaeger CRD is updated (which adds that new spec field) and when the config is applied? I also tried setting `force: true` on the upgrade spec on the helmrelease (to force the recreation of resources on upgrade vs updating), but I believe this only applies to the new version onwards, not to the previous version being upgraded (as the previous HR spec does not have force set to true on upgrades). I also tried a job to delete the `jaeger` CR prior to upgrading, but the new CR applied on upgrade still did not have the priority field set. Deleting the HR …
> feat: Add pre-upgrade job to delete jaeger HR

- .github/workflows/lint-pr.yaml
- .gitlint
Add gitlint rule to ignore commit titles that are too long; since PR titles are used in squash commits, we don't gain anything by limiting the commit messages. Instead, validate that PR titles are not too long.
example of failed run when I updated title to be too long: https://github.com/mesosphere/kommander-applications/actions/runs/5674273398/job/15377493428?pr=1433
```
Error: Pull Request title "ci: Validate PR title length instead of commit and this is going to be super long now you should fail" is greater than max length specified - 72
```
```release-note
```
**Checklist**
> ci: Validate PR title length instead of commit

- services/kubecost/0.33.1/defaults/cm.yaml
PSPs were removed in k8s 1.25 (dkp 2.5) but it is still enabled by default here so we need to explicitly disable it to avoid upgrade failures from 2.4. We only need to do this for 2.5 because the version in 2.6 changed the default to false.
https://d2iq.atlassian.net/browse/D2IQ-98509
```release-note
```
**Checklist**
> fix: Disable kubecost-grafana PSP by default

- services/gatekeeper/3.12.0/defaults/cm.yaml
- services/logging-operator/4.2.3/defaults/cm.yaml
* fix: disable PSPs
* fix(gatekeeper): Disable psps by default
PSP was removed in k8s 1.25, we should explicitly disable PSPs in our default values.
---------
backports https://github.com/mesosphere/kommander-applications/pull/1437
https://d2iq.atlassian.net/browse/D2IQ-98509
```release-note
```
**Checklist**
> fix: disable PSPs explictly to avoid upgrade failures (2.6)

- hack/release/pkg/chartversion/chartversion.go
- hack/release/pkg/chartversion/chartversion_test.go
- hack/release/pkg/constants/constants.go
- services/gatekeeper/3.12.0/pre-upgrade.yaml
- services/gatekeeper/3.12.0/pre-upgrade/kustomization.yaml
- services/gatekeeper/3.12.0/pre-upgrade/pre-upgrade.yaml
- services/gatekeeper/3.12.0/release.yaml
- services/kubecost/0.35.1/pre-upgrade.yaml
- services/kubecost/0.35.1/pre-upgrade/kustomization.yaml
- services/kubecost/0.35.1/pre-upgrade/pre-upgrade.yaml
- services/logging-operator/4.2.3/pre-upgrade.yaml
- services/logging-operator/4.2.3/pre-upgrade/kustomization.yaml
- services/logging-operator/4.2.3/pre-upgrade/pre-upgrade.yaml
Add pre-upgrade jobs to kubecost, logging-operator, and gatekeeper to run helm-mapkubeapis tool that takes care of editing the helmrelease secret to remove the podsecuritypolicy manifest which is unsupported starting in k8s 1.25.
This affects clusters that were upgraded from 2.4, in which the PSP api was still supported and these 3 charts had deployed PSPs. Since kommander applications are upgraded prior to k8s, we saw this:
- upgrade to kommander 2.5 --> these apps upgraded successfully, with PSP resources still deployed
- upgrade to k8s 1.25 --> PSP api was removed, so all existing PSPs are deleted
- upgrade to kommander 2.6 --> upgrade errors in these 3 apps, explanation here: https://helm.sh/docs/topics/kubernetes_apis/#helm-users
> Helm fails in …
> feat: Add pre-upgrade jobs to run helm-mapkubeapis

- make/test.mk
Made the change to use the same k8s version for upgrade tests since the previous version is compatible on 1.26
Held off on updating to 1.27 because it looks like there were issues with getting that build working in CI
depends on https://github.com/mesosphere/kommander-applications/pull/1455
```release-note
```
**Checklist**
> ci: Use prev k8s version for upgrade e2e test

- services/logging-operator/4.2.3/defaults/cm.yaml
- services/logging-operator/4.2.3/pre-upgrade/pre-upgrade.yaml
In the logging-operator `4.2.0`, the fluent-bit daemonset `spec.selector` field was [updated](https://github.com/kube-logging/logging-operator/blob/5a8e76e6e81c7440e70bf37bd8b1d6ff5d11a376/pkg/resources/fluentbit/fluentbit.go#L60) which is an immutable field. 
On upgrade to 2.6, the fluent-bit daemonset is never upgraded because the logging-operator cannot update the DS with the new selectors. The only way to continue is to delete the DS. Unfortunately, since our logging-operator HR is not behind a Kustomization, we don't have a good way of running a job after the operator finishes upgrading so we can't just simply run a `kubectl delete` on the DS. 
By setting `enableRecreateWorkloadOnImmutableFieldChange`, we allow the operator to recreate resources …
> fix: Handle upgrade to logging-operator v4.2.0

- common/helm-repositories/mesosphere-repos.yaml
Use `https` for the helmMirrorURL of the optional Insights Engine component.
```release-note
```
**Checklist**
> fix: Use https for Insights Engine Helm Mirror URL

- services/traefik-forward-auth-mgmt/0.3.9/defaults/cm.yaml
- services/traefik-forward-auth/0.3.9/defaults/cm.yaml
TFA-full ingresses are skipping the k8s API authorization thus a user can just access the URL(just seeing the empty page) without any RBAC permission
see TFA Code about this config option:
https://github.com/mesosphere/traefik-forward-auth/blob/master/internal/handlers/server.go#L497-L504
https://d2iq.atlassian.net/browse/D2IQ-97861#
```release-note
```
**Checklist**
> fix: not skipping authz for kube dashboard

- services/kube-prometheus-stack/48.3.1/defaults/cm.yaml
It looks like the KPS chart already defines a servicemonitor which scrapes the apiserver metrics. Our additional scrapeconfig definition is resulting in scraping the same apiserver targets and generating duplicate metrics. We can remove our scrape config and rely on the chart created servicemonitor.
Also, we no longer deploy keepalived in dkp 2.x so removing that unused scrape target.
https://d2iq.atlassian.net/browse/D2IQ-98647
```release-note
```
**Checklist**
> fix(kps): Remove duplicate apiserver and unused keepalived scrapeconfig

- .github/workflows/automerge.yaml
looks like automerge action has been reenabled - it should not automerge if the `let-me-merge-it` label is applied
```release-note
```
**Checklist**
> ci(gha): Avoid automerge if let-me-merge-it label is appliesd

- licenses.d2iq.yaml
- services/grafana-logging/6.58.6/defaults/cm.yaml
- services/grafana-logging/6.58.6/grafana.yaml
- services/kube-prometheus-stack/48.3.1/defaults/cm.yaml
- services/kube-prometheus-stack/48.3.1/helmrelease/kube-prometheus-stack.yaml
- services/kube-prometheus-stack/metadata.yaml
- services/project-grafana-logging/6.58.6/defaults/cm.yaml
We were overriding the grafana image to avoid this upstream bug https://github.com/grafana/grafana/issues/56087 but it has been fixed so ~using the latest / default image now~ -- latest image v10 appears to be breaking prometheus scraping of grafana metrics, pinning to latest 9.5 version for now.
```release-note
```
**Checklist**
> feat(grafana): Use grafana 9.5.7

- services/centralized-grafana/48.3.1/defaults/cm.yaml
- services/grafana-logging/6.58.6/defaults/cm.yaml
- services/kube-prometheus-stack/48.3.1/defaults/cm.yaml
- services/kubecost/0.35.1/defaults/cm.yaml
- services/project-grafana-logging/6.58.6/defaults/cm.yaml
Prevents Grafana from phoning home with telemetry data.
https://d2iq.atlassian.net/browse/D2IQ-99007
```release-note
```
**Checklist**
> fix: disables telemetry transmission for Grafana

- charts/kommander-operator/crds/crd_kommandercores.yaml
Update `kommandercore` crd (generated in https://github.com/mesosphere/kommander/pull/3807) to add new spec and status fields.
(I am manually copying over the CRD from `kommander` because I didn't find any automation to sync them; let me know if I am missing something)
https://d2iq.atlassian.net/browse/D2IQ-97893
```release-note
```
**Checklist**
> feat(koperator): Update CRD

- .github/service-labeler.yaml
- services/ai-navigator-app/0.1.0/defaults/cm.yaml
- services/ai-navigator-app/0.1.0/defaults/kustomization.yaml
- services/ai-navigator-app/0.1.0/kustomization.yaml
- services/ai-navigator-app/metadata.yaml
A skeleton for ai-navigator-app. The work is continued in https://github.com/mesosphere/kommander-applications/pull/1514.
- https://d2iq.atlassian.net/browse/D2IQ-98636
```release-note
```
**Checklist**
> feat: Introduce empty kustomization of ai-navigation-app

- make/pre-commit.mk
```release-note
```
**Checklist**
> fix: fixes linter to stay in the release-branch 2.6

- make/pre-commit.mk
```release-note
```
**Checklist**
> fix: fixes linter to stay on release branch 2.5

- make/pre-commit.mk
```release-note
```
**Checklist**
> fix: fixes linter to stay on release branch 2.4

- charts/kommander-operator/Chart.yaml
- charts/kommander-operator/templates/deployment.yaml
- charts/kommander-operator/templates/post_install_kommandercore_hook.yaml
- charts/kommander-operator/values.yaml
- common/kommander-operator/helmrelease.yaml
- updates operator helm chart version to be in line with dkp version
- pass chart version into deployment args
- set kommandercore spec version to chart version in post-install
https://d2iq.atlassian.net/browse/D2IQ-97955
```release-note
```
**Checklist**
> feat(koperator): Update chart version, pass version into deployment

- .github/workflows/release.yml
It looks like gha were never created for release branches.
```release-note
```
**Checklist**
> build: Add a workflow to build artifacts for 2.6 branch

- .github/workflows/release.yml
It looks like gha was never created for 2.4 branch.
```release-note
```
**Checklist**
> build: Add a workflow to build artifacts for 2.4 branch

- mergebot-config.json
Disables E2E tests on release-2.6 which are non functional on all of our release branches atm.
https://d2iq.atlassian.net/browse/D2IQ-99147
```release-note
```
**Checklist**
> fix: disables E2E tests on release-2.6

- mergebot-config.json
Disables E2E tests on release-2.5 which are non functional on all of our release branches atm.
https://d2iq.atlassian.net/browse/D2IQ-99147
```release-note
```
**Checklist**
> fix: disables E2E tests on release-2.5

- mergebot-config.json
Disables E2E tests on release-2.4 which are non functional on all of our release branches atm.
https://d2iq.atlassian.net/browse/D2IQ-99147
```release-note
```
**Checklist**
> fix: disables E2E tests on release-2.4

- .bloodhound.yml
Validates manifests against 1.28.0 using bloodhound
https://d2iq.atlassian.net/browse/D2IQ-97973
```release-note
```
**Checklist**
> build: validate manifests against 1.28.0

- services/ai-navigator-app/0.1.0/ai-navigator-app.yaml
- services/ai-navigator-app/0.1.0/defaults/cm.yaml
- services/ai-navigator-app/0.1.0/defaults/kustomization.yaml
I've ran 25 bot users which are constantly asking questions against the
service on the daily and it was inside the limits with a good margin.
It never went above 0.008 CPU usage and memory wasn't really much
affected, it stayed <30MB observed in our Grafana Dashboard.
https://d2iq.atlassian.net/browse/D2IQ-99125
```release-note
```
**Checklist**
> feat(ai-navigator): set proper resource limits and requests

- .github/workflows/test.yaml
- .go-tools
- make/go.mk
It looks like coveralls didn't work flow a while, let's update the setup
```release-note
```
**Checklist**
> chore: Update coveralls setup

- charts/kommander-operator/Chart.yaml
- charts/kommander-operator/templates/deployment.yaml
- charts/kommander-operator/templates/post_install_kommandercore_hook.yaml
- charts/kommander-operator/templates/rback_v1_clusterrole_operator_kommander-operator.yaml
- charts/kommander-operator/values.yaml
- common/kommander-operator/helmrelease.yaml
After additional discussions, it looks like we can simplify things by avoiding the syncing of koperator chart version with dkp/kommander version (involves pre/postrelease jobs, and postrelease jobs right now are risky since those bumps are not reviewed prior to releasing). Instead, we can follow the "kcli way" of getting its version which is set at build time via goreleaser ldflags https://github.com/mesosphere/kommander-cli/blob/97eb1585529a8b3183eb306d1bcdf85186a6ad86/.goreleaser.yml#L22-L27. This is how the kcli will be triggering ugprade, by using this version to update `kommandercore` (and `workspace`) with, so we should do the same in the kommander operator (and other controllers). Instead of using the chart version and passing the version down …
> feat(koperator): Revert to using arbitrary chart version

- .github/workflows/release.yml
Allows running the release workflow manually and from other workflows 
```release-note
```
**Checklist**
> ci: add workflow_dispatch on release workflow (2.6)

- .github/workflows/release.yml
Allows running the release workflow manually and from other workflows
```release-note
```
**Checklist**
> ci: add workflow_dispatch on release workflow (2.5)

- .github/workflows/release.yml
Allows running the release workflow manually and from other workflows
```release-note
```
**Checklist**
> ci: add workflow_dispatch on release workflow (2.4)

- .github/workflows/validate-licenses.yaml
update-licenses reorders keys and removes comments; needed to update infra-tools version used in kapps
https://d2iq.atlassian.net/browse/D2IQ-98627
```release-note
```
**Checklist**
> fix: update-licenses reorders keys and removes comments

- charts/kommander-operator/templates/post_install_kommandercore_hook.yaml
- charts/kommander-operator/templates/pre_upgrade_kommandercore_hook.yaml
pre 2.7 kommander core status.version is empty. This prevent 2.7 koperator from triggering the declarative upgrade logic.
https://d2iq.atlassian.net/browse/D2IQ-98960
```release-note
```
**Checklist**
> feat: patch kcore status to kommander ver pre upgrade

- .github/workflows/release.yml
Reverts mesosphere/kommander-applications#1633
AWS role is not working and needs further looking in to.
> revert: "ci: change aws role"

- services/ai-navigator-app/0.1.0/defaults/kustomization.yaml
Enabling ai-navigator was causing kustomization errors due to missing `defaults/` dir and manifests.
```
kommander                     ai-navigator-app-0.1.0-defaults             46m   False     kustomization path not found: stat /tmp/kustomization-2697881657/services/ai-navigator-app/0.1.0/defaults: no such file or directory
```
https://d2iq.atlassian.net/browse/D2IQ-99374
Tested this fix on the daily and saw the kustomization resolve successfully
```
k get kustomizations -n kommander -w | grep navigator
ai-navigator-app                            93m   True      Applied revision: main@sha1:06df51eb92b7d8c8f6973385dd5c64f09efd893d
ai-navigator-app-0.1.0-defaults …
```
> fix(ai-navigator): Add missing defaults directory and manifests

- charts/kommander-operator/templates/post_install_kommandercore_hook.yaml
- charts/kommander-operator/templates/pre_upgrade_kommandercore_hook.yaml
depends on https://github.com/mesosphere/kommander-applications/pull/1608
the kommandercore related jobs have been using cluster-admin clusterrole. although it's short lived, it's better to just drop that usage.
```release-note
```
**Checklist**
> fix: used dedicated clusterrole for kcore hooks

- make/release.mk
Let's skip ai-navigator-app from the bundle.
https://d2iq.atlassian.net/browse/D2IQ-99372
```release-note
```
**Checklist**
> fix: Exclude ai-navigator-app from the bundle

- make/release.mk
Let's exclude ai-navigator-app also in main branch (following https://github.com/mesosphere/kommander-applications/pull/1655).
```release-note
```
**Checklist**
> fix: Exclude ai-navigator-app from the bundle (#1655)

- apptests/environment/environment.go
- apptests/environment/environment_test.go
- apptests/go.mod
- apptests/go.sum
- apptests/kind/kind.go
- apptests/kind/kind_test.go
- apptests/kustomize/kustomize.go
This PR provide functionality to setup environment for applications specific testing by putting together all defined packages so far. 
Provisioning an environment is creating a kind cluster, installs flux components on the cluster and apply base repositories to the cluster. 
https://d2iq.atlassian.net/browse/D2IQ-98659
```release-note
```
**Checklist**
> feat: environment provisioning

- services/gitea/9.3.0/defaults/cm.yaml
Upstream uses `Always` https://gitea.com/gitea/helm-chart/src/commit/370775537323ba95fe93fe3d849ad46e860b8575/values.yaml  which does not seem efficient and is not consistent with what most other services use so this change overrides it to be more consistent.
More context https://d2iq.slack.com/archives/C01LNF6KML5/p1697577633844619?thread_ts=1697576272.378049&cid=C01LNF6KML5
```release-note
```
**Checklist**
> chore: `IfNotPresent` pull policy for gitea

- .bloodhound.yml
just updating the k8s versions used by bloodhound for validation
https://d2iq.atlassian.net/browse/D2IQ-98552
```release-note
```
**Checklist**
> ci(bloodhound): Update k8s version for validation

- services/gitea/9.3.0/defaults/cm.yaml
Fixing a typo
```release-note
```
**Checklist**
> fix: Typo in namespace name

- licenses.d2iq.yaml
- services/kommander/0.7.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
Bumps to v1.2.0 of cluster-observer
d2iq.atlassian.net/browse/D2IQ-99463
```release-note
```
**Checklist**
> build: bump cluster observer to v1.2.0

- services/prometheus-adapter/4.4.1/defaults/cm.yaml
Doubling resources for prometheus adapter as discussed here:
https://d2iq.slack.com/archives/CJZQDQMSR/p1696956332307929?thread_ts=1696954502.650439&cid=CJZQDQMSR
https://d2iq.atlassian.net/browse/D2IQ-99404
```release-note
```
**Checklist**
> fix: Double memory resources for prometheus-adapter

- services/gitea/9.3.0/defaults/cm.yaml
It seems we can shorted the time gitea becomes ready by tuning livenessProbe's initial delay.
https://d2iq.slack.com/archives/C03P4F14M7E/p1697803003706169?thread_ts=1697798961.547819&cid=C03P4F14M7E
```release-note
```
**Checklist**
> chore: Adjust livenessprobe in gitea

- services/dex-k8s-authenticator/1.2.16/defaults/cm.yaml
We have low values for probe timeouts. We can increase these default values to avoid issues with larger setups.
https://d2iq.atlassian.net/browse/D2IQ-99405
```release-note
```
**Checklist**
> fix: Set default timeouts for the high load

- services/kube-prometheus-stack/48.3.1/helmrelease.yaml
This PR uses the `kube-prometheus` **deployment** as a reference point to check the `health` status of the rollout. The kustomization for kube-prometheus will only be ready when the deployment is healthy
https://d2iq.atlassian.net/browse/D2IQ-94596
```release-note
```
**Checklist**
> feat: verify the health of the kube-prometheus-stack deployment

- services/gitea/9.3.0/defaults/cm.yaml
It looks like (at least in one case), gitea tried to connect to postgres pod and connection was refused. It cased a restart of gitea pod and timed out gitea installation.
https://d2iq.atlassian.net/browse/D2IQ-99546
```release-note
```
**Checklist**
> fix: Enable startup probe for gitea's postgres

- licenses.d2iq.yaml
- services/ai-navigator-app/0.2.0/defaults/cm.yaml
By default, Weaviate vector db requests a PVC with 32Gi of storage size, which is probably too high given the amount of data collected. Also, this might cause the kommander e2e tests to fail on was pre-provisioned.
```release-note
```
**Checklist**
> fix: Reduce Weaviate storage size

- make/release.mk
The ai-navigator-cluster-info-agent would be in the airgapped bundle, and it shouldn't be
No JIRA - I just thought of it now, but I basically just tried to lift Mikołaj's change here and add the agent to this exclude:
https://github.com/mesosphere/kommander-applications/pull/1655
To be honest - I am mostly just hopeful that this will work the way I want it to.
No change, this will just exclude it from the airgapped bundle (new feature, so no change to users)
**Checklist**
> fix: xxclude ai-nav info agent from the bundle

- licenses.d2iq.yaml
- services/dkp-insights-management/1.0.0/defaults/cm.yaml
- services/dkp-insights-management/1.0.0/helmrelease/helmrelease.yaml
- services/dkp-insights/1.0.0/defaults/cm.yaml
- services/dkp-insights/1.0.0/helmrelease/helmrelease.yaml
* feat: Release DKP-Insights Backend v1.0.0-dev.8
Release DKP-Insights Backend v1.0.0-dev.8
---------
backports https://github.com/mesosphere/kommander-applications/pull/1738 to `release-2.7`
```release-note
```
**Checklist**
> feat: Release DKP-Insights v1.0.0-dev.8 (2.7)

- licenses.d2iq.yaml
- services/grafana-logging/6.60.1/defaults/cm.yaml
- services/grafana-logging/6.60.1/grafana.yaml
- services/project-grafana-logging/6.60.1/defaults/cm.yaml
Pin grafana-logging to 8.5.26 which is the latest functioning version of grafana that loads the kubernetes audit dashboard successfully. Using 9+ causes the dashboard to crash upon loading, and after fixing the mem to avoid the crash, only the audit logs panel shows data. In interest of time and release timeline, let's just use grafana 8.5 and continue to investigate why newer grafana versions are causing these issues.
https://d2iq.atlassian.net/browse/D2IQ-99725
```release-note
```
**Checklist**
> fix: Pin grafana-logging to 8.5

- licenses.d2iq.yaml
- services/gitea/8.2.0/defaults/cm.yaml
https://avd.aquasec.com/nvd/2022/cve-2022-2068/
```release-note
```
**Checklist**
> fix: Address critical postrgres CVE

- licenses.d2iq.yaml
- services/kommander/0.8.0/dynamic-helmreleases/mtls-proxy/list-images-values.yaml
```
trivy image mesosphere/ghostunnel:v1.7.1-server-backend-proxy.1 --severity CRITICAL
2023-12-19T11:31:05.768+0100    INFO    Vulnerability scanning is enabled
2023-12-19T11:31:05.768+0100    INFO    Secret scanning is enabled
2023-12-19T11:31:05.768+0100    INFO    If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-12-19T11:31:05.768+0100    INFO    Please see also https://aquasecurity.github.io/trivy/v0.48/docs/scanner/secret/#recommendation for faster secret detection
2023-12-19T11:31:07.006+0100    INFO    Detected OS: alpine
2023-12-19T11:31:07.006+0100    INFO    Detecting Alpine vulnerabilities...
2023-12-19T11:31:07.010+0100    INFO    Number of language-specific files: 1
2023-12-19T11:31:07.010+0100 …
```
> fix: bump ghostunnel image to address critical CVEs

- licenses.d2iq.yaml
- services/kommander/0.7.0/dynamic-helmreleases/mtls-proxy/list-images-values.yaml
Backport of https://github.com/mesosphere/kommander-applications/pull/1772
```release-note
```
**Checklist**
> fix: bump ghostunnel image to address critical CVEs (2.7)

- licenses.d2iq.yaml
- services/dex/2.13.6/defaults/cm.yaml
Bumping dex images to mitigate existing CVEs in d2iq v2.37.0-d2iq.1 image.
```release-note
```
**Checklist**
> feat: bump dex image

- licenses.d2iq.yaml
- services/gitea/8.2.0/defaults/cm.yaml
Reverting postgres docker container version bump.
A backport of https://github.com/mesosphere/kommander-applications/pull/1779
```release-note
```
**Checklist**
> fix: taking psql bump from major to minor version (#1779)

- services/kubecost/0.37.1/defaults/cm.yaml
[Kubecost](https://github.com/mesosphere/charts/blob/6135b0df4858e916d6bd5705ca63a43c885153bf/stable/kubecost/values.yaml#L11) is using the `pkg:docker/bitnami/kubectl@1.24.1` image which has many CVEs, this PR exposes it in defaults so that we can easily track and bump it to versions which don't have this CVE.
```release-note
```
**Checklist**
> fix(CVE): bump pkg:docker/bitnami/kubectl@1.24.1

- licenses.d2iq.yaml
- services/centralized-grafana/48.3.1/defaults/cm.yaml
- services/centralized-kubecost/0.37.1/defaults/cm.yaml
- services/grafana-logging/6.60.1/defaults/cm.yaml
- services/kube-prometheus-stack/48.3.1/defaults/cm.yaml
- services/kubecost/0.37.1/defaults/cm.yaml
Let's bump the kiwigrid/sidecar image to the latest one to avoid critical CVEs in auxiliary libraries.
```release-note
```
**Checklist**
> fix: bump kubecost sidecar image

- services/dkp-insights/1.0.1/helmrelease/list-images-values.yaml
This prevents the `bitnami-shell` image with hard to remove critical CVEs from being pulled into the airgapped bundle by the `dkp-insights` app.
The side effect of this change is that without this image `postgres.tls` and `postgres.volumePermissions` become unusable in air-gapped environments. Note that we neither use these flags by default, nor can they add any significant amount of security in the Insights use case.
A backport of this PR into 2.7 will hopefully close https://github.com/mesosphere/kommander/issues/4129
**Checklist**
> fix: drop airgapped support for Insights flags that use `bitnami-shell` 

- licenses.d2iq.yaml
- services/centralized-grafana/48.3.1/centralized-grafana.yaml
- services/centralized-grafana/48.3.1/defaults/cm.yaml
- services/grafana-logging/6.60.1/defaults/cm.yaml
- services/grafana-logging/6.60.1/grafana.yaml
- services/kube-prometheus-stack/48.3.1/defaults/cm.yaml
- services/kube-prometheus-stack/48.3.1/helmrelease/kube-prometheus-stack.yaml
- services/kube-prometheus-stack/metadata.yaml
- services/project-grafana-logging/6.60.1/defaults/cm.yaml
Bumps Grafana image to avoid critical CVEs present in 9.5.7
Closes https://github.com/mesosphere/kommander/issues/4145
No
**Checklist**
> fix: bump grafana to 9.5.13

- licenses.d2iq.yaml
- services/grafana-loki/0.74.6/defaults/cm.yaml
- services/project-grafana-loki/0.74.6/defaults/cm.yaml
Bumps the `nginx-unprivileged` image in grafana-loki and project-grafana-loki to avoid critical CVEs present in `1.22.0-alpine`
https://github.com/mesosphere/kommander/issues/4144
No
```release-note
```
**Checklist**
> fix: bump nginx-unprivileged in *grafana-loki to 1.24.0-alpine

- licenses.d2iq.yaml
- services/logging-operator/4.2.3/defaults/cm.yaml
This updates the fluentd image to get rid of recent CVEs. 
Closes https://github.com/mesosphere/kommander/issues/4134
Tested by verifying presence of logs in Grafana Logging.
From a Fluentd changelog, a potential for some subtle breakage in some narrow case looks quite low: https://github.com/fluent/fluentd/blob/master/CHANGELOG.md
Apparently kube-logging is no longer solely driven by Cisco (who acquired Banzaicloud in 2019) and is being onboarded into CNCF Sandbox right now. See:
- Issue 42 in https://github.com/cncf/sandbox/issues
- https://axoflow.com/logging-operator-the-telemetry-pipeline-for-kubernetes/
No
**Checklist** …
> fix: bump fluentd image to kube-logging/fluentd:v1.16-full-build.122

- licenses.d2iq.yaml
- services/karma/2.0.3/defaults/cm.yaml
Rebuild an image to keep it compatible with the existing configuration: https://nutanix.slack.com/archives/C066Z6Q0C2H/p1704282760071239?thread_ts=1704231984.117689&cid=C066Z6Q0C2H
- https://d2iq.atlassian.net/browse/D2IQ-99764
```release-note
```
**Checklist**
> fix: Rebuild karma image to bring back TLS server name support

- licenses.d2iq.yaml
- services/karma/2.0.3/defaults/cm.yaml
Backport of https://github.com/mesosphere/kommander-applications/pull/1809
```release-note
```
**Checklist**
> fix: Rebuild karma image to bring back TLS server name support (#1809)

- licenses.d2iq.yaml
- services/gitea/8.2.0/defaults/cm.yaml
Bump memcached to address a number of CVEs.
```release-note
```
**Checklist**
> chore: Bump memcached to a default for gitea chart

- licenses.d2iq.yaml
- services/centralized-kubecost/0.37.2/post-install-jobs/post-install-jobs.yaml
- services/centralized-kubecost/0.37.2/release/release.yaml
- services/grafana-loki/0.74.6/grafana-loki-pre-install-jobs/pre-install.yaml
- services/istio/1.17.2/defaults/cm.yaml
- services/kube-prometheus-stack/48.3.1/defaults/cm.yaml
- services/kubecost/0.37.2/defaults/cm.yaml
- services/kubefed/0.10.4/defaults/cm.yaml
- services/kubetunnel/0.0.31/defaults/cm.yaml
- services/rook-ceph-cluster/1.12.6/pre-install/ceph-crd-check.yaml
- services/thanos/12.13.13/jobs/jobs.yaml
- services/traefik/24.0.0/defaults/cm.yaml
- services/velero/4.1.1/defaults/cm.yaml
- services/velero/4.1.1/pre-install/pre-install-job.yaml
```release-note
```
**Checklist**
> fix: bump kubectl image to v1.27.9

- licenses.d2iq.yaml
- services/gitea/8.2.0/defaults/cm.yaml
Update gitea image to use D2iQ's [fork](https://github.com/mesosphere/gitea/actions/runs/7415434306/job/20178555988).
The fork is used because the upstream `gitea:1.19.2-rootless` image has a CVE and [upstream rejected](https://github.com/go-gitea/gitea/pull/28641) a patch to fix it for this release branch.
We're matching the exact tag with just the base alpine image updated to reduce any breakages.
```release-note
```
**Checklist**
> fix: Update gitea image to D2iQ fork to address CVEs.

- .bloodhound.yml
- Bump to latest 1.28.5 k8s version
- Add 1.29.0 to bloodhound to start validating the next version
https://d2iq.atlassian.net/browse/D2IQ-99770
```release-note
```
**Checklist**
> ci(bloodhound): Bump to latest 1.28 k8s version, add 1.29.0

- services/cert-manager/bootstrap/kustomization.yaml
- services/gatekeeper/3.13.0/release/release.yaml
- services/gatekeeper/bootstrap/kustomization.yaml
Use patches instead if patchesJson6902. Done using `kustomize edit fix`.
https://d2iq.atlassian.net/browse/D2IQ-98758
```release-note
```
**Checklist**
> chore: Use patches instead of patchesJson6902

- .github/workflows/validate-licenses.yaml
Updates `dkp-licenses-cli` to a version that accepts new parameter for validation command, that allows to skip validating licenses file presence for given GH organization.
```release-note
```
**Checklist**
> chore: remove use of MESOSPHERECI_USER_TOKEN

- .github/workflows/validate-licenses.yaml
Backport of https://github.com/mesosphere/kommander-applications/pull/1881
```release-note
```
**Checklist**
> chore: remove use of MESOSPHERECI_USER_TOKEN (2.7)

- .github/workflows/validate-licenses.yaml
Backport of https://github.com/mesosphere/kommander-applications/pull/1881
```release-note
```
**Checklist**
> chore: remove use of MESOSPHERECI_USER_TOKEN (2.6)

- .github/workflows/validate-licenses.yaml
Use new format for basic auth that is compatible with oauth generated tokens.
```release-note
```
**Checklist**
> fix: update-licenses basic auth oauth2 token

- services/kommander/0.8.0/defaults/cm.yaml
This ensures that the apps are handled during expansion to be removed.
ai navigator apps were sticking around post-expansion. in order to ensure that they are removed instead, we must add them to the list of management apps.
https://d2iq.atlassian.net/browse/D2IQ-99868
```release-note
```
**Checklist**
> fix(kommander): Add ai-nav apps to list of mgmt apps

- services/kube-prometheus-stack/48.3.1/defaults/cm.yaml
Let's silence kommandercluster resource quota.
https://d2iq.atlassian.net/browse/D2IQ-99870
Shall we backport it?
```release-note
```
**Checklist**
> fix: Silence kommandercluster quota alert

- .github/workflows/validate-licenses.yaml
Backport of https://github.com/mesosphere/kommander-applications/pull/1881
```release-note
```
**Checklist**
> chore: remove use of MESOSPHERECI_USER_TOKEN (2.5)

- .github/workflows/validate-licenses.yaml
Backport of https://github.com/mesosphere/kommander-applications/pull/1887
Use new format for basic auth that is compatible with oauth generated tokens.
```release-note
```
**Checklist**
> fix: update-licenses basic auth oauth2 token (2.6)

- .github/workflows/validate-licenses.yaml
Backport of https://github.com/mesosphere/kommander-applications/pull/1887
Use new format for basic auth that is compatible with oauth generated tokens.
```release-note
```
**Checklist**
> fix: update-licenses basic auth oauth2 token (2.7)

- services/ai-navigator-app/0.2.0/defaults/cm.yaml
- services/ai-navigator-app/0.2.0/helmrelease.yaml
- services/ai-navigator-app/0.2.0/helmrelease/helmrelease.yaml
The HR had a different name from the AP name. There is a requirement in Kommander that this name match for charts that will get the override. This fixes the inability to add config overrides in the UI, etc. 
https://d2iq.atlassian.net/browse/D2IQ-99867
- Tested in a local cluster against kapps branch.
- Check for correct mapping of config maps 
```release-note
```
**Checklist**
> feat: Update name of HR

- common/airgapped/patch-add-secret-ref.yaml
Keeping up with Flux deprecations. Flux HelmRepository.spec.secretRef.name has been deprecated. Using spec.certSecretRef.name instead.
https://d2iq.atlassian.net/browse/D2IQ-99228
Tested with e2e tests against kommander-cli repo. [Created branch and mapped applications repositories](https://github.com/mesosphere/kommander-cli/pull/1295/files) to test against this branch. 
Ran an upgrade manually on airgapped and non-airgapped clusters. Upgraded from v2.7.0 to head (v2.8.0-dev) with the applications repo.
```release-note
Flux HelmRepository.spec.secretRef.name has been deprecated. Use spec.certSecretRef.name instead. See: …
```
> feat: Rename deprecated secretRef to certSecretRef

- licenses.d2iq.yaml
- services/centralized-grafana/48.3.1/centralized-grafana.yaml
- services/centralized-grafana/48.3.1/defaults/cm.yaml
- services/kube-prometheus-stack/48.3.1/defaults/cm.yaml
- services/kube-prometheus-stack/48.3.1/helmrelease/kube-prometheus-stack.yaml
- services/kube-prometheus-stack/metadata.yaml
This PR fixes the metrics scraping issue with Grafana v10+. Also, it bumps Grafana in KPS to the latest version (v10.3.3)
https://d2iq.atlassian.net/browse/D2IQ-99819
```release-note
```
**Checklist**
> fix: unpin KPS Grafana, update metrics path

- licenses.d2iq.yaml
- services/centralized-kubecost/0.37.2/post-install-jobs/post-install-jobs.yaml
- services/centralized-kubecost/0.37.2/release/release.yaml
- services/dex/2.13.8/defaults/cm.yaml
- services/grafana-loki/0.74.6/grafana-loki-pre-install-jobs/pre-install.yaml
- services/istio/1.20.2/defaults/cm.yaml
- services/knative/1.10.4/defaults/cm.yaml
- services/kube-prometheus-stack/48.3.1/defaults/cm.yaml
- services/kubecost/0.37.2/defaults/cm.yaml
- services/kubefed/0.10.4/defaults/cm.yaml
- services/kubetunnel/0.0.31/defaults/cm.yaml
- services/rook-ceph-cluster/1.13.2/pre-install/ceph-crd-check.yaml
- services/thanos/12.20.3/jobs/jobs.yaml
- services/traefik/26.0.0/defaults/cm.yaml
- services/velero/5.2.2/defaults/cm.yaml
- services/velero/5.2.2/velero-pre-install.yaml
Bump kubectl image in values overrides to 1.29.2.
https://d2iq.atlassian.net/browse/D2IQ-99985
kubetools templating variables were added back recently, but I wanted to note that this variable is not actually getting substituted, so effectively we are still using the defaults and thus must still manually bump them here. we should revisit switching to using kubetools and getting it substituted when we get to implementing declarative installs (relevant jira ticket https://d2iq.atlassian.net/browse/D2IQ-87946)
```release-note
```
**Checklist**
> fix(kubectl): Bump all kubectl image defaults to 1.29.2

- services/centralized-grafana/48.3.1/defaults/cm.yaml
Noticed the centralized-grafana metrics target was still down, realized this grafana's path is different so fixed it and checked that the target is back up
```release-note
```
**Checklist**
> fix(centralized-grafana): Correct metrics path

- common/airgapped/patch-add-secret-ref.yaml
Reverts mesosphere/kommander-applications#1925
`secretRef` to `certSecretRef` is a bigger change than we initially anticipated. when we reintroduce this feature, we should:
- have a patch to remove the `secretRef` from HelmRepository resources.
- update the `caFile` to `ca.crt` in the secret data.
> revert: "feat: Rename deprecated secretRef to certSecretRef (#1925)"

- licenses.d2iq.yaml
- services/centralized-grafana/48.3.1/centralized-grafana.yaml
- services/centralized-grafana/48.3.1/defaults/cm.yaml
- services/kube-prometheus-stack/48.3.1/defaults/cm.yaml
- services/kube-prometheus-stack/48.3.1/helmrelease/kube-prometheus-stack.yaml
- services/kube-prometheus-stack/metadata.yaml
Update Grafana in KPS to the latest version to fix critical CVEs.
```
➜  ubuntu-dev git:(master) ✗ trivy image grafana/grafana:10.3.3 --severity CRITICAL
...
grafana/grafana:10.3.3 (alpine 3.18.4)
Total: 0 (CRITICAL: 0)
```
Manually tested Grafana runs without any issues and dashboards are working correctly:
https://d2iq.atlassian.net/browse/D2IQ-99993
```release-note
```
**Checklist**
> feat: bump grafana to the latest to fix critical CVEs

- .bloodhound.yml
bump to latest 1.28 and 1.29 k8s patch versions
https://d2iq.atlassian.net/browse/D2IQ-99776
```release-note
```
**Checklist**
> ci(bloodhound): Update k8s 1.28 and 1.29 versions

- services/project-grafana-loki/0.74.6/object-bucket-claims.yaml
- services/rook-ceph-cluster/1.13.2/objectbucketclaims/helmrelease.yaml
bump OBC to latest which adds templating for k8s version and defaults it to 1.29.2
https://d2iq.atlassian.net/browse/D2IQ-99984
```release-note
```
**Checklist**
> feat(obc): Bump to 0.1.11

- licenses.d2iq.yaml
- services/centralized-grafana/48.3.1/defaults/cm.yaml
- services/grafana-logging/6.60.1/defaults/cm.yaml
- services/kube-prometheus-stack/48.3.1/defaults/cm.yaml
- services/project-grafana-logging/6.60.1/defaults/cm.yaml
Image patched with copacetic - https://github.com/mesosphere/dkp-container-images/actions/runs/8005532506#summary-21865185492
https://d2iq.atlassian.net/browse/D2IQ-99997
```release-note
```
**Checklist**
> fix: bump mesosphere/grafana-plugins image - cve fixes

- .envrc
- hack/list-images.sh
* Fixes envrc to use devbox.
* Adds debug output to `list-images.sh` script so its possible to identify where an images comes from
```
+ ./common/build/kommander-cert-federation.yaml
docker.io/bitnami/kubectl:1.29.2
quay.io/kubernetes-multicluster/kubefed:v0.9.1
+ ./common/kommander-operator/helmrelease.yaml
docker.io/mesosphere/kommander2-core-installer:v2.8.0-dev
docker.io/mesosphere/kommander2-kubetools:v2.8.0-dev
+ ./services/ai-navigator-app/0.2.1/helmrelease/helmrelease.yaml
docker.io/bitnami/kubectl:1.26.4
docker.io/bitnami/postgresql:15.2.0-debian-11-r21
docker.io/mesosphere/ai-navigator-cluster-info-api:v0.1.0
docker.io/semitechnologies/weaviate:1.21.4
...
```
**Does …
> chore: debug list-images.sh script

- licenses.d2iq.yaml
- services/kubecost/0.37.3/defaults/cm.yaml
- Bumps version of grafana deployed by kubecost to 10.3.3 to resolve a CVE
https://d2iq.atlassian.net/browse/D2IQ-99992
I tested this manually on the daily cluster
```release-note
```
**Checklist**
> fix(kubecost): Bump grafana to 10.3.3 to resolve CVE-2023-49569

- common/build/kommander-cert-federation.yaml
- licenses.d2iq.yaml
Chart bump updates `kubefed` image and fixes critical CVEs.
JIRA: https://d2iq.atlassian.net/browse/D2IQ-100008
```release-note
```
**Checklist**
> chore(kommander-cert-federation): bump chart to v0.0.11

- licenses.d2iq.yaml
- services/rook-ceph-cluster/1.13.2/defaults/cm.yaml
- services/rook-ceph/1.13.2/defaults/cm.yaml
Bumps rook ceph container images with fixed CVEs.
https://d2iq.atlassian.net/browse/D2IQ-100005
```release-note
```
**Checklist**
> chore(rook-ceph): use custom patched images with fixed CVEs

- services/kube-oidc-proxy/0.3.4/defaults/cm.yaml
The `kube-oidc-proxy` image contains additional CA bundle that could be overriden specifically in the e2e tests https://github.com/mesosphere/dkp-container-images/tree/main/kube-oidc-proxy
```release-note
```
**Checklist**
> fix(kube-oidc-proxy): use custom copied certs bundle

- licenses.d2iq.yaml
- services/nvidia-gpu-operator/23.9.2/defaults/cm.yaml
This updates the nvidia gpu operator chart to use newer values for the component versions.
```release-note
```
**Checklist**
> feat: updates nvidia values to use all latest and pins toolkit

- licenses.d2iq.yaml
- services/kommander/0.8.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
Bumps cluster observer to 1.2.1. This updates `kubectl` image dependency to the latest `1.29.2`.
```release-note
```
**Checklist**
> chore: bump cluster-observer to 1.2.1

- .github/workflows/create-dev-tag.yml
Dependabot didn't detect correctly necessary update. The version we're referencing in our workflow is not longer available.
The action is no longer available:
```
Unable to resolve action `benc-uk/workflow-dispatch@v121`, unable to find version `v121`
```
Dependabot log
```
updater | 2024/03/18 06:47:28 INFO <job_801440859> Checking if benc-uk/workflow-dispatch 121 needs updating
proxy | 2024/03/18 06:47:28 [110] GET https://github.com:443/benc-uk/workflow-dispatch.git/info/refs?service=git-upload-pack
proxy | 2024/03/18 06:47:28 [110] * authenticating git server request (host: github.com)
proxy | 2024/03/18 06:47:28 [110] 200 https://github.com:443/benc-uk/workflow-dispatch.git/info/refs?service=git-upload-pack
updater | 2024/03/18 06:47:28 INFO …
```
> fix: update workflow-dispatch action

- apptests/environment/environment.go
- apptests/environment/environment_test.go
- apptests/go.mod
- apptests/go.sum
This PR fixes a bug that happens when common/base repositories are applied as part of the environment setup for testing the app. The bug was caused by using yaml.Decoder() incorrectly, which only decoded one resource. 
I have also set a `logger`  before using kubernetes generic client, which is required for using generic kubernetes client 
https://d2iq.atlassian.net/browse/D2IQ-98659
```release-note
```
**Checklist**
> feat: ensure base repositories are applied to cluster 

- services/grafana-logging/6.60.2/defaults/cm.yaml
- services/project-grafana-logging/6.60.2/defaults/cm.yaml
Fix the Grafana logging out of memory issue after upgrade to v9+
The Grafana get OOM killed status and the pod is in the CrachBackLoopoff State which causing the 502 and 404 issue. 
```
zihui.liu@C02F94FBML85 Desktop % k get pods -A | grep grafana-logging
kommander                           grafana-logging-68cf97499b-qvjvg                                    1/2     OOMKilled   8 (6m58s ago)   40m
```
After update the memory from 100Mi to 200Mi the issue has been solved. 
https://github.com/mesosphere/kommander-applications/blob/main/services/grafana-logging/6.60.2/defaults/cm.yaml#L75 
https://github.com/mesosphere/kommander-applications/blob/main/services/grafana-logging/6.60.2/defaults/cm.yaml#L78
> fix(grafana-logging): Fix OOM issue after upgrade to v9+

- licenses.d2iq.yaml
`kommander-ui` used to be referenced by `kommander` chart in DKP <= v2.5.x. 
This needs to be backported to v2.6, 2.7 and 2.8.
```release-note
```
**Checklist**
> fix(licensing): use static kommander-ui version

- licenses.d2iq.yaml
Manual backport of https://github.com/mesosphere/kommander-applications/pull/2054
```release-note
```
**Checklist**
> fix: use static kommander-ui version (2.7)

- licenses.d2iq.yaml
Manual backport of https://github.com/mesosphere/kommander-applications/pull/2054
```release-note
```
**Checklist**
> fix: use static kommander-ui version (2.6)

- licenses.d2iq.yaml
ensure the old kubectl images are no longer used and remove them from licenses file
```release-note
```
**Checklist**
> fix(licenses): Remove unused kubectl images

- charts/kommander-operator/Chart.yaml
- charts/kommander-operator/templates/rback_v1_clusterrole_operator_kommander-operator.yaml
Currently kommander-federater-view is getting excessive permissions
https://d2iq.atlassian.net/browse/D2IQ-100411
```release-note
```
**Checklist**
> fix: remove excessive label

- charts/kommander-operator/Chart.yaml
- charts/kommander-operator/templates/rback_v1_clusterrole_operator_kommander-operator.yaml
Currently kommander-federater-view is getting excessive permissions
https://d2iq.atlassian.net/browse/D2IQ-100411
```release-note
```
**Checklist**
> fix: [backport-2.7] rm kmd operator rbac label 2.7

- services/ai-navigator-app/0.2.2/helmrelease.yaml
- services/ai-navigator-cluster-info-agent/0.1.1/helmrelease.yaml
`v1beta2` flux kustomization is deprecated and seeing the warning in manifest validation CI runs.
```release-note
```
**Checklist**
> chore: [backport-2.8] bump flux kust api version in ai nav

- services/centralized-grafana/48.3.2/centralized-grafana.yaml
- services/kube-prometheus-stack/48.3.2/helmrelease/kube-prometheus-stack.yaml
backport the KPS chart bump for 2.8 regarding the RBAC issue.
https://d2iq.atlassian.net/browse/D2IQ-100406
```release-note
```
**Checklist**
> fix: [backport-2.8] bump centr grafana and KPS chart version

- charts/kommander-operator/Chart.yaml
- charts/kommander-operator/templates/rback_v1_clusterrole_operator_kommander-operator.yaml
Currently kommander-federater-view is getting excessive permissions
https://d2iq.atlassian.net/browse/D2IQ-100411
```release-note
```
**Checklist**
> fix: [backport-2.8] remove excessive label

- hack/release/pkg/appversion/appversion_test.go
- services/kommander/0.8.0/kommander.yaml
Remove versioning from the optional kommander chart overrides CM.
https://d2iq.atlassian.net/browse/D2IQ-100445
```release-note
```
**Checklist**
> fix: add general kommander overrides cm

- .github/workflows/create-dev-tag.yml
- make/repo.mk
Let's generate dev version instead of hardcoding them.
Depends on https://github.com/mesosphere/gh-dkp/pull/451
```release-note
```
**Checklist**
> ci: Generate dev tags dynamically

- services/kube-prometheus-stack/48.3.2/grafana-dashboards/kustomization.yaml
- services/kube-prometheus-stack/48.3.2/grafana-dashboards/pv-stats.json
Add https://grafana.com/grafana/dashboards/13646-kubernetes-persistent-volumes/ grafana dashboard to default set deployed with dkp. Request from support team
This has been tested on the daily cluster
```release-note
```
**Checklist**
> feat(grafana): Add PV Stats grafana dashboard

- services/kommander/0.8.0/defaults/cm.yaml
Set newly added kommander values to define set of default apps that should be deployed to the mgmt cluster workspace by default. these apps (sso, reloader for now) must be part of the minimal set of apps for kommander functionality and ability of users to access the UI
This goes along with https://github.com/mesosphere/kommander/pull/4421 which consumes this new field
https://d2iq.atlassian.net/browse/D2IQ-100424
```release-note
```
**Checklist**
> feat(kommander): Specify default mgmt apps in values

- common/helm-repositories/ai-navigator-repos.yaml
- common/helm-repositories/kustomization.yaml
- common/helm-repositories/mesosphere-repos.yaml
- make/release.mk
Separate ai-nav helmrepos to separate file so we can exclude it from the bundle. I am depending on this kcli bug https://jira.nutanix.com/browse/D2IQ-97040 to continue to exist to ensure that the `kustomize` won't fail (kustomization.yaml specifies ai-nav file which is removed)
```release-note
```
**Checklist**
> fix(release): Omit ai-nav helmrepos from bundle

- licenses.d2iq.yaml
- services/fluent-bit/0.43.0/grafana-dashboards-logging/audit.json
- services/grafana-logging/6.60.2/defaults/cm.yaml
- services/grafana-logging/6.60.2/grafana.yaml
- services/project-grafana-logging/6.60.2/defaults/cm.yaml
Cherry-pick changes in https://github.com/mesosphere/kommander-applications/pull/2119 to release-2.8 branch.
Kubernetes Audit Dashboard failing in Grafana Logging v9+
https://d2iq.atlassian.net/browse/D2IQ-99728
Upgraded the Grafana version to version 10.4.2 which is the latest version. 
Test result in Grafana 10.3.3
> fix: Fix Kubernetes Audit Dashboard failing in Grafana Logging v9+

- services/kube-prometheus-stack/48.3.2/grafana-dashboards/kustomization.yaml
- services/kube-prometheus-stack/48.3.2/grafana-dashboards/pv-stats.json
backports https://github.com/mesosphere/kommander-applications/pull/2124 to release-2.8
```release-note
```
**Checklist**
> feat(grafana): Add PV Stats grafana dashboard (#2124)

- apptests/appscenarios/appscenarios.go
- apptests/appscenarios/reloader.go
- apptests/appscenarios/reloader_test.go
- apptests/constants/apps.go
some functions are there when we decided to not use ginkgo.
```release-note
```
**Checklist**
> refactor: cleanup and use constructor func

- hack/build-archive.sh
- make/release.mk
* fix: Modify files in the release archive
* fix: Path to a script
---------
backports https://github.com/mesosphere/kommander-applications/pull/2154 to release-2.8
```release-note
```
**Checklist**
> fix: Modify files in the release archive (#2154)

- apptests/appscenarios/contants.go
- apptests/appscenarios/kubecost.go
- apptests/appscenarios/kubecost_test.go
- apptests/appscenarios/suite_test.go
- apptests/constants/apps.go
Adds basic application specific tests for Kubecost. Covers upgrade and install.
https://jira.nutanix.com/browse/D2IQ-100304
```release-note
```
**Checklist**
> feat: Add basic kubecost tests for install and upgrade

- apptests/appscenarios/kubecost.go
Use the correct constant for the `kubecost` app name in the tests
```release-note
```
**Checklist**
> fix: Use correct constant for app name

- hack/list-images.sh
Exclude the `apptests` dir in the `grep` part of the `list-images.sh` script. These charts/repos/images are added to the kommander install and are causing issues with the `HelmReleases` that exist in the `apptests` directory. 
Testing by overriding the kommander-applications` dir in this temp PR: https://github.com/mesosphere/kommander/pull/4500
```release-note
```
**Checklist**
> ci: Exclude apptests dir in list-images.sh script

- apptests/appscenarios/externaldns.go
- apptests/appscenarios/externaldns_test.go
- apptests/constants/apps.go
Adds app-specific tests for External DNS.
- Tests use configuration as specified in `kommander-applications`, though a typical installation would need some configuration.
- These tests do not test an AWS or Azure install. We assume that External DNS does what it is supposed to and that our [documentation](https://docs.d2iq.com/dkp/2.7/configure-an-external-dns-management-or-essential-) is not Kommander/DKP specific.
- We are primarily looking for the metrics servers to be up and emitting metrics.
https://jira.nutanix.com/browse/D2IQ-100300
- There is an "issue" with configuration that is in `v2.7.0` version of `kommander-applications`. This has external-dns `v0.13.6` (app/chart …
> feat: Add External DNS tests

- services/centralized-grafana/48.3.2/defaults/cm.yaml
after upgrading to grafana 10, the default memory limit is no longer enough. KPS k-app has been bumped but centralized grafana resource limit bump was missed.
https://jira.nutanix.com/browse/NCN-100776
```release-note
```
**Checklist**
> chore: bump centralized grafana resource limits

- apptests/appscenarios/karma.go
- apptests/appscenarios/karma_test.go
use `traefik` object to install traefik in karma test
```release-note
```
**Checklist**
> refactor: use traefik object to install traefik

- apptests/flux/apply.go
- apptests/go.mod
- apptests/go.sum
currently we are importing fluxcd notification and image controllers API, which we currently don't use
```release-note
```
**Checklist**
> chore: drop unused fluxcd api import

- services/kommander/0.12.0/defaults/cm.yaml
looks like we never added `kommander-ui` to the list of mgmt apps. (one of the) impacts of this is that expanded clusters still get `kommander-ui` enabled on them. the app never becomes ready bc it is dependent on `kommander`, which, as expected, is not running on these expanded clusters post expansion.
```release-note
```
**Checklist**
> fix(kommander): Add kommander-ui to mgmt apps

- licenses.d2iq.yaml
- services/git-operator/0.0.0/git-operator.yaml
Bumps git-operator to a version that has user management and can perform git repository initialisation with an empty commit.
This is a prerequisite to https://jira.nutanix.com/browse/NCN-99979
```release-note
```
**Checklist**
> feat: bump git-operator to v0.2.0

- charts/kommander-operator/templates/rback_v1_clusterrole_operator_kommander-operator.yaml
Should fix the error ```unable to index manager cache	{"error": "failed to get API group resources: unable to retrieve the complete list of server APIs: apps.kommander.d2iq.io/v1alpha3: the server could not find the requested resource"}
github.com/mesosphere/kommander/v2/common/pkg/log.(*logger).Error```
```release-note
```
**Checklist**
> feat(koperator): Add necessary read perms for clusterapps

- services/git-operator/0.0.0/defaults/kustomization.yaml
Allows to use the app installation code in the CLI
Yet another prerequisite to https://jira.nutanix.com/browse/NCN-99979
```release-note
```
**Checklist**
> fix: add a defaults Kustomization expected by the CLI to git-operator

- devbox.json
- devbox.lock
- hack/release/go.mod
Let's use the latest go binary
```release-note
```
**Checklist**
> ci: Bump go to 1.22

- services/git-operator/0.0.0/git-operator.yaml
- services/traefik/27.0.2/defaults/cm.yaml
Makes it possible for Flux on attached clusters to access the platform Git repository in GitOperator-based installations. 
To avoid complicating migration from Gitea (which is exposed using  the `dkp/kommander/git` prefix), GitOperator is exposed using a different prefix.
- Prerequisite to https://jira.nutanix.com/browse/NCN-100835
Will be used by https://github.com/mesosphere/kommander/pull/4623
```release-note
```
**Checklist**
> feat: add an Ingress for git-operator

- licenses.d2iq.yaml
- services/kommander/0.12.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
cluster-observer doesnt support helm v2b2
https://jira.nutanix.com/browse/NCN-101035
```release-note
```
**Checklist**
> chore: bump cluster-observer to 1.3.0 w/ helm v2b2

- .github/workflows/application-test-scenario-install.yaml
- .github/workflows/application-test-scenario-upgrade.yaml
- .github/workflows/application-test.yaml
for workflow dispatch
right not it doesnt trigger upon new PRs. also it cannot handle more than 1 app
```release-note
```
**Checklist**
> ci: add (re)open events for prs and handle 2+ apps

- charts/kommander-operator/templates/deployment.yaml
- charts/kommander-operator/values.yaml
Add feature flag to gate the upgrade logic that has been partially completed in kcore operator. We can use the flag to test upgrade once we are ready to continue development.
This flag is used in https://github.com/mesosphere/kommander/pull/4655
https://jira.nutanix.com/browse/NCN-100567
```release-note
```
**Checklist**
> feat(koperator): Add feature flag gate for kcore upgrade

- licenses.d2iq.yaml
- services/nvidia-gpu-operator/24.3.0/defaults/cm.yaml
- services/nvidia-gpu-operator/24.3.0/helmrelease/extra-images.txt
```release-note
```
**Checklist**
> fix: gfd no longer uses its own image

- .bloodhound.yml
- apptests/appscenarios/contants.go
- common/build/list-images-values.yaml
- licenses.d2iq.yaml
- services/ai-navigator-app/0.2.2/defaults/cm.yaml
- services/centralized-kubecost/0.37.3/defaults/cm.yaml
- services/centralized-kubecost/0.37.3/post-install-jobs/post-install-jobs.yaml
- services/centralized-kubecost/0.37.3/release/release.yaml
- services/dex/2.13.12/defaults/cm.yaml
- services/dkp-insights-management/1.1.1/defaults/cm.yaml
- services/dkp-insights/1.1.2/defaults/cm.yaml
- services/grafana-loki/0.78.5/grafana-loki-pre-install-jobs/pre-install.yaml
- services/istio/1.21.1/defaults/cm.yaml
- services/knative/1.10.5/defaults/cm.yaml
- services/kommander/0.12.0/dynamic-helmreleases/cluster-observer/list-images-values.yaml
- services/kube-prometheus-stack/48.3.2/defaults/cm.yaml
- services/kubecost/0.37.3/defaults/cm.yaml
- services/kubefed/0.10.5/defaults/cm.yaml
- services/kubetunnel/0.0.33/defaults/cm.yaml
- services/project-grafana-loki/0.78.5/defaults/cm.yaml
- services/rook-ceph-cluster/1.14.2/defaults/cm.yaml
- services/rook-ceph-cluster/1.14.2/pre-install/ceph-crd-check.yaml
- services/thanos/15.4.1/jobs/jobs.yaml
- services/traefik/27.0.2/defaults/cm.yaml
- services/velero/6.6.0/defaults/cm.yaml
- services/velero/6.6.0/velero-pre-install.yaml
bump k8s to 1.29.6
bump kubectl image in apps to 1.29.6
https://jira.nutanix.com/browse/NCN-101202
```release-note
```
**Checklist**
> feat: Bump k8s and kubectl to 1.29.6

- .github/dependabot.yml
adding labels to set automatically on dependabot prs to run tests, and for application test dep updates, adding a services label as well to run an actual app test 
```release-note
```
**Checklist**
> ci: Set labels on dependabot prs

- hack/flux/flux-update-kustomization.yaml
- services/kommander-flux/2.2.3/templates/apps_v1_deployment_notification-controller.yaml
Now that flux is deployed in kommander bootstrapper job before cloning the k-apps repo, i think its easier to deploy it with standard priority classes set up. 
Alternative is to skip notification controller deployment at the start but I felt the approach in this PR keeps things more consistent. 
```release-note
```
**Checklist**
> chore: bump priorityclass for notification controller

- .github/workflows/flux-update-scheduled-check.yml
Let's allow to trigger the flux update job manually.
```release-note
```
**Checklist**
> ci: Allow to manually run flux update job

- .github/workflows/application-test-scenario-install.yaml
- .github/workflows/application-test-scenario-upgrade.yaml
- apptests/appscenarios/certmanager_test.go
- apptests/appscenarios/externaldns_test.go
- apptests/appscenarios/gatekeeper_test.go
- apptests/appscenarios/karma_test.go
- apptests/appscenarios/kommanderflux_test.go
- apptests/appscenarios/kubecost_test.go
- apptests/appscenarios/reloader_test.go
- apptests/appscenarios/rookceph_test.go
- apptests/appscenarios/traefik_test.go
- apptests/appscenarios/velero_test.go
Skips the teardown of the test cluster in the CI. THis allows the support bundle to be collected as needed.
```release-note
```
**Checklist**
> feat: Conditional cluster teardown in app tests

- charts/kommander-operator/templates/rback_v1_clusterrole_operator_kommander-operator.yaml
add cluster-admin CRB needed for kommander operator
```release-note
```
**Checklist**
> feat: giving kommander-operator cluster-admin

- services/velero/4.1.2/defaults/cm.yaml
- services/velero/4.1.2/helmrelease/helmrelease.yaml
- services/velero/4.1.2/velero-post-install.yaml
- services/velero/4.1.2/velero-pre-install.yaml
- services/velero/4.1.2/velero.yaml
missed bumps for velero limits fix
```release-note
```
**Checklist**
> fix: [backport-2.7] velero with bumped limits 

- .github/workflows/kommander-branch.yaml
I think that this can fail in some cases when PR body contains `'` character.
https://github.com/mesosphere/kommander-applications/actions/runs/9888081767/job/27311190768?pr=2394
```release-note
```
**Checklist**
> fix: open kommander branch body quoting

- licenses.d2iq.yaml
- services/gitea/8.2.1/defaults/cm.yaml
Patch memcached image with fixed CVE's
workflow link:
https://github.com/mesosphere/dkp-container-images/actions/runs/9886039464
https://jira.nutanix.com/browse/NCN-101394
```release-note
```
**Checklist**
> fix: memcached patched image with fixed CVE

- services/git-operator/0.1.0/git-operator-manifests/all.yaml
```release-note
```
**Checklist**
> chore: bump git-operator to v0.8.3

- services/git-operator/0.1.0/ingress.yaml
Missed this change in https://github.com/mesosphere/kommander-applications/pull/2400
```release-note
```
**Checklist**
> fix: git-operator ingress port

- hack/list-images.sh
- justfile
- licenses.d2iq.yaml
- services/git-operator/0.1.0/additional-images.txt
- services/git-operator/0.1.0/git-operator-manifests/all.yaml
Makes the airgapped installation (incl. airgapped validation tests) work with Git Operator.
A temporary solution to https://jira.nutanix.com/browse/NCN-101519
The local docker registry used in Kommander airgapped validation tests (and probably some other docker registry) exhibits a weird behaviour where it fails to provide an image when the image ref uses the `image:tag@sha256...` syntax; this is why this PR strips the SHA part in `git-operator` manifests.
```release-note
```
**Checklist**
> fix: make git-operator images appear in the airgapped bundle

- services/kubernetes-dashboard/7.5.0/defaults/cm.yaml
awsgke e2e tests are failing on kubernetes-dashboard failing to come up ready. Trying to see how to fix it.
Also, found a few indentation errors in values.yaml
https://jira.nutanix.com/browse/NCN-101453
```release-note
```
**Checklist**
> fix(kubernetes-dashboard): Make deployable on gke

- licenses.d2iq.yaml
- services/git-operator/0.1.0/additional-images.txt
- services/git-operator/0.1.0/git-operator-manifests/all.yaml
```release-note
```
**Checklist**
> chore: bump git-operator to v0.9.0

- services/chartmuseum/3.10.2/ingress.yaml
- services/chartmuseum/3.10.2/kustomization.yaml
It looks like chartmuseum manifests only existed in the k-cli:
https://github.com/mesosphere/kommander-cli/blob/main/pkg/chartmuseum/manifests/ingress.yaml
Let's move it here so we can deploy a fully functional chartmuseum without the cli.
```release-note
```
**Checklist**
> feat: Add chartmuseum ingress

- licenses.d2iq.yaml
- services/git-operator/0.1.0/additional-images.txt
- services/git-operator/0.1.0/git-operator-manifests/all.yaml
Title says it all
```release-note
```
**Checklist**
> chore: Bump git operator to v0.9.1

- .bloodhound.yml
We don't need to validate pre 1.28 k8s versions compatibility.
```release-note
```
**Checklist**
> chore: remove old k8s version bloodhound validation

- licenses.d2iq.yaml
- services/centralized-kubecost/0.37.4/defaults/cm.yaml
- services/kubecost/0.37.4/defaults/cm.yaml
Patch kubecost image with fixed CVE's
workflow link:
https://github.com/mesosphere/dkp-container-images/actions/runs/9833998335
https://jira.nutanix.com/browse/NCN-101394
```release-note
```
**Checklist**
> fix: kubecost patched image with fixed CVEs

- licenses.d2iq.yaml
- services/nvidia-gpu-operator/24.3.1/defaults/cm.yaml
- services/nvidia-gpu-operator/24.3.1/helmrelease/extra-images.txt
Patch k8s-device-plugin:v0.15.0-ubi8-d2iq.0 and gpu-operator-validator image with fixed CVE's
workflow link
https://github.com/mesosphere/dkp-container-images/actions/runs/9962429325
https://github.com/mesosphere/dkp-container-images/actions/runs/9902973870
`sandhya.ravi@GT9X7CVF5F kommander-applications % trivy image ghcr.io/mesosphere/dkp-container-images/nvcr.io/nvidia/cloud-native/gpu-operator-validator:v24.3.0-d2iq.0  --vuln-type os --ignore-unfixed | grep Total 2024-07-16T16:32:13+05:30	INFO	Vulnerability scanning is enabled 2024-07-16T16:32:13+05:30	INFO	Secret scanning is enabled 2024-07-16T16:32:13+05:30	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning 2024-07-16T16:32:13+05:30	INFO	Please see also …
> fix: gpuoperator patched image with fixed CVE

- services/git-operator/0.1.0/defaults/kustomization.yaml
An empty kustomization causes the flux kustomization failure.
https://jira.nutanix.com/browse/NCN-101714
```release-note
```
**Checklist**
> fix: Add contents to git-operator defaults kustomization

- services/traefik/27.0.2/defaults/cm.yaml
Work around for Traefik issue: https://github.com/traefik/traefik/issues/5853
URLs with `api` later in the URL are also being rewritten resulting in a 404.
As a workaround, pin the match to the beginning of the URL by matching the label too:
```
rewrites:
- regex: apiUrl:\"/api\"
replacement: apiUrl:"/dkp/traefik/api"
```
See Slack: https://nutanix.slack.com/archives/C067BPT2MQ9/p1719940306056019
https://jira.nutanix.com/browse/NCN-101671
```release-note
```
**Checklist**
> feat: Fix Traefik rewrite for api url

- licenses.d2iq.yaml
- services/git-operator/0.1.0/additional-images.txt
- services/git-operator/0.1.0/git-operator-manifests/all.yaml
Bumping git operator to v0.11.0
```release-note
```
**Checklist**
> feat: Bump git operator to v0.11.0

- licenses.d2iq.yaml
- services/git-operator/0.1.0/additional-images.txt
https://nutanix.slack.com/archives/C06A78Y063B/p1722245168452669
```release-note
```
**Checklist**
> fix: patched git-operator Nginx image in airgapped bundle

- licenses.d2iq.yaml
- services/git-operator/0.1.0/additional-images.txt
- services/git-operator/0.1.0/git-operator-manifests/all.yaml
bump git-operator to latest v0.12.0
https://jira.nutanix.com/browse/NCN-101764
```release-note
```
**Checklist**
> feat(git-operator): Bump to 0.12.0

- .github/workflows/labeler.yaml
According to this page [^1]
> When you use the repository's `GITHUB_TOKEN` to perform tasks, events triggered by the `GITHUB_TOKEN`, with the exception of `workflow_dispatch` and `repository_dispatch`, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs.
I believe that's the reason we need to manually remote and re-add the `update-licenses` label for the automatic update to trigger.
[^1]: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
```release-note
```
**Checklist**
> ci: add update-licenses label with Mesosphere bot

- .github/workflows/validate-licenses.yaml
According to this page [^1]
> When you use the repository's `GITHUB_TOKEN` to perform tasks, events triggered by the `GITHUB_TOKEN`, with the exception of `workflow_dispatch` and `repository_dispatch`, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs.
I believe that's the reason we need to manually close and re-open the PR to trigger a verification on the updated head with the automated license change commit.
[^1]: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
```release-note
```
**Checklist**
> ci: update licenses with user token

- apptests/go.mod
- apptests/go.sum
- magefiles/go.mod
Update [github.com/docker/docker](https://github.com/docker/docker) to v26.1.5+incompatible to fix cve
https://www.docker.com/blog/docker-security-advisory-docker-engine-authz-plugin/
https://avd.aquasec.com/nvd/2024/cve-2024-41110/
https://jira.nutanix.com/browse/NCN-101805
```release-note
```
**Checklist**
> fix: update the docker to v26.1.5+incompatible to fix cve

- licenses.d2iq.yaml
- services/kubetunnel/0.0.34/kubetunnel.yaml
bump kubetunnel to v0.0.34
```release-note
```
**Checklist**
> chore: bump kubetunnel to v0.0.34

- licenses.d2iq.yaml
```release-note
```
**Checklist**
> fix: add license mapping for remaining images

- hack/list-images.sh
err="failed to read image descriptor for "docker.io/registry.k8s.io/pause:3.10" from registry: GET https://index.docker.io/v2/registry.k8s.io/pause/manifests/3.10: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:registry.k8s.io/pause Type:repository]]"
```release-note
```
**Checklist**
> fix: the list-images regex

- services/velero/metadata.yaml
There is an old reference to a now-unsupported version of DKP.
This removes that.
N/A
n/a
solely text on the application details page.
**Checklist**
> docs: removing old dkp references

- services/kommander/0.12.0/defaults/cm.yaml
Adds a list of Apps which need to be deployed for Nutanix infra only when upgrading from `Starter` to `Pro`/`Essentials` licenses.
For non-Nutanix infra, this set of apps is configured and installed by Kommander CLI.
https://jira.nutanix.com/browse/NCN-101939
```release-note
```
**Checklist**
> feat: Add Pro Apps autodeploy list

- licenses.d2iq.yaml
- services/dex/2.13.13/defaults/cm.yaml
```release-note
```
**Checklist**
> chore: bump dex image to v2.37.0-d2iq.5

- .github/workflows/backport.yaml
this token should allow backport PRs to get created
```release-note
```
**Checklist**
> build: Use mesosphere token for backporting

- services/kiali/1.87.0/defaults/cm.yaml
We must override the kiali image to the distroless image (to resolve CVEs)
Relevant: https://github.com/kiali/kiali/issues/6580
Tested on the daily cluster
https://jira.nutanix.com/browse/NCN-102082
```release-note
```
**Checklist**
> fix(kiali): Override to use distroless kiali image

- hack/release/cmd/postrelease/postrelease.go
- hack/release/pkg/upgradematrix/upgradematrix.go
- hack/release/pkg/upgradematrix/upgradematrix_test.go
Update `upgrade-matrix.yaml` in post release.
https://jira.nutanix.com/browse/NCN-100509
Test manually with `go run . post-release --version v1.2.3 --repo <path to kommander-applications>` in `hack/release` with `gh-dkp` installed.
```release-note
```
**Checklist**
> feat: Update upgrade-matrix.yaml in post-upgrade

- hack/release/cmd/postrelease/postrelease.go
- hack/release/pkg/upgradematrix/upgradematrix.go
- hack/release/pkg/upgradematrix/upgradematrix_test.go
Updates `upgrade-matrix.yaml` in post-release with the value from an environment variable. The variable is set in `gh-dkp`
https://github.com/mesosphere/gh-dkp/pull/492 needs to be merged first.
https://jira.nutanix.com/browse/NCN-100509
Test manually with:
```
export NKP_RELEASE_AUTOMATION_UPGRADE_MATRIX="upgrades:"
go run . post-release --version v2.21.31 --repo /Users/luke.ogg/Projects/kommander-applications
```
```release-note
```
**Checklist**
> feat: Update upgrade-matrix.yaml in post-upgrade based on env variable

- .github/workflows/flux-update-scheduled-check.yml
- hack/flux/update-flux.sh
Fixed up a few things in the automated flux bump workflow. Working test run https://github.com/mesosphere/kommander-applications/actions/runs/11060715919 which produced PR https://github.com/mesosphere/kommander-applications/pull/2664 (closed since I was triggering it against this branch so an extra commit was on there)
If the branch already exists then it should exit gracefully as a success instead of looking like a failed run.
https://jira.nutanix.com/browse/NCN-102720
```release-note
```
**Checklist**
> build(gha): Flux update fixes

- apptests/kind/kind.go
fix the below error
`Error response from daemon: client version 1.46 is too new. Maximum supported API version is 1.45`
https://nutanix.slack.com/archives/C06KX3DPA9K/p1727705385264839
```release-note
```
**Checklist**
> fix: docker client fix

- apptests/appscenarios/contants.go
- common/build/list-images-values.yaml
- licenses.d2iq.yaml
- services/ai-navigator-app/0.2.5/defaults/cm.yaml
- services/centralized-kubecost/0.37.5/defaults/cm.yaml
- services/centralized-kubecost/0.37.5/post-install-jobs/post-install-jobs.yaml
- services/centralized-kubecost/0.37.5/release/release.yaml
- services/dex/2.14.0/defaults/cm.yaml
- services/grafana-loki/0.79.4/grafana-loki-pre-install-jobs/pre-install.yaml
- services/istio/1.23.2/defaults/cm.yaml
- services/knative/1.10.5/defaults/cm.yaml
- services/kommander/0.13.0/dynamic-helmreleases/cluster-observer/list-images-values.yaml
- services/kube-prometheus-stack/63.0.0/defaults/cm.yaml
- services/kubecost/0.37.6/defaults/cm.yaml
- services/kubefed/0.10.5/defaults/cm.yaml
- services/kubetunnel/0.0.36/defaults/cm.yaml
- services/nkp-insights-management/1.2.2/defaults/cm.yaml
- services/nkp-insights/1.2.2/defaults/cm.yaml
- services/project-grafana-loki/0.79.4/defaults/cm.yaml
- services/rook-ceph-cluster/1.14.5/defaults/cm.yaml
- services/rook-ceph-cluster/1.14.5/pre-install/ceph-crd-check.yaml
- services/thanos/15.7.23/jobs/jobs.yaml
- services/traefik/27.0.2/defaults/cm.yaml
- services/velero/7.1.4/defaults/cm.yaml
bump kubectl image in apps to 1.30.5
`sandhya.ravi@GT9X7CVF5F kommander-applications % trivy i docker.io/bitnami/kubectl:1.30.5
2024-09-30T12:20:15+05:30	INFO	Vulnerability scanning is enabled
2024-09-30T12:20:15+05:30	INFO	Secret scanning is enabled
2024-09-30T12:20:15+05:30	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-09-30T12:20:15+05:30	INFO	Please see also https://aquasecurity.github.io/trivy/v0.53/docs/scanner/secret#recommendation for faster secret detection
2024-09-30T12:20:18+05:30	INFO	Detected OS	family="debian" version="12.7"
2024-09-30T12:20:18+05:30	INFO	[debian] Detecting vulnerabilities...	os_version="12" pkg_num=127
2024-09-30T12:20:18+05:30	INFO	Number of language-specific files	num=5 …
> feat: bump kubectl to 1.30.5 with cve fix

- services/velero/7.1.4/velero-pre-install.yaml
Missed one bump of kubectl
```release-note
```
**Checklist**
> fix: bump kubectl in velero pre install

- licenses.d2iq.yaml
- services/kube-prometheus-stack/63.0.0/defaults/cm.yaml
bump kube-webhook-certgen to 1.4.3 with cve fix
`sandhya.ravi@GT9X7CVF5F kommander-applications % trivy i registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.3
2024-10-03T00:20:37+05:30	INFO	Vulnerability scanning is enabled
2024-10-03T00:20:37+05:30	INFO	Secret scanning is enabled
2024-10-03T00:20:37+05:30	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-10-03T00:20:37+05:30	INFO	Please see also https://aquasecurity.github.io/trivy/v0.53/docs/scanner/secret#recommendation for faster secret detection
2024-10-03T00:20:39+05:30	INFO	Detected OS	family="debian" version="12.6"
2024-10-03T00:20:39+05:30	INFO	[debian] Detecting vulnerabilities...	os_version="12" pkg_num=3
2024-10-03T00:20:39+05:30	INFO	Number …
> feat: bump kube-webhook-certgen to 1.4.3

- justfile
Right now it creates `s3:///foobar`, let's make it `s3://foobar`.
```release-note
```
**Checklist**
> build: Fix how S3 URL is constructed

- .github/workflows/test.yaml
- devbox.json
- devbox.lock
- just/test.just
- justfile
- server/Dockerfile
Produce a docker image with http server.
https://jira.nutanix.com/browse/NCN-102822
To move things quickly, I'm using github.com/sigoden/dufs. I use it because it supports tls but I'm planning to create our own (maybe a few lines in Python - let's see what's the fastest).
```release-note
```
**Checklist**
> feat: Add server that provides k-apps contents

- apptests/appscenarios/kubecost_test.go
- licenses.d2iq.yaml
- services/kube-prometheus-stack/63.0.0/defaults/cm.yaml
- services/kubecost/0.37.6/defaults/cm.yaml
update kube-state-metrics to v2.13.0
https://jira.nutanix.com/browse/NCN-102773
```release-note
```
**Checklist**
> feat: bump kube-state-metrics to v2.13.0

- .bloodhound.yml
bump k8s 1.29 bloodhound validation version
https://jira.nutanix.com/browse/NCN-103093
```release-note
```
**Checklist**
> ci(bloodhound): Update k8s 1.29 version to 1.29.9

- .github/workflows/automerge.yaml
seeing if this fixes automerge to trigger the workflow successfully for chartbump prs and prs labeled with `auto-merge`
```release-note
```
**Checklist**
> ci(automerge): Update/fix automerge workflow

- hack/release/cmd/postrelease/postrelease.go
- hack/release/cmd/prerelease/prerelease.go
- hack/release/pkg/extraimages/extraimages.go
- hack/release/pkg/extraimages/extraimages_test.go
- licenses.d2iq.yaml
- services/kommander/0.13.0/extra-images.txt
We need to make sure that the newly created kommander applications server image is in the airgapped bundle.
https://jira.nutanix.com/browse/NCN-102822
```release-note
```
**Checklist**
> feat: Add extra image of kommander applications server

- licenses.d2iq.yaml
```release-note
```
**Checklist**
> fix: remove additional image tag trim

- justfile
Follow up of https://github.com/mesosphere/kommander-applications/pull/2710
Above change corrupted how we publish artifacts cuz i see:
```bash
❯ curl -L https://downloads.d2iq.com/dkp/v2.13.0-dev.2 --output local.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  449k  100  449k    0     0  1414k      0 --:--:-- --:--:-- --:--:-- 1413k
❯ tar -tvf local.tar.gz
drwxr-xr-x runner/runner     0 2024-10-14 18:30 ./
drwxr-xr-x runner/runner     0 2024-10-14 18:29 ./charts/
drwxr-xr-x runner/runner     0 2024-10-14 18:29 ./charts/kommander-operator/
-rw-r--r-- runner/runner   168 2024-10-14 18:29 ./charts/kommander-operator/Chart.yaml
``` …
> ci: use explicit name when publishing s3 blobs

- licenses.d2iq.yaml
- services/logging-operator/4.2.5/defaults/cm.yaml
Bump docker.io/fluent/fluent-bit to 2.2.3-d2iq.1 CVE fix
https://jira.nutanix.com/browse/NCN-102779
> feat: Bump docker.io/fluent/fluent-bit cve fix

- licenses.d2iq.yaml
- services/centralized-grafana/63.0.0/defaults/cm.yaml
- services/centralized-kubecost/0.37.6/defaults/cm.yaml
- services/grafana-logging/8.3.6/defaults/cm.yaml
- services/kube-prometheus-stack/63.0.0/defaults/cm.yaml
- services/kubecost/0.37.7/defaults/cm.yaml
- services/project-grafana-logging/8.3.5/defaults/cm.yaml
bump kiwigrid/k8s-sidecar to 1.27.6
https://jira.nutanix.com/browse/NCN-102780
**Checklist**
> feat: bump kiwigrid/k8s-sidecar to 1.28.0

- licenses.d2iq.yaml
- services/gatekeeper/3.17.0/defaults/cm.yaml
```release-note
```
**Checklist**
> fix: bump curl to 8.9.1

- .github/workflows/release.yml
Triggers slack notifications when release is failed as well as successful (for non `-dev` releases)
[jira.nutanix.com/browse/NCN-103687](https://jira.nutanix.com/browse/NCN-103687)
```release-note
```
**Checklist**
> feat: send slack notifications on success and failure

- .github/workflows/release.yml
Follow up of #2814 
Lets use a different channel for daily dev release alerts to keep the ship-it channel less chatty.
```release-note
```
**Checklist**
> fix: use `ncn-system-ops` slack for daily alerts

- services/rook-ceph-cluster/1.14.5/pre-install/ceph-crd-check.yaml
```release-note
```
**Checklist**
> fix: `s/lastAppliedRevision/lastAttemptedRevision/` after flux bump

- just/test.just
- justfile
Publish open source code images to ghcr instead of docker registry
```release-note
```
**Checklist**
> feat: publish kapps server to ghcr

- .github/workflows/release.yml
For https://github.com/mesosphere/kommander-applications/pull/2753 to work, we need write access to ghcr.
```release-note
```
**Checklist**
> build: Allow to write packages to release to ghcr

- services/grafana-loki/0.79.5/defaults/cm.yaml
When looking at the production cluster due to an unrelated issue @fatz raised, i found that the loki compactor was printing the following error 
```
❯ k logs -nkommander grafana-loki-loki-distributed-compactor-0 -f
level=error ts=2024-11-19T23:16:56.703832344Z caller=compactor.go:523 msg="failed to run compaction" err="index store client not found for aws"
level=error ts=2024-11-19T23:26:56.703352606Z caller=compactor.go:523 msg="failed to run compaction" err="index store client not found for aws"
level=error ts=2024-11-19T23:36:56.702274812Z caller=compactor.go:523 msg="failed to run compaction" err="index store client not found for aws"
level=error ts=2024-11-19T23:46:56.704304251Z caller=compactor.go:523 msg="failed to run compaction" err="index …
```
> fix: broken store config in grafana loki

- .github/workflows/release.yml
We need the right credentials.
```release-note
```
**Checklist**
> build: Login to ghcr in order to push to it

- services/ai-navigator-cluster-info-agent/0.1.2/defaults/cm.yaml
Removes the hardcoded tag and use the default chart value, so we don't have to maintain that in both places.
```release-note
```
**Checklist**
> fix: Remove hardcoded image in for ai-navigator-cluster-info-agent

- hack/release/pkg/extraimages/extraimages.go
- hack/release/pkg/extraimages/extraimages_test.go
The release automation has to be adjusted too:
https://github.com/mesosphere/kommander-applications/commit/199536d025c3124eefcd96ad903f77787d69a171#diff-320fd277251bdefe63fc147281f3cec45d88932c9e31bfcf17f8658b2ad03e97R1
```release-note
```
**Checklist**
> build: Adjust the release automation to handle ghcr

- licenses.d2iq.yaml
- services/centralized-kubecost/0.37.7/defaults/cm.yaml
- services/kubecost/0.37.8/defaults/cm.yaml
patch and bump frontend image
workflow:
https://github.com/mesosphere/dkp-container-images/actions/runs/11930752381
```release-note
```
**Checklist**
> fix: patch and bump kubecost images to fix cve

- services/kube-prometheus-stack/65.5.0/defaults/cm.yaml
Re-enable RBAC proxy on `kube-prometheus-stack` deployed `prometheus-node-exporter`.
https://jira.nutanix.com/browse/NCN-104587
Tested manually on daily.
```release-note
```
**Checklist**
> fix: enable rbac proxy on kube-prometheus-stack node-exporter

- services/ai-navigator-app/0.2.8/defaults/cm.yaml
- services/ai-navigator-app/0.2.8/helmrelease/helmrelease.yaml
Upgrade the AI Navigator Cluster Info API to `0.2.8`, which includes a proper fix for the postgres migration issue.
https://jira.nutanix.com/browse/NCN-104562
```release-note
```
**Checklist**
> feat: Bump AI Navigator chart to v0.2.8

- licenses.d2iq.yaml
- services/README.md
- services/velero/7.2.2/defaults/cm.yaml
Bump version v1.11.0
pkg:docker/velero/velero-plugin-for-aws@v1.10.1
trivy image docker.io/velero/velero-plugin-for-aws:v1.11.0
2024-11-19T14:01:03+05:30       INFO    [vuln] Vulnerability scanning is enabled
2024-11-19T14:01:03+05:30       INFO    [secret] Secret scanning is enabled
2024-11-19T14:01:03+05:30       INFO    [secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-11-19T14:01:03+05:30       INFO    [secret] Please see also https://aquasecurity.github.io/trivy/v0.57/docs/scanner/secret#recommendation for faster secret detection
2024-11-19T14:01:06+05:30       INFO    Number of language-specific files       num=2
2024-11-19T14:01:06+05:30       INFO    [gobinary] …
> feat: bump velero v1.11.0

- apptests/testdata/cert-manager/acme-setup/deploy-ingress-nginx-v1.10.0.yaml
- licenses.d2iq.yaml
- services/kube-prometheus-stack/65.5.0/defaults/cm.yaml
Bumps webhook certgen version to 1.4.4
https://jira.nutanix.com/browse/NCN-104606
arvinder.pal@GHH4XN27GC kommander-applications % git checkout webhook-certgen-1.4.4
branch 'webhook-certgen-1.4.4' set up to track 'origin/webhook-certgen-1.4.4'.
Switched to a new branch 'webhook-certgen-1.4.4'
arvinder.pal@GHH4XN27GC kommander-applications % trivy i registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.4
2024-12-10T18:28:30+05:30	INFO	[db] Need to update DB
2024-12-10T18:28:30+05:30	INFO	[db] Downloading DB...	repository="ghcr.io/aquasecurity/trivy-db:2"
57.28 MiB / 57.28 MiB [-----------------------------------------------------------------------] 100.00% 3.17 MiB p/s 18s …
> feat: Bump kube-webhook-certgen to 1.4.4

- licenses.d2iq.yaml
Bumps kube-rbac-proxy version to 0.18.2
https://jira.nutanix.com/browse/NCN-104608
> feat: kube-rbac-proxy bump to 0.18.2

- .exclude-airgapped
- common/helm-repositories/kustomization.yaml
- common/helm-repositories/mesosphere-repos.yaml
- common/helm-repositories/nkp-pulse-repos.yaml
- justfile
NKP-Pulse shouldn't be included in air-gapped builds (similar to AI-Navigator).
This PR follows up on #2957 to exclude NKP-Pulse from airgapped builds.
https://jira.nutanix.com/browse/NCN-103329
Corresponding PRs:
- https://github.com/mesosphere/kommander/pull/5379
```release-note
```
**Checklist**
> chore: Exclude NKP-Pulse from Airgapped builds.

- .bloodhound.yml
bumping 1.32.0 in commander-application for checking incompatible resources
https://jira.nutanix.com/browse/NCN-103535
> feat: bump bloodhound to validate against 1.32.0

- services/cert-manager/metadata.yaml
- services/external-dns/metadata.yaml
- services/fluent-bit/metadata.yaml
- services/gatekeeper/metadata.yaml
- services/grafana-logging/metadata.yaml
- services/grafana-loki/metadata.yaml
- services/istio/metadata.yaml
- services/jaeger/metadata.yaml
- services/kiali/metadata.yaml
- services/kube-oidc-proxy/metadata.yaml
- services/kube-prometheus-stack/metadata.yaml
- services/kubecost/metadata.yaml
- services/kubernetes-dashboard/metadata.yaml
- services/logging-operator/metadata.yaml
- services/nkp-insights/metadata.yaml
- services/nvidia-gpu-operator/metadata.yaml
- services/project-grafana-logging/metadata.yaml
- services/project-grafana-loki/metadata.yaml
- services/project-logging/metadata.yaml
- services/prometheus-adapter/metadata.yaml
- services/reloader/metadata.yaml
- services/rook-ceph-cluster/metadata.yaml
- services/rook-ceph/metadata.yaml
- services/traefik-forward-auth/metadata.yaml
- services/traefik/metadata.yaml
- services/velero/metadata.yaml
Kubecost is now a platform application.
Certified should be removed.
Supported should be replaced with Qualified.
Requested changes for 2.14:
- Certified badges will be removed in the UI
- Supported -> Qualified for third-party apps
- Nutanix apps should keep supported ( I think we only have nkp insights here but let me know if I missed any)
- Partner applications should not be used. Kubecost should become a platform application due to this.
https://jira.nutanix.com/browse/NCN-104856
```release-note
Kubecost has been updated to a platform application. 
The term "Certified" has been removed. 
The term "Supported" has been …
```
> feat: updated app metadata

- hack/list-images.sh
- licenses.d2iq.yaml
list-images.sh skips Cronjob images
https://jira.nutanix.com/browse/NCN-105004
tested running the script and saw the missing `docker.io/bitnami/kubectl:1.29.6` image
```release-note
```
**Checklist**
> fix: list image shell missing cronjob

- services/kubernetes-dashboard/7.10.0/defaults/cm.yaml
k8s dashboard doesn't start when ipv6 is disabled
https://jira.nutanix.com/browse/NCN-105116
```release-note
```
**Checklist**
> fix: ensure ipv4 for kong

- licenses.d2iq.yaml
- services/kommander/0.14.0/defaults/cm.yaml
- services/kubecost/2.5.0/cosi-storage/cosi-bucket.yaml
- services/kubecost/2.5.0/cosi-storage/extra-images.txt
- services/kubecost/2.5.0/cosi-storage/kustomization.yaml
- services/kubecost/2.5.0/cosi-storage/object-store-check.yaml
- services/kubecost/2.5.0/defaults/cm.yaml
- services/kubecost/2.5.0/pre-install.yaml
- services/kubecost/2.5.0/pre-install/pre-install-jobs.yaml
- services/kubecost/2.5.0/release.yaml
- services/kubecost/2.5.0/release/extra-images.txt
- services/kubecost/2.5.0/release/release.yaml
Follow up of #2959
Refactors the kubecost manifest to always depend on cosi. Adds a dashboard CM as well as some code cleanup.
```release-note
```
**Checklist**
> refactor: always have a dependency against COSI for kubecost

- services/harbor/1.16.0/database.yaml
- services/harbor/1.16.0/database/cluster.yaml
- services/harbor/1.16.0/database/kustomization.yaml
- services/harbor/1.16.0/defaults/database.yaml
- services/harbor/1.16.0/defaults/harbor.yaml
- services/harbor/1.16.0/kustomization.yaml
- services/harbor/1.16.0/release/kustomization.yaml
Tested by manually enabling `cloudnative-pg` app and `harbor` app.
> feat: Add HA harbor database

- services/harbor/1.16.0/pre-install/pre-install-jobs.yaml
Harbor helm chart does not adequately URL escape special characters in redis (valkey) password leading to harbor core not being able to connect to redis. This PR limits the characters usable for password generation so the connection URLs are guaranteed to be valid.
> fix: Use only alphanumeric characters for harbor valkey password

- services/cloudnative-pg/0.23.0/defaults/cm.yaml
- services/harbor/1.16.0/defaults/database.yaml
- configure CloudNativePG Operator to pass labels used by NKP Prom instance to select monitors
- enable monitoring on harbor databases
> feat: add monitoring to cnpg and default harbor db

- services/harbor/1.16.0/defaults/database.yaml
we need a second labels to add the harbor db prometheusrules to our prom instance
> feat: add prom rules for harbor deployed cluster

- services/cloudnative-pg/metadata.yaml
- services/harbor/metadata.yaml
Third-party applications should use 'qualified' instead of 'supported'.
Supported is now reserved for Nutanix supported apps - NKP Insights, NAI, etc. 
https://jira.nutanix.com/browse/NCN-105258
```release-note
CloudNativePG and Harbor applications will have a qualified badge and not a certified badge.
```
**Checklist**
> fix: third-party apps should use the qualified certification

- apptests/appscenarios/kubecost_test.go
- services/kubecost/2.5.2/defaults/cm.yaml
- services/kubecost/2.5.2/release/release.yaml
```release-note
```
**Checklist**
> feat: consume centralized-grafana in primary kubecost

- services/istio/metadata.yaml
- services/jaeger/metadata.yaml
- services/kiali/metadata.yaml
Istio, Jaeger, and Kiali are available in airgapped environments.
Link to discussion - https://nutanix.slack.com/archives/C068HGFS19B/p1737181472843889
https://jira.nutanix.com/browse/NCN-105312
```release-note
Istio, Jaeger, and Kiali will have a badge indicating they are available in airgapped environments.
```
**Checklist**
> fix: add airgapped certification to istio, jaeger, and kiali

- hack/list-images.sh
the gojq line that parse git operator patch image was missing the append
```release-note
```
**Checklist**
> fix: add the missing append

- services/kubecost/2.5.2/cosi-storage/cosi-bucket.yaml
- services/kubecost/2.5.2/defaults/cm.yaml
Bumps cosi-bucket-kit chart consumed by kubecost to latest version
```release-note
```
**Checklist**
> chore: bump cosi-bucket-kit chart

- services/harbor/1.16.0/cosi-storage.yaml
- services/harbor/1.16.0/cosi-storage/cosi-bucket.yaml
- services/harbor/1.16.0/cosi-storage/kustomization.yaml
- services/harbor/1.16.0/defaults/harbor.yaml
- services/harbor/1.16.0/kustomization.yaml
- services/harbor/1.16.0/pre-install/secrets.yaml
- services/harbor/1.16.0/release/harbor.yaml
Depends on https://github.com/mesosphere/charts/pull/1544
https://jira.nutanix.com/browse/NCN-105274
```release-note
```
**Checklist**
> feat: add harbor cosi hr

- licenses.d2iq.yaml
- services/cosi-driver-nutanix/0.0.4/defaults/cm.yaml
- services/cosi-driver-nutanix/0.0.4/extra-images.txt
- services/rook-ceph-cluster/1.16.2/defaults/cm.yaml
- services/rook-ceph-cluster/1.16.2/objectbucketclaims/extra-images.txt
See the warning at https://console.cloud.google.com/gcr/images/k8s-staging-sig-storage/GLOBAL/objectstorage-controller:v20221027-v0.1.1-8-g300019f/details 
> Container Registry is deprecated and scheduled for shutdown. Artifact Registry now [hosts images for the gcr.io domain by default ](https://cloud.google.com/artifact-registry/docs/transition/gcr-on-ar) in projects without previous Container Registry usage. After March 18, 2025, Container Registry will be shut down. To learn more about your options to upgrade to Artifact Registry, see Prepare for Container Registry shutdown.
Depends on https://github.com/mesosphere/dkp-container-images/pull/14 
The nutanix cosi app now bundles the cosi controller image. (this is used by kommander airgapped kind …
> feat: use ghcr.io/mesosphere images for cosi

- licenses.d2iq.yaml
- services/cosi-driver-nutanix/0.0.4/defaults/cm.yaml
- services/cosi-driver-nutanix/0.0.4/extra-images.txt
- services/rook-ceph-cluster/1.16.2/defaults/cm.yaml
- services/rook-ceph-cluster/1.16.2/objectbucketclaims/extra-images.txt
This reverts commit 5035c4e50d6b7c64c25a5182ecdaf691b3d420da.
The new images broke some of the kubecost tests. I will get to debugging the faiures later, but temporarily reverting to upstream images meanwhile.
```release-note
```
**Checklist**
> revert: feat: use ghcr.io/mesosphere images for cosi (#3058)

- services/kubecost/2.5.2/defaults/cm.yaml
Adding back the stripprefixes middleware to kubecost ingress that was removed in #3018 
```release-note
```
**Checklist**
> chore: update kubecost ingress middleware

- services/nvidia-gpu-operator/metadata.yaml
chore: move gpu operator app to general category
https://jira.nutanix.com/browse/NCN-105439
> chore: move gpu operator app to general category

- licenses.d2iq.yaml
- services/kube-oidc-proxy/0.3.5/defaults/cm.yaml
Upgrades the following apps to use version 1.0.7 to 1.0.9
* kube-oidc-procy from version  1.0.7 to 1.0.9
> feat: bump kube-oidc-proxy 1.0.9

- licenses.d2iq.yaml
- services/kube-prometheus-stack/67.6.0/defaults/cm.yaml
- services/kubecost/2.5.2/defaults/cm.yaml
Upgrades the following apps to use version alert-manager to v0.28.0:
* alert-manager to v0.28.0
> feat: update the alert-manager to v0.28.0

- licenses.d2iq.yaml
- services/nvidia-gpu-operator/24.9.2/defaults/cm.yaml
Upgrades the following apps to use version 3.6.1 to 4.0.1
* dcgm-exporter from version 3.6.1 to 4.0.1
> feat: bump new version dcgm-exporter:4.0.0-4.0.1-ubuntu22.04

- services/rook-ceph-cluster/1.16.2/defaults/cm.yaml
- services/rook-ceph-cluster/1.16.2/objectbucketclaims/cosi-bucket.yaml
Insights requires ceph cosi driver on workload clusters. This change updates ceph config to always default to installing ceph cosi driver.
```release-note
```
**Checklist**
> feat: install ceph cosi on attached clusters

- services/cosi-driver-nutanix/0.0.4/cosi-driver-nutanix.yaml
fetching changes from https://github.com/mesosphere/charts/pull/1547 to avoid Conflicts with ClusterRole resource created by ceph driver.
```release-note
```
**Checklist**
> chore: bump cosi-driver-nutanix helm chart

- services/cosi-driver-nutanix/metadata.yaml
- services/harbor/metadata.yaml
The category and the dependency field of metadata yaml of the cosi driver nutanix app and harbor app was set to empty array. However, we do not need dependency fields for either of the app and category needs to be general. Hence removing dependency field and adding category.
Slack Discussion Thread :- https://nutanix.slack.com/archives/C06A78Y063B/p1738775586636359?thread_ts=1738773226.964009&cid=C06A78Y063B
https://jira.nutanix.com/browse/NCN-105574
```release-note
```
**Checklist**
> fix: update cosi & harbor metadata fields

- services/ai-navigator-app/metadata.yaml
- services/ai-navigator-cluster-info-agent/metadata.yaml
- services/knative/metadata.yaml
We are missing certifications for Knative and AI Navigator apps.
Confirmed with product what these should be. 
https://jira.nutanix.com/browse/NCN-105577
```release-note
Knative application will display a Nutanix Qualified and Air-Gapped badge. AI Navigator applications will display a Nutanix Supported badge.
```
**Checklist**
> fix: missing certifications for knative and ai navigator apps

- services/traefik/34.1.0/defaults/traefik.yaml
This allows for pushing of large blobs to image registry which would
otherwise timeout.
> feat(traefik): Increase default registry entrypoint read timeout

- services/cloudnative-pg/metadata.yaml
The metadata yaml file for cloudnative-pg app has dependencies and category fields set to an empty array. The dependency field should be removed and category should be set as "general" if it is not categorized. 
Setting dependencies field as empty array [], causes UI to render empty name (see screenshot in the [ticket](https://jira.nutanix.com/browse/NCN-105607)), a bug in kommander-ui which is being tracked [here](https://jira.nutanix.com/browse/NCN-105575) . 
For now, as we do for all other k-apps metadata, if the cloudnative-pg app has no dependencies it can be safely removed from the metadata yaml file. 
https://jira.nutanix.com/browse/NCN-105607
**Does this PR introduce a …
> chore: update cloudnative-pg metadata

- services/traefik/34.1.0/crds/crds.yaml
Add an optionnal overrides for the traefik-crds helm chart to be able to deploy additional crd if needed
> fix: allow traefik-crds helmrelease overrides

- services/cosi-driver-nutanix/metadata.yaml
This PR addresses a FNF UI issue where the styling of cosi-driver-nutanix app paragraphs in overview section was inconsistent with what we show for others apps.
https://jira.nutanix.com/browse/NCN-105664
```release-note
```
**Checklist**
> chore: update cosi-driver-nutanix overview metadata

- services/cosi-driver-nutanix/0.0.4/cosi-resources-nutanix.yaml
- services/kubecost/2.5.2/cosi-storage/cosi-bucket.yaml
- services/rook-ceph-cluster/1.16.2/objectbucketclaims/cosi-bucket.yaml
Bumping the cosi-bucket-kit chart to the latest version and be consistent across all apps.
```release-note
```
**Checklist**
> chore: bump to latest cosi-bucket-kit

- services/kubecost/metadata.yaml
currently kubecost metadata overview doesn't include kubecost v2 breaking change
https://jira.nutanix.com/browse/NCN-105479
```release-note
```
**Checklist**
> docs: highlights kubecost v2 breaking change

- services/cloudnative-pg/0.23.0/defaults/cm.yaml
- services/kubecost/2.5.2/defaults/cm.yaml
- harbor has critical priority so cloudnative-pg gets the same priority.
- kubecost has always been at high priority.
https://jira.nutanix.com/browse/NCN-105638
https://jira.nutanix.com/browse/NCN-105641
```release-note
```
**Checklist**
> chore: add priorityclass for new pods

- licenses.d2iq.yaml
- services/cosi-driver-nutanix/0.2.0/defaults/cm.yaml
- services/rook-ceph-cluster/1.16.2/defaults/cm.yaml
- services/rook-ceph-cluster/1.16.2/objectbucketclaims/extra-images.txt
Fresh release - https://github.com/kubernetes-sigs/container-object-storage-interface/releases/tag/v0.2.1
Bumps cosi sidecar image to latest version (moves off of the deprecated gcr.io container registry). I made sure the new image does not add any new vulns:
Fixes https://jira.nutanix.com/browse/NCN-105729
Partially addresses https://jira.nutanix.com/browse/NCN-105713
```release-note
```
**Checklist**
> feat(cosi): bump cosi sidecar to v0.2.1

- services/cosi-driver-nutanix/0.2.0/cosi-driver-nutanix.yaml
currently cosi driver deployment doesnt auto restart after config secret change on UI
https://jira.nutanix.com/browse/NCN-105746
```release-note
```
**Checklist**
> fix: add reloader annotation to cosi driver

- devbox.lock
devbox.lock file is updated on `main` by latest version of devbox. This change commits the new devbox.lock file to make sure CI doesn't fail cuz of the diff.
```release-note
```
**Checklist**
> ci: update `devbox.lock` file 

- services/harbor/1.16.2/defaults/harbor.yaml
Disables ipv6 in harbor config.
Context - https://nutanix.slack.com/archives/C06A78Y063B/p1739827439361349?thread_ts=1739823742.885869&cid=C06A78Y063B
I cleaned up some duplicate keys in harbor config.
https://jira.nutanix.com/browse/NCN-105780
```release-note
```
**Checklist**
> fix: disable ipv6 in harbor config 

- licenses.d2iq.yaml
- services/cosi-driver-nutanix/0.2.0/defaults/cm.yaml
- services/cosi-driver-nutanix/0.2.0/extra-images.txt
`cosi-driver-nutanix` allows to install cosi controller image but this image is not added in licenses manifest. This is disabled by default and is handled by konvoy but I am adding it here for completeness (and also to make e2e tests easy on non konvoy clusters).
```release-note
```
**Checklist**
> build: add cosi controller image

- services/kubecost/2.5.2/defaults/cm.yaml
Adjusting the kubectl image to be consistent with what we add in the bundle https://github.com/mesosphere/kommander-applications/blob/release-2.14/licenses.d2iq.yaml#L524-L528 
```release-note
```
**Checklist**
> chore: make the kubectl image tag consistent

- services/kube-prometheus-stack/69.1.2/defaults/cm.yaml
- services/nvidia-gpu-operator/24.9.2/defaults/cm.yaml
Nvidia gpu metrics scrapping who don’t work out of the box
i don't know why but this is configured to collect metrics against node IP despite dcgmExporter running in pod network space
i move config from static kube-prometheus-stack target config to a more dynamic approach using the GPU Operator to create a proper servicemonitor ressource
> fix: GPU metrics scraping

- licenses.d2iq.yaml
- services/dex/2.14.1/defaults/cm.yaml
Bumping dex to include a11y changes and some other recent theme changes
https://github.com/mesosphere/dex/tree/refs/tags/v2.41.1-d2iq.2
n/a
solely bumping dex image
n/a - ui changes
**Checklist**
> chore: bumping dex image

- services/cosi-driver-nutanix/0.3.0/cosi-resources-nutanix.yaml
- services/harbor/1.16.2/cosi-storage/cosi-bucket.yaml
- services/kubecost/2.5.2/cosi-storage/cosi-bucket.yaml
- services/rook-ceph-cluster/1.16.2/objectbucketclaims/cosi-bucket.yaml
Pulling changes from https://github.com/mesosphere/charts/pull/1562 
https://jira.nutanix.com/browse/NCN-105904
```release-note
```
**Checklist**
> chore: bump cosi-bucket-kit chart to 0.0.5

- services/kubecost/2.5.2/defaults/cm.yaml
looks like current 128G is good for :
> This configuration is estimated to be sufficient for environments monitoring < 60k unique containers per day. You can check this metric on the /diagnostics page.
https://docs.kubecost.com/install-and-configure/install/multi-cluster/federated-etl/aggregator#aggregator-optimizations
looking at the soak cluster [https://dkp214.ksphere-soak.d2iq.cloud/dkp/kommander/monitoring/grafana/d/919b92a8e8041bd567[…]gregator-db-storage-kubecost-aggregator-0&refresh=10s](https://dkp214.ksphere-soak.d2iq.cloud/dkp/kommander/monitoring/grafana/d/919b92a8e8041bd567af9edab12c840c/kubernetes-persistent-volumes?orgId=1&from=now-1h&to=now&timezone=utc&var-datasource=default&var-cluster=18fb9f52-da44-433d-8486-fcbc5e113df8&var-namespac …
> chore: decrease kubecost aggregator default storage

- licenses.d2iq.yaml
- services/nvidia-gpu-operator/24.9.2/defaults/cm.yaml
- services/nvidia-gpu-operator/24.9.2/grafana-dashboards/gpu-operator.json
https://jira.nutanix.com/browse/NCN-105855
```release-note
```
**Checklist**
> fix: revert dcgm-export to helm chart default value

- .exclude-airgapped
- .github/service-labeler.yaml
- common/helm-repositories/kustomization.yaml
- common/helm-repositories/nkp-pulse-repos.yaml
- justfile
- licenses.d2iq.yaml
- services/kommander/0.15.0/defaults/cm.yaml
- services/nkp-pulse-management/0.0.1-dev.0/defaults/cm.yaml
- services/nkp-pulse-management/0.0.1-dev.0/defaults/kustomization.yaml
- services/nkp-pulse-management/0.0.1-dev.0/helmrelease.yaml
- services/nkp-pulse-management/0.0.1-dev.0/kustomization.yaml
- services/nkp-pulse-management/metadata.yaml
- services/nkp-pulse-workspace/0.0.1-dev.0/defaults/cm.yaml
- services/nkp-pulse-workspace/0.0.1-dev.0/defaults/kustomization.yaml
- services/nkp-pulse-workspace/0.0.1-dev.0/helmrelease.yaml
- services/nkp-pulse-workspace/0.0.1-dev.0/kustomization.yaml
- services/nkp-pulse-workspace/metadata.yaml
Revert PR #3076 via commit b0d160e9eaaca85ca79e3be5546bcd3bd5c4f2fa and re-add NKP-Pulse to k-apps.
We can then land the latest version via #3223 which will merge into this.
```release-note
```
**Checklist**
> chore: Re-add NKP Pulse for NKP 2.15 release.

- apptests/appscenarios/contants.go
- common/build/list-images-values.yaml
- licenses.d2iq.yaml
- services/ai-navigator-app/0.2.10/defaults/cm.yaml
- services/cosi-driver-nutanix/0.4.0/defaults/cm.yaml
- services/dex/2.14.1/defaults/cm.yaml
- services/git-operator/0.1.4/git-operator-manifests/all.yaml
- services/git-operator/0.1.4/kustomization.yaml
- services/grafana-loki/0.79.5/grafana-loki-pre-install-jobs/pre-install.yaml
- services/harbor/1.16.2/defaults/harbor.yaml
- services/harbor/1.16.2/pre-install/pre-install-jobs.yaml
- services/istio/1.23.3/defaults/cm.yaml
- services/knative/1.17.0/defaults/cm.yaml
- services/kommander/0.15.0/dynamic-helmreleases/cluster-observer/list-images-values.yaml
- services/kube-prometheus-stack/69.1.2/defaults/cm.yaml
- services/kubecost/2.5.2/defaults/cm.yaml
- services/kubecost/2.5.2/pre-install/pre-install-jobs.yaml
- services/kubefed/0.11.1/defaults/cm.yaml
- services/kubetunnel/0.0.39/defaults/cm.yaml
- services/nkp-insights-management/1.4.4/defaults/cm.yaml
- services/nkp-insights/1.4.4/defaults/cm.yaml
- services/project-grafana-loki/0.79.5/defaults/cm.yaml
- services/rook-ceph-cluster/1.16.2/defaults/cm.yaml
- services/rook-ceph-cluster/1.16.2/pre-install/ceph-crd-check.yaml
- services/thanos/15.7.24/jobs/jobs.yaml
- services/velero/8.3.0/defaults/cm.yaml
- services/velero/8.3.0/velero-pre-install.yaml
bump kubectl version to 1.32.2
https://jira.nutanix.com/browse/NCN-105854
```release-note
```
**Checklist**
> feat: bump kubectl version to 1.32.2

- services/cosi-driver-nutanix/metadata.yaml
The "Essential" license is misspelled as "Essentials" in the `cosi-driver-nutanix` app's metadata YAML file. This typo needs correction.
https://jira.nutanix.com/browse/NCN-106024
```release-note
```
**Checklist**
> chore: update cosi licensing metadata

- .bloodhound.yml
bump the k8s 1.30 to latest patch 1.30.10
**release 2.13.2**
https://jira.nutanix.com/browse/NCN-105973
```release-note
```
**Checklist**
> feat: bump the k8s 1.30 to latest patch

- upgrade-matrix.yaml
Post-release bumps are PRs created by [gh-dkp](https://github.com/mesosphere/gh-dkp/)
to adjust repositories after releases.
> chore: Post release bumps

- apptests/appscenarios/contants.go
- common/build/list-images-values.yaml
- licenses.d2iq.yaml
- services/ai-navigator-app/0.2.8/defaults/cm.yaml
- services/centralized-kubecost/0.37.7/defaults/cm.yaml
- services/centralized-kubecost/0.37.7/post-install-jobs/post-install-jobs.yaml
- services/centralized-kubecost/0.37.7/release/release.yaml
- services/dex/2.14.0/defaults/cm.yaml
- services/git-operator/0.1.2/kustomization.yaml
- services/grafana-loki/0.79.5/grafana-loki-pre-install-jobs/pre-install.yaml
- services/istio/1.23.3/defaults/cm.yaml
- services/knative/1.15.5/defaults/cm.yaml
- services/kommander/0.13.2/dynamic-helmreleases/cluster-observer/list-images-values.yaml
- services/kube-prometheus-stack/65.5.0/defaults/cm.yaml
- services/kubecost/0.37.8/defaults/cm.yaml
- services/kubefed/0.10.5/defaults/cm.yaml
- services/kubetunnel/0.0.38/defaults/cm.yaml
- services/nkp-insights-management/1.3.4/defaults/cm.yaml
- services/nkp-insights/1.3.4/defaults/cm.yaml
- services/project-grafana-loki/0.79.5/defaults/cm.yaml
- services/rook-ceph-cluster/1.14.5/defaults/cm.yaml
- services/rook-ceph-cluster/1.14.5/pre-install/ceph-crd-check.yaml
- services/thanos/15.7.23/jobs/jobs.yaml
- services/traefik/27.0.3/defaults/cm.yaml
- services/velero/7.2.2/defaults/cm.yaml
- services/velero/7.2.2/velero-pre-install.yaml
bump kubectl version to 1.30.7
` docker pull bitnami/kubectl:1.30.7                            
1.30.7: Pulling from bitnami/kubectl
Digest: sha256:1249fc292e84a38575ee0cadc3e28dcd7ddf5a3a4e5da401b1a8599e8ac52a1b
Status: Image is up to date for bitnami/kubectl:1.30.7
docker.io/bitnami/kubectl:1.30.7
`
```release-note
```
**Checklist**
> feat: bump kubectl version to 1.30.7

- hack/flux/flux-update-kustomization.yaml
- services/kommander-flux/2.4.0/templates/v1_namespace_kommander-flux.yaml
Whenever the `flux-configuration` `Kustomization` in `kommander` namespace is reconciled, we overwrite any user given labels on flux namespace. This breaks proxied environments cuz our docs currently ask user to label flux namespace manually. We should fix this manual ask from the user in long run but until then, we should use `merge` strategy in flux ssa. 
I am not bumping the flux component version here cuz this change is only limited to adding an annotation on namespace and does not cause any restarts or such.
This was first added in https://github.com/fluxcd/kustomize-controller/blob/main/CHANGELOG.md#0220 so we can safely backport it all way back to 2.8.x (which uses a 1.x.y version of kustomize-controller) …
> fix: preserve user labels on flux ns during upgrades

- licenses.d2iq.yaml
- services/fluent-bit/0.43.1/defaults/cm.yaml
- services/logging-operator/4.2.5/defaults/cm.yaml
Use docker directly to pull fluentbit images.
backport of https://github.com/mesosphere/kommander-applications/pull/3142
```release-note
```
**Checklist**
> fix: use fluentbit image from dockerhub (#3142)

- services/thanos/15.7.24/defaults/cm.yaml
At some point, new resource presets field was introduced and set to "nano" by default
```
"nano" (dict 
"requests" (dict "cpu" "100m" "memory" "128Mi" "ephemeral-storage" "50Mi")
"limits" (dict "cpu" "150m" "memory" "192Mi" "ephemeral-storage" "2Gi")
)
```
https://github.com/bitnami/charts/blob/bbe546947f67cd71da25fafbf7920b888b93e8cd/bitnami/thanos/values.yaml#L265-L281
These presets are not meant to be used in production and we should be setting our own resource values.
https://github.com/bitnami/charts/blob/52607faf0d32ed0c7741b0fc224863596fcdc271/bitnami/common/templates/_resources.tpl#L28-L31
Looking at the usage in the ticket and also at the presets, I think we can go with the "medium" values, which I have used for our default resources config …
> fix(thanos): Set resources

- charts/kommander-operator/Chart.yaml
Bumping the kommander-operator chart before renaming it to have the `-chart` suffix.
```release-note
```
**Checklist**
> chore: bump kommander operator version

- services/kube-prometheus-stack/48.3.3/defaults/cm.yaml
follow up to https://github.com/mesosphere/kommander-applications/pull/2624
https://github.com/prometheus-community/helm-charts/issues/3338
Was fixed in KPS 57.1.1 https://github.com/prometheus-community/helm-charts/pull/3946 which is higher than the version of KPS in 2.8, so manually adding the rule via default values.
After applying the rule, prometheus was able to access node metrics and error disappeared from UI
```release-note
```
**Checklist**
> fix(kps): Missing node-exporter rbac proxy rule

- .github/service-labeler.yaml
- apptests/appscenarios/ciliumhubblerelaytraefik.go
- apptests/appscenarios/ciliumhubblerelaytraefik_test.go
- apptests/constants/apps.go
- apptests/testdata/cilium-hubble-relay-traefik/hubble-relay-fake.yaml
- services/cilium-hubble-relay-traefik/0.0.3/cilium-hubble-relay-traefik.yaml
- services/cilium-hubble-relay-traefik/0.0.3/defaults/cm.yaml
- services/cilium-hubble-relay-traefik/0.0.3/defaults/kustomization.yaml
- services/cilium-hubble-relay-traefik/0.0.3/kustomization.yaml
- services/cilium-hubble-relay-traefik/metadata.yaml
- services/kommander/0.16.0/defaults/cm.yaml
This deploys the helm chart that configures a traefik route for the Cilium Hubble Relay service.
Adds an install apptest for the service, and an upgrade test that is skipped, for now, because no previous version of the service exists, and the upgrade test framework requires a previous version.
The install apptest verifies that the IngressRouteTCP created by cilium-hubble-relay-traefik does correctly route requests to the hubble-relay service with TLS passthrough. The test:
- Installs traefik and its dependencies
- Installs cilium-hubble-relay-traefik
- Runs an HTTPS server that presents a self-signed server cert with a specific CN.
- Routes the hubble-relay Service to that HTTPS server.
- Verifies that a request to traefik using the expected SNI is …
> feat: Introduce cilium-hubble-relay-traefik

- README.md
- hack/list-images.sh
- licenses.d2iq.yaml
Fixes issues occurring in Kommander E2E airgapped tests. NKP-Pulse isn't supported in air-gapped environments.
[Slack Thread](https://nutanix.slack.com/archives/C06AQ8T3AHW/p1744201209246309)
```release-note
```
**Checklist**
> fix: Exclude listing nkp-pulse images in airgapped bundle.

- services/kube-prometheus-stack/70.4.2/defaults/cm.yaml
Update KPS default config to allow more updates in parallel for node-exporter
https://jira.nutanix.com/browse/NCN-107037
```release-note
```
**Checklist**
> fix(kps): Update updateStrategy maxUnavailable to 25%

- services/kube-prometheus-stack/70.4.2/defaults/cm.yaml
Many customers have complained that after an upgrade, they have lost their custom Grafana dashboards or customized configurations. 
This PR enables persistence for the Grafana app using the default settings.
> feat: enable persistence for grafana

- apptests/appscenarios/appscenarios.go
- apptests/appscenarios/ciliumhubblerelaytraefik.go
- apptests/appscenarios/gatekeeper.go
- apptests/appscenarios/karma.go
- apptests/appscenarios/reloader.go
- apptests/appscenarios/suite_test.go
- apptests/appscenarios/traefik.go
adding methods to interface to be used by other modules
```release-note
```
**Checklist**
> refactor: Appscenerio interface add 2 new methods

- apptests/appscenarios/appscenarios.go
- apptests/appscenarios/certmanager.go
- apptests/appscenarios/ciliumhubblerelaytraefik.go
- apptests/appscenarios/externaldns.go
- apptests/appscenarios/gatekeeper.go
- apptests/appscenarios/karma.go
- apptests/appscenarios/kommanderflux.go
- apptests/appscenarios/kubecost.go
- apptests/appscenarios/reloader.go
- apptests/appscenarios/rookceph.go
- apptests/appscenarios/traefik.go
- apptests/appscenarios/velero.go
- apptests/scenarios/suite.go
Doing this allows us to use the interface in downstream catalog repositories.
```release-note
```
**Checklist**
> refactor: move AppScenarios interface into apptests module

- services/kommander/0.16.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
- services/kommander/0.16.0/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
- services/kommander/0.16.0/kustomization.yaml
- services/kommander/0.16.0/repository.yaml
- Previously, HelmRepository resources were defined separately from the application definitions. This change moves them into the same location as the applications they belong to, ensuring they are included in the same kustomization. This improves maintainability, modularity, and clarity in resource ownership and deployment flow.
- https://jira.nutanix.com/browse/NCN-105538
- This application is one of the applications that has been migrated. After the successful completion of this migration, the remaining applications will be moved. 
- No
> refactor: Migrate helm repository definition closer to service

- services/kube-prometheus-stack/70.4.2/defaults/cm.yaml
https://jira.nutanix.com/browse/NCN-107084
https://jira.nutanix.com/browse/NCN-107085
Metrics like machine_cert_expiry_days and rollout_trigger_days_before_cert_expiry are exposed by extending kube-state-metrics via the customResourceState config.
Alerting Rules Implemented:
CertificateExpiringSoon: Triggers when certificate expiry is within 1 and 7 days
CertificateRollingOutSoon: Triggers if expiry is exactly 1 day away and rollout threshold is met.
CertificateRolledOut: Triggers when the certificate is successfully renewed (e.g., 365 days left).
CertificateExpired: Triggers if expiry date has passed (i.e., less than 0 days remaining).
> feat: Extend Kubestate metrics for CRDs and custom prometheus rules

- services/nkp-insights/1.4.4/metadata.yaml
Allow installing NKP Insights without Rook Ceph.
https://jira.nutanix.com/browse/NCN-107416
```release-note
```
**Checklist**
> fix: Remove Rook Ceph from required dependencies for Insights

- services/kommander/0.15.0/defaults/cm.yaml
`deploy/kommander-licensing-cm ` is failiing in airgapped environments with the following error:
```
2025-05-06T05:52:00.787Z	ERROR	controllers.LicenseProAppDeployment	Reconciler error	{"reconcileID": "7fba97b1-dd1e-417c-ae7d-b2761b13d80c", "error": "unable to get latest version of app ai-navigator-app: no ClusterApps found for app ai-navigator-app"}
```
This is because ai-navigator-app is excluded in airgapped artifacts. As an interim fix for 2.15, we can move it down the list so that other apps are deployed and then the controller will fail on the last app. This has been the behavior since 2.12.0 - https://github.com/mesosphere/kommander-applications/blob/v2.12.0/services/kommander/0.12.0/defaults/cm.yaml#L80
This is an interim fix for 2.15 and we …
> refactor: reorder defaultProApps to deploy ai navigator towards the end.

- services/kommander/0.16.0/defaults/cm.yaml
ports https://github.com/mesosphere/kommander-applications/pull/3495
https://jira.nutanix.com/browse/NCN-107450
```release-note
```
**Checklist**
> refactor: reorder defaultProApps to deploy ai nav towards the end

- charts/kommander-operator/templates/deployment.yaml
- charts/kommander-operator/values.yaml
As of https://github.com/mesosphere/kommander/pull/5790 we are not going to use this feature flag anymore.
```release-note
```
**Checklist**
> chore: Remove unused feature flag

- services/kube-prometheus-stack/71.0.0/defaults/cm.yaml
https://jira.nutanix.com/browse/NCN-107084
machine_cert_expiry_days is exposed by extending kube-state-metrics using kubeadm config resource instead machine
> chore: Switch metric source from Machine to KubeadmConfig

- .github/workflows/automerge.yaml
- .github/workflows/backport.yaml
Don't use `pull_request_target` for GHA.
https://jira.nutanix.com/browse/NCN-107016
There are 2 workflows updates.
`automerge.yaml`: the `pull_request_target` trigger couldn't work properly as the token is missing the `pull-request: write` permission necessary for approving a PR.
`backport.yaml`: implication will be that it won't be possible to run backport action on PRs that are coming from a fork.
```release-note
```
**Checklist**
> fix: use pull_request target for GHA

- .bloodhound.yml
bump k8s 1.33.0 version to bloodhound
https://jira.nutanix.com/browse/NCN-106613
```release-note
```
**Checklist**
> feat: bump k8s 1.33.0 version to bloodhound

- services/kube-prometheus-stack/71.0.0/defaults/cm.yaml
Adds Rollout Might Fail metrics, incase rollout did not happen till rolloutBefore/2
https://jira.nutanix.com/browse/NCN-106656
> chore: Adds Rollout Might Fail state

- .bloodhound.yml
feat: bump the k8s 1.31 to latest patch 1.31.9
release 2.14.1
https://jira.nutanix.com/browse/NCN-107606
```release-note
```
**Checklist**
> feat: bump the k8s 1.31 to latest patch 1.31.9

- services/kommander-appmanagement/0.16.0/kommander-appmanagement.yaml
Kustomization fails on HR when we switch to OCI registry. Forcing HR solves the problem.
```release-note
```
**Checklist**
> fix: Force k appmanagement HR

- .github/service-labeler.yaml
- common/helm-repositories/external-secrets.yaml
- common/helm-repositories/kustomization.yaml
- licenses.d2iq.yaml
- services/external-secrets/0.17.0/defaults/cm.yaml
- services/external-secrets/0.17.0/defaults/kustomization.yaml
- services/external-secrets/0.17.0/external-secrets-namespace.yaml
- services/external-secrets/0.17.0/external-secrets-namespace/external-secrets.yaml
- services/external-secrets/0.17.0/kustomization.yaml
- services/external-secrets/0.17.0/metadata.yaml
- services/external-secrets/0.17.0/release.yaml
- services/external-secrets/0.17.0/release/kustomization.yaml
- services/external-secrets/0.17.0/release/release.yaml
- services/external-secrets/metadata.yaml
Adds external-secrets operator app
https://jira.nutanix.com/browse/NCN-107784
```release-note
```
**Checklist**
> feat: add external secrets operator app

- .github/workflows/release.yml
#3506 bumped the slack send message action which introduced some breaking changes (see https://github.com/slackapi/slack-github-action/issues/372#issuecomment-2518209779 )  in the action config.
https://github.com/slackapi/slack-github-action/blob/v2.1.0/action.yml#L37-L42
Fixes this error:
https://github.com/mesosphere/kommander-applications/actions/runs/15615724298/job/44018612388
```
Run slackapi/slack-github-action@v2.1.0
Error: Missing input! The webhook type must be 'incoming-webhook' or 'webhook-trigger'.
SlackError: Missing input! The webhook type must be 'incoming-webhook' or 'webhook-trigger'.
at Config.validate (file:///runner/_work/_actions/slackapi/slack-github-action/v2.1.0/src/config.js:177:1)
at …
```
> ci: use new slack webhook config

- applications/rook-ceph-cluster/1.17.5/pre-install.yaml
- applications/rook-ceph-cluster/1.17.5/pre-install/ceph-crd-check.yaml
By using OCI repository the last attempted version now contains helm chart artifact SHA.
```
Ceph operator is at 1.17.5+82c0fb0fd927 version and desired version is v1.17.5. Continuing to wait...
```
This condition thus will never resolve correctly.
```release-note
```
**Checklist**
> fix: rook-ceph wait script for OCI repository version

- .bloodhound.yml
bump to 1.33.2
```release-note
```
**Checklist**
> feat: bump k8s to 1.33.2

- applications/cosi-driver-nutanix/0.6.0/cosi-driver-nutanix.yaml
- applications/cosi-driver-nutanix/0.6.0/cosi-resources-nutanix.yaml
What problem does this PR solve?:
bump cost-analyzer chart to 2.8.0
OCI migration of cosi-driver-nutanix
OCI migration of cosi-bucket-kit
Jira: https://jira.nutanix.com/browse/NCN-108249
Special notes for your reviewer:
Does this PR introduce a user-facing change?:
Checklist
If the PR adds a version bump, ensure there is no breaking change in Licensing model (or NA).
If a chart is changed or app configuration is significantly changed, the chart version is correctly incremented (so that apps are not automatically upgraded from a previous version of DKP).
> feat: update cosi-driver-nutanix to OCI

- applications/kube-oidc-proxy/0.3.6/kube-oidc-proxy.yaml
migrate kube-oidc-proxy to OCI
https://github.com/mesosphere/kommander-applications/pkgs/container/charts%2Fkube-oidc-proxy
```
sandhya.ravi@GT9X7CVF5F oci-ghcr % helm pull oci://ghcr.io/mesosphere/charts/kube-oidc-proxy:0.3.4                          
Pulled: ghcr.io/mesosphere/charts/kube-oidc-proxy:0.3.4
Digest: sha256:89112ff2b328423f56491d3f01e0b6d6ef0d1aa325ffa225c955cf80c76ba495
```
https://jira.nutanix.com/browse/NCN-108250
```release-note
```
**Checklist**
> refactor: migrate kube-oidc-proxy to OCI

- applications/knative/1.18.1/knative-deployment.yaml
- applications/knative/1.18.1/knative-operator.yaml
migrate knative chart to OCIRepository
helm pull oci://ghcr.io/mesosphere/charts/knative --version 1.18.1         
Pulled: ghcr.io/mesosphere/charts/knative:1.18.1
Digest: sha256:856d8966f8e9cc8dbd2b6d98f3f48c5564f001334c5a4b017222382345c81859
helm pull oci://ghcr.io/mesosphere/charts/knative-operator --version 1.18.1
Pulled: ghcr.io/mesosphere/charts/knative-operator:1.18.1
Digest: sha256:86c9ca011e1efc16addf631054b2ace29de7e79073834773436f28fdb5363ee3
https://jira.nutanix.com/browse/NCN-108194
> refactor: migrate knative chart to OCIRepository

- applications/traefik-forward-auth-mgmt/0.3.15/traefik-forward-auth-mgmt.yaml
- applications/traefik-forward-auth/0.3.15/traefik-forward-auth.yaml
OCi migration of traefik-forward-auth helm chart
```release-note
```
**Checklist**
> refactor: migrate traefik-forward-auth chart to OCIRepository

- applications/prometheus-thanos-traefik/0.0.3/prometheus-thanos-traefik.yaml
Migrate Prometheus thanos traefik to OCIRepository
helm pull oci://ghcr.io/mesosphere/charts/thanos-traefik --version 0.0.2
Pulled: ghcr.io/mesosphere/charts/thanos-traefik:0.0.2
Digest: sha256:41b11a92d6be909e974d60e3bc103f3d63ba715443673bb221ec47e787bcbbf6
https://jira.nutanix.com/browse/NCN-108423
> refactor: Migrate Prometheus thanos traefik to OCIRepository

- applications/chartmuseum/3.10.4/chartmuseum.yaml
chartmuseum oci migration
https://jira.nutanix.com/browse/NCN-108191
```release-note
```
**Checklist**
> refactor: chartmuseum oci migration

- applications/istio/1.23.4/helmrelease/helmrelease.yaml
Migrate istio to OCI
```
sandhya.ravi@GT9X7CVF5F istio-oci % helm pull oci://ghcr.io/mesosphere/charts/istio:1.23.3                 
Pulled: ghcr.io/mesosphere/charts/istio:1.23.3
Digest: sha256:4dfa13927768da39e2f2a5281b102bfa9d78b8176c5053f9cabaa24b4f3fdd50
```
https://jira.nutanix.com/browse/NCN-108452
```release-note
```
**Checklist**
> refactor: Migrate istio to OCI

- applications/kommander-flux/2.6.1/kustomization.yaml
- applications/kommander-flux/2.6.1/mirror/flux-oci-mirror.yaml
- applications/kommander-flux/2.6.1/mirror/kustomization.yaml
- apptests/appscenarios/kommanderflux_test.go
- apptests/environment/crds/cert-manager.crds.yaml
- apptests/environment/environment.go
- licenses.d2iq.yaml
Add new `flux-oci-mirror` deployment.
```release-note
```
**Checklist**
> feat: add flux oci mirror app

- applications/kubecost/2.7.3/cosi-storage/cosi-bucket.yaml
- applications/kubecost/2.7.3/release/release.yaml
- common/helm-repositories/kustomization.yaml
cost-analyzer helm chart oci migration
https://jira.nutanix.com/browse/NCN-108195
```release-note
```
**Checklist**
> refactor: migrate kubecost chart to OCIRepository

- applications/kommander/0.16.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
currently workspace upgrade encounters https://github.com/mesosphere/kommander-cli/actions/runs/16372808039/job/46265185838#step:12:5312
```release-note
```
**Checklist**
> fix: enable HR replacement on upgrade

- applications/nkp-insights-management/1.6.2/helmrelease/helmrelease.yaml
- applications/nkp-insights-management/1.6.2/helmrelease/kustomization.yaml
- applications/nkp-insights-management/1.6.2/helmrelease/ocirepository.yaml
- applications/nkp-insights/1.6.2/helmrelease/helmrelease.yaml
- applications/nkp-insights/1.6.2/helmrelease/kustomization.yaml
- applications/nkp-insights/1.6.2/helmrelease/ocirepository.yaml
Redo of #3756 
Split out contents of `OCIRepository` into its own file so that Insights' release tooling can easily apply new changes to separate files.
https://jira.nutanix.com/browse/NCN-108441
```release-note
```
**Checklist**
> chore: Split HelmRelease and OCIRepository in their own respective files

- applications/knative/1.18.1/knative-operator.yaml
Follow on to #3800 which addressed 26/28 of the previous issues.
However we still have the following failure when knative is deployed on the daily cluster v0.0.0-dev.0 build.
```
Warning  InstallFailed  56m   helm-controller  Helm install failed for release knative-operator/knative with chart knative-operator@1.18.1+86c9ca011e1e: 2 errors occurred:
* Deployment.apps "knative-operator" is invalid: spec.template.labels: Invalid value: "1.18.1+86c9ca011e1e": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
* Deployment.apps …
```
> fix: Add additional spec.template.labels patch

- applications/fluent-bit/0.50.0/defaults/cm.yaml
- licenses.d2iq.yaml
update fluent-bit to 4.0.5
```
bhargavreddy.hastava@J4R3KVQRXK kommander % trivy image docker.io/fluent/fluent-bit:4.0.5
2025-07-25T15:07:02+05:30	INFO	[vulndb] Need to update DB
2025-07-25T15:07:02+05:30	INFO	[vulndb] Downloading vulnerability DB...
2025-07-25T15:07:02+05:30	INFO	[vulndb] Downloading artifact...	repo="mirror.gcr.io/aquasec/trivy-db:2"
67.06 MiB / 67.06 MiB [-------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 6.00 MiB p/s 11s
2025-07-25T15:07:17+05:30	INFO	[vulndb] Artifact successfully downloaded	repo="mirror.gcr.io/aquasec/trivy-db:2"
2025-07-25T15:07:17+05:30	INFO	[vuln] Vulnerability scanning is enabled …
```
> feat: update fluent-bit to 4.0.5

- applications/harbor/1.17.1/defaults/valkey.yaml
- licenses.d2iq.yaml
update redis-exporter with bitnamilegacy
```
sandhya.ravi@GT9X7CVF5F charts % docker pull bitnamilegacy/redis-exporter:1.74.0-debian-12-r3
1.74.0-debian-12-r3: Pulling from bitnamilegacy/redis-exporter
dbf75f05c48e: Pull complete 
Digest: sha256:26d147a5cef36c1f0c3a9ab4ed0633d1318b233f09aa4e771a943beae3edede1
Status: Downloaded newer image for bitnamilegacy/redis-exporter:1.74.0-debian-12-r3
docker.io/bitnamilegacy/redis-exporter:1.74.0-debian-12-r3
```
https://jira.nutanix.com/browse/NCN-108757
```release-note
```
**Checklist**
> refactor: update redis-exporter with bitnamilegacy

- applications/kube-prometheus-stack/71.0.0/defaults/cm.yaml
- applications/kube-prometheus-stack/71.0.0/helmrelease/extra-images.txt
- licenses.d2iq.yaml
include prometheus/promethes:v3.3.0 image in license file  with v3.4.1, as few components (e.g., Kubecost, Grafana) might still reference to v3.3.0. 
https://jira.nutanix.com/browse/NCN-108800
```release-note
```
**Checklist**
> feat: add prometheus/promethes:v3.3.0

- applications/kommander/0.16.0/kommander.yaml
We have controllers in kommander that reconcile ESO resources, and other controllers that depend on ESO (creates ESO resources). When kommander comes up before ESO is deployed (ESO CRDs don't exist) we might see the kommander-cm pod crashloop. Even if it does not end up crashing, there are a lot of error logs in the controller until ESO is up.
```
2025-07-30T22:39:39.627Z	ERROR	controller-runtime.source.EventHandler	if kind is a CRD, it should be installed before calling Start	{"kind": "SecretStore.external-secrets.io", "error": "no matches for kind \"SecretStore\" in version \"external-secrets.io/v1\""}
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind[...]).Start.func1.1
sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/source/kind.go:71 …
```
> fix(kommander): Add external-secrets dependency

- applications/harbor/1.17.1/cosi-storage/cosi-bucket.yaml
- applications/kubecost/2.8.1/cosi-storage/cosi-bucket.yaml
cosi bucket kit chart is being reinstalled for 2 different versions:
```
Conditions:
Last Transition Time:  2025-08-04T09:14:44Z
Message:               stored artifact for digest '0.0.5@sha256:d4d9add4a45f28f2d0873f69d129e7c00332635950c2d1bead6cea40228c1125'
Observed Generation:   39
Reason:                Succeeded
Status:                True
Type:                  Ready
Last Transition Time:  2025-08-04T09:14:44Z
Message:               stored artifact for digest '0.0.5@sha256:d4d9add4a45f28f2d0873f69d129e7c00332635950c2d1bead6cea40228c1125'
Observed Generation:   39
Reason:                Succeeded
Status:                True
Type:                  ArtifactInStorage
Observed Generation:     39
URL: …
```
> fix: unique name for cosi bucket kit

- applications/kommander/0.16.0/kommander.yaml
Reverts #3828 and moves the prerequisite logic to https://github.com/mesosphere/kommander/pull/6294
https://jira.nutanix.com/browse/NCN-108855
```release-note
```
**Checklist**
> refactor: remove external-secrets dep for kommander

- applications/ai-navigator-rag/0.6.1/defaults/cm.yaml
Using `pullthrough.infra.nkp.sh` cause a failure when building images for [Kommmander GHA](https://github.com/mesosphere/kommander/actions/runs/16738046081/job/47380794785#step:13:827) 
Revert this addition which landed in #3841 
```release-note
```
**Checklist**
> fix: Remove pullthrough as registry path for ai-navigator-rag

- applications/nvidia-gpu-operator/25.3.1/helmrelease/extra-images.txt
- licenses.d2iq.yaml
For the Ubuntu OOTB OS, we need to add the nvidia precompiled drivers to the NKP airgap package. 
This will be required to allow NKP customers to use GPU workloads in airgap scenarios in combination with Ubuntu OOTB OS
https://jira.nutanix.com/browse/NCN-108862
```release-note
```
**Checklist**
> fix: NCN-108862 adds ubuntu prebuilt driver container for pro

- applications/centralized-grafana/71.0.1/defaults/cm.yaml
- applications/grafana-logging/8.15.2/defaults/cm.yaml
- applications/kube-prometheus-stack/71.0.1/defaults/cm.yaml
- applications/project-grafana-logging/8.15.2/defaults/cm.yaml
In airgapped clusters, grafana was failing to load plugins (new feature in grafana) and was essentially unusable.
ref https://github.com/grafana/grafana/issues/106871#issuecomment-3035054121 
Also in https://github.com/mesosphere/kommander-applications/commit/a9c1d9e6d64f05fea491e360ca079e422ab193a7 we removed piechart plugin, just cleaning up the unused field here
https://jira.nutanix.com/browse/NCN-108951
```release-note
```
**Checklist**
> fix(grafana): Disable preinstalled plugins

- applications/knative/1.18.1/defaults/cm.yaml
- applications/knative/1.18.1/extra-images.txt
- hack/knative/README.md
- hack/knative/extract-images.py
- licenses.d2iq.yaml
Update images for Knative
- Updated the images that are found in ENV variables and are defined in values.yaml configmaps as data string.
- Update the `queue-proxy` image. The cache image and has a [specific override](https://github.com/knative/operator/blob/8954073cb2affffdb82041c1c2e805c34119ebc5/pkg/reconciler/common/images.go#L148) that is based on name.
- Update script and readme.
https://jira.nutanix.com/browse/NCN-109043
Tested deployment on a local cluster - validated tags for the images that are deployed.
```release-note
```
**Checklist**
> feat: Update images for Knative - env vars and queue-proxy

- hack/list-images.sh
- services/git-operator/0.1.4/kustomization.yaml
Can update existing kustomization overlay to specify `newName` which will replace `bitnami` images with `bitnamilegacy`
```
kustomize build services/git-operator/0.1.4 | grep -C1 bitnami
fieldPath: metadata.namespace
image: bitnamilegacy/kubectl:1.32.3
name: admin-credentials-rotate
```
```release-note
```
**Checklist**
> fix(git-operator): Override image  using kustomization overlay

- .github/workflows/validate-licenses.yaml
Short-term fix to manually close/reopen PRs after license update is pushed by GHA
https://jira.nutanix.com/browse/NCN-108002
Temp commit to bump an image to trigger the licenses bump, workflow successfully closed/reopened PR after the commit:
```release-note
```
**Checklist**
> ci(gha): Close/reopen PRs after license update
