mesosphere/kommander-applications

services/kube-prometheus-stack/17.2.1/defaults/cm.yaml
Reflecting changes in https://github.com/mesosphere/kommander/pull/905
=> chore: Enable containerd metrics targets

services/kommander-flux/0.17.2/templates/kustomization.yaml, services/kube-prometheus-stack/17.2.1/defaults/cm.yaml
Signed-off-by: Mikołaj Baranowski <mikolajb@gmail.com>
=> chore: Include a network policy file in the kustomization

services/kube-prometheus-stack/17.2.1/defaults/cm.yaml
Signed-off-by: Mikołaj Baranowski <mikolajb@gmail.com>
=> feat: Enable prometheus node exporter

services/kommander/0.1.0/defaults/cm.yaml
Signed-off-by: Mikołaj Baranowski <mikolajb@gmail.com>
=> chore: Allow to specify issuer kind for kommander

services/traefik/10.3.0/traefik.yaml
https://jira.d2iq.com/browse/D2IQ-80123
=> fix: Update traefik docs link

services/gitea/4.1.1/defaults/cm.yaml
Signed-off-by: Mikołaj Baranowski <mikolajb@gmail.com>
=> fix: Cluster domain to work in alpine linux

services/kommander/0.1.0/defaults/cm.yaml
New defaults after switching to `cli` installations.
=> chore: Update kommander defaults

services/kommander-flux/0.17.2/kustomization.yaml, services/kommander-flux/0.17.2/patch-source-ctrl-network-policy.yaml
https://jira.d2iq.com/browse/D2IQ-79266
=> feat: guard src ctrl ingress access with network policy

hack/flux/update-flux.sh
=> build: remove old flux version upon update

services/cert-manager/0.2.7/release/release.yaml, services/karma/2.0.0/karma.yaml, services/metallb/0.12.2/metallb.yaml, services/traefik-forward-auth/0.3.2/traefik-forward-auth.yaml, services/velero/3.1.3/velero.yaml
follow up for #55 
I stashed my changes and did not add all the changes as i said I did here - https://github.com/mesosphere/kommander-applications/pull/55#issue-1055298680
=> feat: remove explicit namespace creation from HelmReleases

services/traefik-forward-auth-mgmt/0.3.2/defaults/cm.yaml
This aligns traefik-forward-auth-mgmt with traefik-forward-auth.
=> feat: use TFA 3.0.3

mergebot-config.json
Mergebot won't work properly until this is merged to `main`
=> chore: Add mergebot config

.tool-versions, make/all.mk, make/release.mk
New make target to replace the script in CI.
=> feat: Provide release target

services/logging-operator/3.15.0/defaults/cm.yaml
https://jira.d2iq.com/browse/D2IQ-82010
=> fix: Deploy fluent-bit for pod logs to control plane

services/knative/0.18.3/defaults/cm.yaml
Sets the default values for KNative service for Kaptain.
=> Update default values for KNative

services/kaptain/1.3.0/defaults/cm.yaml, services/kaptain/1.3.0/defaults/kustomization.yaml, services/kaptain/1.3.0/kaptain.yaml, services/kaptain/1.3.0/kustomization.yaml, services/kaptain/metadata.yaml
Allow to install kaptain as kommander's AppDeployment. [D2IQ-81777](https://jira.d2iq.com/browse/D2IQ-81777)
Changes are used here: https://github.com/mesosphere/kudo-kubeflow/pull/600
=> feat: add kaptain

services/kube-prometheus-stack/18.1.1/defaults/cm.yaml
Jira ticket: https://jira.d2iq.com/browse/D2IQ-82767
=> fix: set sha to empty to ensure airgapped works

services/chartmuseum/metadata.yaml
Add missing metadata for chartmuseum service
=> fix: Add chartmuseum metadata

services/kubetunnel/0.0.10/defaults/cm.yaml, services/kubetunnel/0.0.10/defaults/kustomization.yaml, services/kubetunnel/0.0.10/kubetunnel.yaml, services/kubetunnel/0.0.10/kustomization.yaml
Test are executed in https://github.com/mesosphere/kommander/pull/1312
=> feat: Update to kubetunnel 0.0.10 (compatible with kubernetes 1.22)

services/gitea/4.1.1/defaults/cm.yaml
We currently don't want users to be able to register an account in
Gitea.
=> feat: disable user registration in Gitea

common/defaults/project/catalog-repositories/kustomization.yaml, common/defaults/project/kustomization.yaml, common/defaults/workspace/catalog-repositories/kustomization.yaml, common/defaults/workspace/kustomization.yaml, services/gitea/4.1.1/defaults/cm.yaml
Context  https://jira.d2iq.com/browse/D2IQ-79950
kommander PR https://github.com/mesosphere/kommander/pull/1329
=> feat: default catalog repositories in kommander

services/kommander/0.2.0/defaults/cm.yaml
Refer following commits which removed certain values:
- https://github.com/mesosphere/kommander/pull/602/files#diff-e34fb33dbcb2f8e616e42e83d478262d462a3834cf3e4d6fcc3d74e0acc9808eL96-L97
- https://github.com/mesosphere/kommander/pull/1093/files#diff-e34fb33dbcb2f8e616e42e83d478262d462a3834cf3e4d6fcc3d74e0acc9808eL85-L95
Testing kommander CI at https://github.com/mesosphere/kommander/pull/1412/files
=> chore: tidy up unused values

services/centralized-grafana/32.0.2/centralized-grafana.yaml, services/kube-prometheus-stack/32.0.2/kube-prometheus-stack.yaml, services/kubecost/0.22.1/kubecost.yaml
Dashboard app versions were out of date, updating
=> fix: Update dashboard app versions

.pre-commit-config.yaml, .tool-versions, hack/validate-default-apps-versions.sh, services/kommander/0.2.0/defaults/cm.yaml
Jira: https://jira.d2iq.com/browse/D2IQ-85345, https://jira.d2iq.com/browse/D2IQ-85338
Example of failing pre-commit check for the existence of a default app: https://teamcity.mesosphere.io/buildConfiguration/ClosedSource_Kommander2_KommanderApplications_PreCommitChecks/3357643?buildTab=log&expandAll=true&focusLine=1478
=> feat: Provide versions of default applications

services/centralized-kubecost/0.22.1/post-install-jobs.yaml, services/centralized-kubecost/0.22.1/release.yaml, services/cert-manager/1.7.1/release.yaml, services/cert-manager/1.7.1/root-ca.yaml, services/gatekeeper/3.7.0/cleanup.yaml, services/gatekeeper/3.7.0/constraints.yaml, services/gatekeeper/3.7.0/constrainttemplates.yaml, services/gatekeeper/3.7.0/release.yaml, services/kubefed/0.9.1/federatedtypeconfigs.yaml, services/kubefed/0.9.1/kube-federation-system-namespace.yaml, services/kubefed/0.9.1/release.yaml
Resolves https://jira.d2iq.com/browse/D2IQ-85656
=> chore: adds spec.wait to Kustomizations

hack/flux/update-flux.sh
https://jira.d2iq.com/browse/D2IQ-85584
=> chore: adds slack notification label to flux update PRs

.tool-versions, Dockerfile.ci
Also sort tools by name in tool versions file.- build: Use asdf pre-commit
=> build: Use asdf pre-commit and upgrade tool versions

common/defaults/project/catalog-repositories/kustomization.yaml, common/defaults/project/kustomization.yaml, common/defaults/workspace/catalog-repositories/kustomization.yaml, common/defaults/workspace/kustomization.yaml
Required for https://github.com/mesosphere/kommander/pull/1523
=> chore: remove unused directories

services/centralized-kubecost/0.23.1/post-install-jobs.yaml, services/centralized-kubecost/0.23.1/release.yaml, services/cert-manager/1.7.1/release.yaml, services/cert-manager/1.7.1/root-ca.yaml, services/gatekeeper/3.7.0/cleanup.yaml, services/gatekeeper/3.7.0/constraints.yaml, services/gatekeeper/3.7.0/constrainttemplates.yaml, services/gatekeeper/3.7.0/release.yaml, services/istio/1.11.6/helmrelease.yaml, services/jaeger/2.29.0/helmrelease.yaml, services/jaeger/2.29.0/pre-upgrade.yaml, services/kubefed/0.9.1/federatedtypeconfigs.yaml, services/kubefed/0.9.1/kube-federation-system-namespace.yaml, services/kubefed/0.9.1/release.yaml, services/minio-operator/4.4.10/minio-operator-helmrelease.yaml, services/minio-operator/4.4.10/minio-operator-pre-upgrade.yaml, services/minio-operator/4.4.10/minio-tenant-helmrelease.yaml
https://jira.d2iq.com/browse/D2IQ-86718
To go along with https://github.com/mesosphere/kommander/pull/1573, increase all kustomizations defined in k-apps to have interval of 6h (timeouts were already 60s, I just updated to 1m to keep it consistent)
=> fix: Increase kustomization interval to 6h

services/kubetunnel/0.0.10/kubetunnel.yaml
https://jira.d2iq.com/browse/D2IQ-86717
=> fix: update kubetunnel crds on upgrade

services/centralized-kubecost/0.23.1/post-install-jobs.yaml, services/centralized-kubecost/0.23.1/release.yaml, services/cert-manager/1.7.1/release.yaml, services/cert-manager/1.7.1/root-ca.yaml, services/gatekeeper/3.7.0/cleanup.yaml, services/gatekeeper/3.7.0/constraints.yaml, services/gatekeeper/3.7.0/constrainttemplates.yaml, services/gatekeeper/3.7.0/release.yaml, services/istio/1.11.6/helmrelease.yaml, services/jaeger/2.29.0/helmrelease.yaml, services/jaeger/2.29.0/pre-upgrade.yaml, services/kubefed/0.9.1/federatedtypeconfigs.yaml, services/kubefed/0.9.1/kube-federation-system-namespace.yaml, services/kubefed/0.9.1/release.yaml, services/minio-operator/4.4.10/minio-operator-helmrelease.yaml, services/minio-operator/4.4.10/minio-operator-pre-upgrade.yaml, services/minio-operator/4.4.10/minio-tenant-helmrelease.yaml
Reverts mesosphere/kommander-applications#256
reverting this to fix cluster attachment, post ff we can explore adding `retryInterval` to all kustomizations.
https://mesosphere.slack.com/archives/C01LNF6KML5/p1648210398628699
=> Revert "fix: Increase kustomization interval to 6h"

services/centralized-kubecost/0.23.1/post-install-jobs.yaml, services/centralized-kubecost/0.23.1/release.yaml, services/cert-manager/1.7.1/release.yaml, services/cert-manager/1.7.1/root-ca.yaml, services/gatekeeper/3.7.0/cleanup.yaml, services/gatekeeper/3.7.0/constraints.yaml, services/gatekeeper/3.7.0/constrainttemplates.yaml, services/gatekeeper/3.7.0/release.yaml, services/istio/1.11.6/helmrelease.yaml, services/jaeger/2.29.0/helmrelease.yaml, services/jaeger/2.29.0/pre-upgrade.yaml, services/kubefed/0.9.1/federatedtypeconfigs.yaml, services/kubefed/0.9.1/kube-federation-system-namespace.yaml, services/kubefed/0.9.1/release.yaml, services/minio-operator/4.4.10/minio-operator-helmrelease.yaml, services/minio-operator/4.4.10/minio-operator-pre-upgrade.yaml, services/minio-operator/4.4.10/minio-tenant-helmrelease.yaml
https://github.com/mesosphere/kommander/pull/1580
=> fix: Add retryInterval to all kustomizations

services/logging-operator/3.17.0/defaults/cm.yaml
testing in https://github.com/mesosphere/kommander/pull/1597
=> chore(logging-operator): bump configmap-reload image to v0.7.1

services/kommander/0.2.0/defaults/cm.yaml
Address https://jira.d2iq.com/browse/D2IQ-86716
=> feat: add flux to default apps

services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml, services/kommander/0.2.0/kommander.yaml, services/logging-operator/3.17.3/logging-operator-logging.yaml, services/logging-operator/3.17.3/logging-operator.yaml
=> release v2.2.0 rc.5

services/traefik-forward-auth/0.3.6/defaults/cm.yaml
JIRA: https://jira.d2iq.com/browse/D2IQ-80979
=> fix: tfa should reload on cm change

services/centralized-grafana/33.1.5/centralized-grafana.yaml, services/grafana-logging/6.22.0/grafana.yaml, services/jaeger/2.29.0/helmrelease/release.yaml, services/karma/2.0.1/karma.yaml, services/kiali/1.47.0/kiali.yaml, services/kube-prometheus-stack/33.1.5/kube-prometheus-stack.yaml, services/kubecost/0.23.3/kubecost.yaml, services/kubernetes-dashboard/5.1.1/kubernetes-dashboard.yaml, services/minio-operator/4.4.10/minio-operator-helmrelease/release.yaml, services/traefik/10.9.1/traefik.yaml
While updating appversions table for 2.2 RN, noticed we also missed updating some app versions in kapps. hopefully got them all here
=> fix: Update appversions

services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml, services/kommander/0.2.0/kommander.yaml
prepping release branch for rc.7
=> [release-2.2] bump kommander charts to rc.7

services/kommander/0.2.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
https://jira.d2iq.com/browse/D2IQ-87219
=> feat: Bump cluster-observer to 1.0.3

services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml, services/kommander/0.2.0/kommander.yaml
=> [release-2.2] feat: Bump kommander charts to v2.2.0-rc.9

services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml, services/kommander/0.2.0/kommander.yaml
=> [release-2.2] feat: Bump kommander charts to rc.11

services/kommander-appmanagement/0.2.0/kommander-appmanagement.yaml, services/kommander/0.2.0/kommander.yaml
=> feat: Bump kommander charts to v2.2.0 GA

mergebot-config.json
bump mergebot versions post release
=> build: Bump mergebot versions post 2.2.0

services/kubefed/0.9.1/defaults/cm.yaml
https://jira.d2iq.com/browse/D2IQ-84836
Tested at https://github.com/mesosphere/kommander/pull/1653
=> chore: Bump kubefed's kubectl image

services/grafana-loki/0.33.2/minio.yaml, services/project-grafana-loki/0.33.2/minio.yaml, services/velero/3.1.5/defaults/cm.yaml
https://jira.d2iq.com/browse/D2IQ-84836
Tested at https://github.com/mesosphere/kommander/pull/1667
=> chore: Bump minio images to latest releases

make/release.mk
Resolves: https://jira.d2iq.com/browse/D2IQ-87649
=> chore: logs published url for the release

make/ci.mk, make/release.mk
Resolves: https://jira.d2iq.com/browse/D2IQ-88067
=> feat: notify in slack about repo tarball release

.go-tools, make/repo.mk
Let's switch to -dev for daily release.
=> feat: Use -dev for development release instead of -next

services/kommander-appmanagement/0.2.1/kommander-appmanagement.yaml, services/kommander/0.2.1/kommander.yaml
=> feat: Bump komm charts to v2.2.1-rc.1

common/build/kommander-cert-federation.yaml
=> [release 2.2] build: add 0.0.2 cert-federation chart for airgapped bundle

services/kommander-appmanagement/0.2.1/kommander-appmanagement.yaml, services/kommander/0.2.1/kommander.yaml
=> build: bump komm charts to v2.2.1-rc.3

services/kommander-appmanagement/0.3.0/defaults/cm.yaml, services/kommander/0.3.0/defaults/cm.yaml
https://jira.d2iq.com/browse/D2IQ-91016
Required for https://github.com/mesosphere/kommander/pull/1987
=> feat: add webhook cert values for appmanagement

.github/pull_request_template.md
Removes trailing whitespace to make pre-commit check happy.
--
--
--
--
=> fix: remove trailing whitespace

.gitignore
Adds .idea directory to .gitignore file 
--
--
--
=> chore: add .idea dir to gitignore

.tool-versions
Adds direnv plugin to .tool-version file to support .envrc file with asdf 
--
--
--
--
Depends on #478
=> chore: add direnv plugin to .tool-versions

.tool-versions, make/repo.mk, make/tools.mk
Let's use the same code as in 2.3 and 2.2 branches.
- https://jira.d2iq.com/browse/D2IQ-91920>
```release-note
```
=> feat: Use gh-dkp tool for calculating dev release name (#474)

hack/release/cmd/postrelease/postrelease.go, hack/release/cmd/prerelease/prerelease.go, hack/release/cmd/root.go, hack/release/go.mod, hack/release/go.sum, hack/release/pkg/chartversion/chartversion.go, hack/release/pkg/chartversion/chartversion_test.go
Depends on #511
Initial version of post-release command (identical to pre-release).
- https://jira.d2iq.com/browse/D2IQ-91716
```release-note
```
=> feat: Add post-release command

hack/release/cmd/postrelease/postrelease.go, hack/release/pkg/appversion/appversion.go, hack/release/pkg/appversion/appversion_test.go, hack/release/pkg/constants/constants.go
Change content of kommander apps files
https://jira.d2iq.com/browse/D2IQ-91716
```release-note
```
=> feat: Change kommander apps variable names

.github/code.yml
As discussed [here](https://mesosphere.slack.com/archives/C03P4F14M7E/p1660144872826169)
```release-note
```
=> chore: Start adding labels to PRs according to their size

hack/flux/update-flux.sh, services/centralized-grafana/34.9.3/defaults/cm.yaml, services/fluent-bit/0.19.20/defaults/cm.yaml, services/grafana-logging/6.28.0/defaults/cm.yaml, services/grafana-loki/0.48.4/defaults/cm.yaml, services/karma/2.0.1/defaults/cm.yaml, services/kommander-flux/0.31.5/templates/apps_v1_deployment_helm-controller.yaml, services/kommander-flux/0.31.5/templates/apps_v1_deployment_kustomize-controller.yaml, services/kommander-flux/0.31.5/templates/apps_v1_deployment_notification-controller.yaml, services/kommander-flux/0.31.5/templates/apps_v1_deployment_source-controller.yaml, services/kube-prometheus-stack/34.9.3/defaults/cm.yaml, services/kubecost/0.26.0/defaults/cm.yaml, services/logging-operator/3.17.7/defaults/cm.yaml, services/project-grafana-logging/6.28.0/defaults/cm.yaml, services/project-grafana-loki/0.48.4/defaults/cm.yaml, services/prometheus-adapter/2.17.1/defaults/cm.yaml, services/traefik-forward-auth-mgmt/0.3.9/defaults/cm.yaml, services/traefik-forward-auth/0.3.8/defaults/cm.yaml
Signed-off-by: Tarun Gupta Akirala <takirala@users.noreply.github.com>
```release-note
```
=> feat: configurable log level

hack/flux/update-flux.sh, services/karma/2.0.1/defaults/cm.yaml, services/kommander-flux/0.31.5/templates/apps_v1_deployment_helm-controller.yaml, services/kommander-flux/0.31.5/templates/apps_v1_deployment_kustomize-controller.yaml, services/kommander-flux/0.31.5/templates/apps_v1_deployment_notification-controller.yaml, services/kommander-flux/0.31.5/templates/apps_v1_deployment_source-controller.yaml
Forward porting the fixes done in #548 
```release-note
```
=> chore: revert flux controllers log level changes

.bloodhound.yml, make/test.mk
Test against Kubernetes v1.24.
```release-note
```
=> test: Test against Kubernetes v1.24

services/grafana-loki/0.48.4/grafana-dashboards/loki-writes-resources.json
Fix the grafana dashboard title to include the necessary prefix
```release-note
```
=> fix: Fix loki writes resources dashboard title

.github/workflows/lint-pr.yaml
Introduces a new check for PR title if the title is a conventional commit message
--
action repo: https://github.com/amannn/action-semantic-pull-request
--
=> ci: add linters to check if title is semantic commit message

.github/workflows/kommander-branch.yaml
This workflow is triggered on PRs with a label `open-kommander-pr`- the action triggers (and pushes) a branch (prefixed with `kapps/`) to the kommander repo, which includes an update to the `Makefile` to point the kommander-applications ref to the branch that the k-apps PR is based off of. There is then another workflow added to the kommander repo (PR with some fixes to that workflow: https://github.com/mesosphere/kommander/pull/2284) which triggers a PR creation automatically for branches that are prefixed with `kapps/`.
I tested this workflow on my fork with this PR: https://github.com/gracedo/kommander-applications/pull/1 which created this branch on the kommander repo: https://github.com/mesosphere/kommander/tree/kapps/gracedo/test-workflow with …
=> build: Add workflow to create kommander branch

services/grafana-loki/0.48.4/grafana-dashboards/loki-deletion.json, services/grafana-loki/0.48.4/grafana-dashboards/loki-reads-resources.json, services/grafana-loki/0.48.4/grafana-dashboards/loki-retention.json, services/grafana-loki/0.48.4/grafana-dashboards/loki-writes-resources.json
This updates a few queries to make the panel work. My IDE went a bit crazy with formatting fixes but the changes are really just changing queries to use the `container` label instead of `job` 
```release-note
```
=> fix: update loki dashboard queries

.github/workflows/lint-pr.yaml
https://mesosphere.slack.com/archives/C5U03P5T6/p1662763874388349?thread_ts=1662662378.452169&cid=C5U03P5T6
this repo doesn't have integration for self hosted instances
```release-note
```
=> build: Run lint pr workflow on ubuntu-latest

.github/workflows/rebase.yaml
Add automatic rebase workflow
```release-note
```
=> build: Add automatic rebase workflow

.github/workflows/mergebot.yml
Added mergebot back to charts as mergebot can now function in public repos.
https://jira.d2iq.com/browse/D2IQ-90583
```release-note
```
=> ci: Reimplemented mergebot

.github/workflows/rebase.yaml
https://github.com/mesosphere/kommander-applications/pull/620
Add automatic rebase workflow
```release-note
```
=> [release-2.3][BACKPORT] build: Add automatic rebase workflow

.github/workflows/rebase.yaml
https://github.com/mesosphere/kommander-applications/pull/620
Add automatic rebase workflow
```release-note
```
=> [release-2.2][BACKPORT] build: Add automatic rebase workflow

services/kommander-appmanagement/0.3.2/kommander-appmanagement.yaml, services/kommander/0.3.2/kommander.yaml
Bump chart versions
```release-note
```
=> feat: bump kommander chart versions to v2.3.1

.github/workflows/rebase.yaml
bumping rebase version to see if it fixes some errors on the rebase workflow
```release-note
```
=> build: Bump rebase to v1.7

.github/workflows/test.yaml, .gitignore, .go-tools, README.md, make/go.mk
Enables [goveralls](https://github.com/mattn/goveralls) for the repo.
```release-note
```
=> feat: Enable coveralls reporting

.github/workflows/test.yaml
As in the title.
```release-note
```
=> feat: Let's run test on push to produce test coverage

README.md
Apparently, the branch has to be set explicitly.
```release-note
```
=> fix: Use correct branch for test coverage badge

.github/bump-pr-labeler.yaml, .github/service-labeler.yaml, .github/workflows/automerge.yaml, .github/workflows/labeler.yaml, .github/workflows/update-service-labeler.yaml, make/all.mk, make/workflows.mk
- Add labeler workflow to label PRs with the service that is being updated.
- Add make target to run script to regenerate the .github/service-labeler.yaml file with the latest services.
- Add workflow to automatically update the .github/service-labeler.yaml file on every PR if necessary (if new service is added).
- Add step to labeler workflow to label automated bump PRs with `ok-to-test`, and `open-kommander-pr` only for those indicated in .github/bump-pr-labeler.yaml.
- Add automerge workflow to automatically merge automated bump PRs once the required checks are green (and there are no `do-not-merge` labels) -- example https://github.com/gracedo/kommander-applications/pull/8
Adding some workflows to better filter PRs by the apps being updated. …
=> build: Add workflows for bump PRs

.github/workflows/update-service-labeler.yaml
fixes pre-commit error that is on `main`
```release-note
```
=> fix: Pre-commit remove newline

services/centralized-kubecost/0.27.0/post-install-jobs/post-install-jobs.yaml, services/centralized-kubecost/0.27.0/release/release.yaml, services/istio/1.14.1/defaults/cm.yaml, services/jaeger/2.32.2/pre-upgrade/delete-jaeger-deployment.yaml, services/kommander/0.4.0/defaults/cm.yaml, services/kube-prometheus-stack/40.0.0/pre-upgrade/delete-node-exporter-daemonset.yaml, services/kubetunnel/0.0.14/defaults/cm.yaml, services/minio-operator/4.4.25/minio-operator-pre-upgrade/update-minio-tenant-crd-metadata.yaml, services/prometheus-adapter/3.4.0/pre-upgrade/delete-prometheus-adapter-deployment.yaml, services/thanos/0.4.7/jobs/jobs.yaml, services/traefik/10.9.3/defaults/cm.yaml
Cleans up some unused substitution variables.
We may want to bump some of these images in the future but I intentionally left that out for now 
https://d2iq.atlassian.net/browse/D2IQ-87946
```release-note
```
=> chore: clean up kubetools vars

.github/workflows/backport.yaml, .github/workflows/rebase.yaml
```
Error: fatal: not in a git directory
```
Fixing this. However, did some testing on the `rebase` action on my fork and I wasn't able to figure out how to get the rebased commits signed :/ just fixing the error for now, will need to revisit the sining shenanigans later, it might be a shortcoming of the upstream action.
```release-note
```
=> fix: Fix backport action

services/centralized-kubecost/metadata.yaml, services/dex-k8s-authenticator/metadata.yaml, services/dkp-insights-management/metadata.yaml, services/istio/metadata.yaml, services/jaeger/metadata.yaml, services/karma-traefik/metadata.yaml, services/karma/metadata.yaml, services/kiali/metadata.yaml, services/knative/metadata.yaml, services/kommander/metadata.yaml, services/kube-prometheus-stack/metadata.yaml, services/kubecost-thanos-traefik/metadata.yaml, services/kubecost/metadata.yaml, services/prometheus-adapter/metadata.yaml, services/prometheus-thanos-traefik/metadata.yaml, services/traefik-forward-auth-mgmt/metadata.yaml, services/traefik-forward-auth/metadata.yaml
It adds a new `dependencies` field in the `metadata.yaml` file for all the services that have dependencies on other services.
https://d2iq.atlassian.net/browse/D2IQ-93535
```release-note
```
=> feat: adds dependencies in metadata

services/grafana-loki/0.33.3/grafana-loki-upgrade-job.yaml, services/grafana-loki/0.33.3/grafana-loki-upgrade-job/upgrade-job.yaml, services/grafana-loki/0.33.3/kustomization.yaml, services/grafana-loki/0.33.3/minio.yaml, services/project-grafana-loki/0.33.3/grafana-loki-upgrade-job.yaml, services/project-grafana-loki/0.33.3/grafana-loki-upgrade-job/upgrade-job.yaml, services/project-grafana-loki/0.33.3/kustomization.yaml, services/project-grafana-loki/0.33.3/minio.yaml
See this comment for more info https://d2iq.atlassian.net/browse/D2IQ-93626?focusedCommentId=545251
https://d2iq.atlassian.net/browse/D2IQ-93626
```release-note
```
=> fix: add upgrade job for grafana-loki

services/nvidia-gpu-operator/metadata.yaml
https://d2iq.atlassian.net/browse/D2IQ-92963
```release-note
```
=> chore: update nvidia-gpu-operator metadata.yaml 

licenses.d2iq.yaml
Removes unused license mappings.
https://d2iq.atlassian.net/browse/D2IQ-93766
```release-note
```
=> chore: remove unused license mappings

.github/workflows/validate-licenses.yaml
Let's run license validation on `main` and releases.
It will also allow to include license check in a release validation.
```release-note
```
=> chore: Let's validate licenses on main and releases

services/reloader/metadata.yaml
It fixes a typo
https://d2iq.atlassian.net/browse/D2IQ-93742
```release-note
```
=> docs: Fix typo in the Reloader app overview

.github/workflows/validate-licenses.yaml, licenses.d2iq.yaml
This adds support for variables in the license mapping files. For more infomation see: https://github.com/mesosphere/dkp-infra-tools/pull/77.
https://d2iq.atlassian.net/browse/D2IQ-93811
```release-note
```
**Checklist**
=> chore: use variables in license mapping file

licenses.d2iq.yaml
```release-note
```
**Checklist**
=> fix: Update license mapping for kommander UI

services/nvidia-gpu-operator/1.11.1/defaults/cm.yaml
Removes the use of a "forked" container for an official container instead 
```release-note
```
**Checklist**
=> feat: use an official ngc image for the validator

licenses.d2iq.yaml
Fixes TFA mapping.
```release-note
```
**Checklist**
=> fix: licenses tfa mapping

licenses.d2iq.yaml, services/dkp-insights-management/0.3.0/defaults/cm.yaml, services/dkp-insights-management/0.3.0/helmrelease/helmrelease.yaml
Bump DKP-Insights to v0.3.0
```release-note
```
**Checklist**
=> chore: Bump DKP-Insights Management

.github/workflows/validate-licenses.yaml, licenses.d2iq.yaml
Fixes some incorrectly mapped licenses.
```release-note
```
**Checklist**
=> fix: license mapping

make/test.mk
another post release bump. I'm not sure if I should make a ticket to automate this because the way we run e2e tests might be changing?
```release-note
```
**Checklist**
=> test: upgrade from 2.4.0-dev

licenses.d2iq.yaml, services/velero/3.3.0/defaults/cm.yaml
Co-Authored-by: <mikolajb@gmail.com>
https://d2iq.atlassian.net/browse/D2IQ-94272
```release-note
```
**Checklist**
=> fix: bump velero aws plugin for compatibility

.github/workflows/test.yaml
Bumps gh checkout action.
```release-note
```
**Checklist**
=> chore: Upgrade github checkout action

.github/workflows/lint.yaml
Fixes the `no-commit-to-branch` failure caused by `pull_request_target` trigger
--
--
--
**Checklist**
=> ci: run pull_request on source branch

.github/workflows/validate-licenses.yaml, make/release.mk, make/validate.mk
Backport of https://github.com/mesosphere/kommander-applications/pull/935
```release-note
```
**Checklist**
=> build: use downloads.d2iq.com (2.3)

.github/workflows/validate-licenses.yaml, make/release.mk
Backport of https://github.com/mesosphere/kommander-applications/pull/935
```release-note
```
**Checklist**
=> build: use downloads.d2iq.com (2.1)

.github/workflows/validate-licenses.yaml, make/release.mk, make/validate.mk
Backport of https://github.com/mesosphere/kommander-applications/pull/935
```release-note
```
**Checklist**
=> build: use downloads.d2iq.com (2.4)

.github/workflows/validate-licenses.yaml, make/release.mk, make/validate.mk
Backport of https://github.com/mesosphere/kommander-applications/pull/935
```release-note
```
**Checklist**
=> build: use downloads.d2iq.com (2.2)

licenses.d2iq.yaml
```release-note
```
**Checklist**
=> chore: add kommander2-core-installer

make/release.mk
Backports https://github.com/mesosphere/kommander-applications/pull/949
```release-note
```
**Checklist**
=> [release-2.1] fix: revert s3 bucket name (#949)

charts/kommander-operator/templates/rback_v1_clusterrole_operator_kommander-operator.yaml
Title says it all
```release-note
```
**Checklist**
=> fix: Sum clusterroles instead of ANDing

common/kommander-operator/helmrelease.yaml
Add an optional overrides ConfigMap to mainly be used for the e2e tests that rely on images in ECR.
https://d2iq.atlassian.net/browse/D2IQ-95849
```release-note
```
**Checklist**
=> feat: Add optional configmap to kommander-operator

charts/kommander-operator/templates/rback_v1_clusterrole_operator_kommander-operator.yaml
Adding permissions to access and write to git repository
```release-note
```
**Checklist**
=> feat: Add permission to kommander operator to access git repository

README.md
As comments are not included in new versions of licenses.d2iq.yaml, this is the follow-up pr which updates the documentation in this repo's README.
Part of https://d2iq.atlassian.net/browse/D2IQ-95738
As comments are not included in new versions of licenses.d2iq.yaml, this is the follow-up pr which updates the documentation in this repo's README.
```release-note
```
**Checklist**
=> feat: Update readme for image automation

services/kiali/1.57.1/defaults/cm.yaml
backports #1020 and #1022
https://d2iq.atlassian.net/browse/D2IQ-96214
```release-note
```
**Checklist**
=> fix: Fix errors in kiali config (2.4)

licenses.d2iq.yaml
follow up of #1038
```release-note
```
**Checklist**
=> fix: update license manifest

services/kommander/0.5.0/defaults/cm.yaml
Reverts mesosphere/kommander-applications#1054
=> revert: "fix: keep gitea during expansion workflow"

services/kube-prometheus-stack/44.2.1/helmrelease/kube-prometheus-stack.yaml
backports https://github.com/mesosphere/kommander-applications/pull/1065
```release-note
```
**Checklist**
=> feat: Add optional mgmt overrides cm to KPS HR (#1065)

services/kubetunnel/0.0.15/defaults/cm.yaml, services/traefik/20.8.0/defaults/cm.yaml
https://d2iq.atlassian.net/browse/D2IQ-93666
```release-note
```
**Checklist**
=> feat: add kubetunnel-proxy ingress config

make/test.mk
```release-note
```
**Checklist**
=> ci: upgrade from 2.5.0-dev to 2.6.0-dev

services/logging-operator/3.17.10/defaults/cm.yaml
readinessProbe for fluentd
```release-note
```
**Checklist**
=> feat: readinessProbe for fluentd (main)

services/istio/1.17.2/defaults/cm.yaml, services/kube-oidc-proxy/0.3.2/defaults/cm.yaml
dkp priorityclass critical for istio, KOP and kubetunnel
https://d2iq.atlassian.net/browse/D2IQ-96267
```release-note
```
**Checklist**
=> feat: dkp critical for istio KOP

hack/validate-default-apps-versions.sh, services/dex-k8s-authenticator/1.2.15/defaults/cm.yaml, services/reloader/1.0.24/defaults/cm.yaml
Update app configs to use DKP High PriorityClass for foundational apps
https://d2iq.atlassian.net/browse/D2IQ-96663
```release-note
```
**Checklist**
=> feat: dkp high for dka reloader

services/nvidia-gpu-operator/22.9.1/defaults/cm.yaml
Adds default version values for nvidia components to be consumed by #1234 
```release-note
```
**Checklist**
=> fix: adds missing values

services/dex/2.12.1/defaults/cm.yaml, services/dex/2.12.1/dex.yaml, services/traefik-forward-auth-mgmt/0.3.9/defaults/cm.yaml, services/traefik-forward-auth/0.3.9/defaults/cm.yaml, services/traefik/23.0.1/defaults/cm.yaml
What problem does this PR solve?:
dkp priorityclass critical for monitoring k-apps.
https://d2iq.atlassian.net/browse/D2IQ-96267
```release-note
```
**Checklist**
=> feat: dkp critical traefik, tfa and dex

services/kubernetes-dashboard/6.0.7/defaults/cm.yaml
Update app configs to use DKP High PriorityClass for kubernetes-dashboard
https://d2iq.atlassian.net/browse/D2IQ-96663
```release-note
```
**Checklist**
=> feat: add high priority for kubernetes-dashboard

services/nvidia-gpu-operator/23.3.1/defaults/cm.yaml
should help fix the error in the e2e tests we're seeing here https://github.com/mesosphere/kommander-e2e/actions/runs/5011030794/jobs/8981453271
```release-note
```
**Checklist**
=> fix: bump toolkit version

services/kommander/0.6.0/dynamic-helmreleases/mtls-proxy/mtls-proxy.yaml
Bump mtls-proxy which adds support to set priority class
https://d2iq.atlassian.net/browse/D2IQ-97331
```release-note
```
**Checklist**
=> feat: Bump mtls-proxy to 0.1.7

common/build/kommander-cert-federation.yaml
bump kommander-cert-federation to latest version which adds support for priority class
https://d2iq.atlassian.net/browse/D2IQ-97320
```release-note
```
**Checklist**
=> feat: Bump kommander-cert-federation

licenses.d2iq.yaml
Companion PR for https://github.com/mesosphere/kommander/pull/3511
```release-note
```
**Checklist**
=> chore: add license manifest for kommander config-api image

.github/workflows/validate-licenses.yaml, .go-tools, .tool-versions, common/build/kustomization.yaml, common/build/list-images-values.yaml, common/kommander-operator/defaults/cm.yaml, common/kommander-operator/helmrelease.yaml, common/kommander-operator/kustomization.yaml, hack/list-images.sh, hack/release/pkg/chartversion/chartversion.go, hack/release/pkg/chartversion/chartversion_test.go, hack/update-image-lists.sh, licenses.d2iq.yaml, services/dkp-insights-management/0.5.0/helmrelease/kustomization.yaml, services/dkp-insights/0.5.0/helmrelease/extra-images.txt, services/dkp-insights/0.5.0/helmrelease/kustomization.yaml, services/dkp-insights/0.5.0/helmrelease/list-images-values.yaml, services/istio/1.17.2/helmrelease/extra-images.txt, services/istio/1.17.2/helmrelease/kustomization.yaml, services/jaeger/2.46.0/helmrelease/extra-images.txt, services/jaeger/2.46.0/helmrelease/kustomization.yaml, services/kiali/1.70.0/extra-images.txt, services/kommander/0.6.0/dynamic-helmreleases/mtls-proxy/list-images-values.yaml, services/kube-prometheus-stack/46.8.0/helmrelease/extra-images.txt, services/kube-prometheus-stack/46.8.0/helmrelease/kustomization.yaml, services/kubetunnel/0.0.24/extra-images.txt, services/logging-operator/4.2.3/extra-images.txt, services/nvidia-gpu-operator/23.3.2/helmrelease/extra-images.txt, services/nvidia-gpu-operator/23.3.2/helmrelease/kustomization.yaml
```release-note
```
**Checklist**
=> build: Statically list images from helm charts

services/gatekeeper/3.12.0/defaults/cm.yaml, services/logging-operator/4.2.3/defaults/cm.yaml
https://d2iq.atlassian.net/browse/D2IQ-98509
```release-note
```
**Checklist**
=> fix: disable PSPs explictly to avoid upgrade failures

.github/workflows/release.yml
We didn't see output from the release target. Let's run it directly to see what actually happens.
```release-note
```
**Checklist**
=> build: Change the way we execute release target

.github/workflows/create-dev-tag.yml
https://d2iq.atlassian.net/browse/D2IQ-99064
Successful run https://github.com/mesosphere/kommander-applications/actions/runs/6096139790
=> fix: create dev tag pipeline

.github/workflows/create-dev-tag.yml
Following https://github.com/mesosphere/dkp-release-specs/pull/166
```release-note
```
**Checklist**
=> ci: Disable 2.3

.github/workflows/flux-update-scheduled-check.yml, .github/workflows/release.yml
```release-note
```
**Checklist**
=> ci: migrate flux-update-schedule-check to gha

services/dkp-insights/metadata.yaml
Add `certified` and `supported` labels to `dkp-insights`.
[D2iQ-99510](https://d2iq.atlassian.net/browse/D2IQ-99510)
```release-note
```
**Checklist**
=> feat: Add certified and supported labels to dkp-insights.

licenses.d2iq.yaml, services/dkp-insights-management/1.0.0/defaults/cm.yaml, services/dkp-insights-management/1.0.0/helmrelease/helmrelease.yaml, services/dkp-insights/1.0.0/defaults/cm.yaml, services/dkp-insights/1.0.0/helmrelease/helmrelease.yaml
Release DKP-Insights v1.0.0-dev.6
=> feat: Release DKP-Insights v1.0.0-dev.6

licenses.d2iq.yaml, services/dkp-insights-management/1.0.0/defaults/cm.yaml, services/dkp-insights-management/1.0.0/helmrelease/helmrelease.yaml, services/dkp-insights/1.0.0/defaults/cm.yaml, services/dkp-insights/1.0.0/helmrelease/helmrelease.yaml
Release DKP-Insights v1.0.0-dev.7
=> feat: Release DKP-Insights v1.0.0-dev.7

services/ai-navigator-app/0.2.0/defaults/cm.yaml, services/ai-navigator-cluster-info-agent/0.1.0/defaults/cm.yaml
Reduce CPU requests to easy pod scheduling/scaling out.
```release-note
```
**Checklist**
=> fix: reduce CPU requests for cluster info pods

licenses.d2iq.yaml, services/dkp-insights-management/1.0.0/defaults/cm.yaml, services/dkp-insights-management/1.0.0/helmrelease/helmrelease.yaml, services/dkp-insights/1.0.0/defaults/cm.yaml, services/dkp-insights/1.0.0/helmrelease/helmrelease.yaml
=> feat: Release DKP-Insights v1.0.0

licenses.d2iq.yaml, services/gitea/8.2.0/defaults/cm.yaml
Backport of https://github.com/mesosphere/kommander-applications/pull/1768
```release-note
```
**Checklist**
=> fix: Address critical postrgres CVE (#1768)

hack/list-images.sh, services/centralized-kubecost/0.37.2/post-install-jobs/post-install-jobs.yaml, services/centralized-kubecost/0.37.2/release/release.yaml, services/grafana-loki/0.74.6/grafana-loki-pre-install-jobs/pre-install.yaml, services/kube-prometheus-stack/48.3.1/defaults/cm.yaml, services/kubecost/0.37.2/defaults/cm.yaml, services/kubetunnel/0.0.31/defaults/cm.yaml, services/rook-ceph-cluster/1.12.6/pre-install/ceph-crd-check.yaml, services/thanos/12.13.13/jobs/jobs.yaml, services/velero/4.1.1/post-install/kustomization.yaml, services/velero/4.1.1/pre-install/kustomization.yaml, services/velero/4.1.1/pre-install/pre-install-job.yaml, services/velero/4.1.1/velero-pre-install.yaml
This PR lets all the kubectl images explicitly set in k-apps to be configurable using dedicated variables.
=> fix: template kubectl images in a release

common/build/kommander-cert-federation.yaml, services/dex/2.13.6/defaults/cm.yaml, services/istio/1.17.2/defaults/cm.yaml, services/knative/1.10.4/defaults/cm.yaml, services/velero/5.2.2/defaults/cm.yaml
Uniform Kubectl image version among the services.
=> fix: template kubectl 

.github/workflows/create-dev-tag.yml, .github/workflows/lint.yaml, .github/workflows/manifest-validation.yml, .github/workflows/release.yml, .github/workflows/validate-licenses.yaml, .gitignore, Dockerfile.ci, make/ci.mk, make/repo.mk
* ci: migrate tc remaining builds to gha
* ci: remove invalid action
* ci: remove buildkit due to docker error
* ci: edit dockerfile
* ci: edit dockerfile
* ci: rearrange workflow structure
* ci: fix github org
* ci: update workflows
* ci: set ci env
* ci: checkout head instead of merge commit
* ci: make requested changes
* ci: change asdf version
* ci: add release
* ci: remove nexus
* ci: add permissions
* ci: fix aws account info
* ci: fix docker issue
* ci: add git tag
* ci: add slack webhook
* ci: fix whitespaces
* ci: remove e2e tests
* ci: remove unused if statements
* ci: create-dev-tag only runs on main
* ci: moved lint to selfhosted
* ci: fix whitespaces
--------- …
=> ci: migrate tc remaining builds to gha (#1465)

common/build/kommander-cert-federation.yaml, licenses.d2iq.yaml, services/velero/5.2.2/velero-v4-hooks-adoption.yaml
bump cert-federation to latest
https://d2iq.atlassian.net/browse/D2IQ-99985
```release-note
```
**Checklist**
=> feat(cert-federation): Bump to 0.0.8

.github/workflows/kommander-branch.yaml, .github/workflows/kommander-revert-kapps-ref.yaml
title says it all - will delete this secret when this merges
```release-note
```
**Checklist**
=> refactor(gha): Use token instead of ssh key

.github/workflows/manifest-validation.yml, services/kommander/0.6.2/defaults/cm.yaml
This ensures that the app is handled during expansion to be removed.
backports https://github.com/mesosphere/kommander-applications/pull/1869 to release-2.6
https://d2iq.atlassian.net/browse/D2IQ-99868
```release-note
```
**Checklist**
=> fix(kommander): Add ai-nav app to list of mgmt apps

licenses.d2iq.yaml, services/dex/2.13.9/defaults/cm.yaml
JIRA: https://d2iq.atlassian.net/browse/D2IQ-99912
```release-note
```
**Checklist**
=> chore(dex): disable grpc service

.github/workflows/backport.yaml
some ci / gha fixes...
```release-note
```
**Checklist**
=> ci(gha): Update backport action repo

.github/workflows/backport.yaml
(cherry picked from commit 660cc5f6b120227d92d308c1339fefa14066cec7)
```release-note
```
**Checklist**
=> ci(gha): Update backport action repo (#2014)

licenses.d2iq.yaml, services/rook-ceph-cluster/1.12.7/defaults/cm.yaml, services/rook-ceph/1.12.7/defaults/cm.yaml
```release-note
```
**Checklist**
=> chore(rook-ceph): use custom patched images with fixed CVEs

.github/workflows/application-test-scenario.yaml, .github/workflows/application-test.yaml
1st iteration of GHA for app specific test that handles install.
https://d2iq.atlassian.net/browse/D2IQ-98659
```release-note
```
**Checklist**
=> ci: GHA for app specific test

.github/workflows/create-dev-tag.yml, .github/workflows/flux-update-scheduled-check.yml, .github/workflows/lint.yaml, .github/workflows/manifest-validation.yml, .github/workflows/release.yml, .github/workflows/test.yaml, .github/workflows/update-service-labeler.yaml, .github/workflows/validate-licenses.yaml
The org of an action we use changed, let's update it so we can continue using the action.
```release-note
```
**Checklist**
=> ci: Update devbox install action org name

apptests/appscenarios/reloader.go, apptests/appscenarios/reloader_test.go
upgrade test case for reloader
https://d2iq.atlassian.net/browse/D2IQ-98659
```release-note
```
**Checklist**
=> test: reloader upgrade

.github/workflows/create-dev-tag.yml
```release-note
```
**Checklist**
=> ci: New org for devbox-install-action - missed in previous PR

.github/workflows/application-test-scenario-install.yaml, .github/workflows/application-test-scenario-upgrade.yaml, .github/workflows/application-test-scenario.yaml, .github/workflows/application-test.yaml
```release-note
```
**Checklist**
=> ci: app specific test GHA #2

common/helm-repositories/ai-navigator-repos.yaml, common/helm-repositories/kustomization.yaml, common/helm-repositories/mesosphere-repos.yaml, make/release.mk
* refactor(helmrepos): Separate ai-navigator helmrepos into separate file
* fix(release): Omit ai-nav helmrepos from bundle
backports https://github.com/mesosphere/kommander-applications/pull/2135
```release-note
```
**Checklist**
=> fix(release): Omit ai-nav helmrepos from bundle (#2135)

hack/build-archive.sh, make/release.mk
It looks we have to modify a file while creating an archive.
https://jira.nutanix.com/browse/D2IQ-100557
```release-note
```
**Checklist**
=> fix: Modify files in the release archive

apptests/go.mod
```release-note
```
**Checklist**
=> chore: bump golang

services/kommander/0.8.0/defaults/cm.yaml
(cherry picked from commit 7e3e159e80fdc3dfa5104518ec2281fa583b1463)
```release-note
```
**Checklist**
=> fix(kommander): Add kommander-ui to mgmt apps

.bloodhound.yml
bump bloodhound to validate against 1.29.4
https://jira.nutanix.com/browse/NCN-100480
```release-note
```
**Checklist**
=> feat: bump bloodhound to validate against 1.29.4

charts/kommander-operator/templates/deployment.yaml, charts/kommander-operator/templates/rback_v1_clusterrole_operator_kommander-operator.yaml
Add missing permissions and pod label to koperator
https://jira.nutanix.com/browse/NCN-100844
```release-note
```
**Checklist**
=> feat(koperator): Add missing permissions and pod label

apptests/tests-doc.md
Add doc for application-specific tests.
https://jira.nutanix.com/browse/NCN-100296
```release-note
```
**Checklist**
=> feat: Add documentation for application specific tests

common/build/list-images-values.yaml, licenses.d2iq.yaml, services/kommander/0.12.0/dynamic-helmreleases/cluster-observer/list-images-values.yaml
```release-note
```
**Checklist**
=> fix(licenses): override kubectl values

services/git-operator/0.1.0/git-operator.yaml
Bump git-operator to the newest version.
```release-note
```
**Checklist**
=> feat: Bump git-operator to v0.7.0

licenses.d2iq.yaml
The tag does not exist in the mapped repo.
```release-note
```
**Checklist**
=> fix: remove unexisting mapping

hack/flux/update-flux.sh
Flux upgrade script was failing for a while:
https://github.com/mesosphere/kommander-applications/actions/runs/9731819247/job/26856739513#step:7:74
```release-note
```
**Checklist**
=> ci: Fix flux update script

.github/workflows/flux-update-scheduled-check.yml
I don't know how it worked before...
https://github.com/mesosphere/kommander-applications/actions/runs/9747457924/job/26900250612#step:7:140
```release-note
```
**Checklist**
=> ci: Clone kommander repo for flux update script

.github/workflows/flux-update-scheduled-check.yml
Without this - `checkout` action does't have access to kommander repo.
```release-note
```
**Checklist**
=> ci: Clone as mesosphere user so it can access kommander repo

devbox.lock, hack/flux/update-flux.sh
Bump all the tools versions
```release-note
```
**Checklist**
=> ci: devbox update

services/git-operator/0.1.0/git-operator.yaml
Bump to the newest
```release-note
```
**Checklist**
=> feat(git-operator): Bump to v0.8.1

services/git-operator/0.1.0/git-operator.yaml
```release-note
```
**Checklist**
=> feat: kommander-ca for git-operator

services/dex-k8s-authenticator/1.3.2/dex-k8s-authenticator.yaml, services/dex/2.13.12/dex.yaml, services/kommander-appmanagement/0.12.0/kommander-appmanagement.yaml, services/kommander-ui/12.2.0/kommander-ui.yaml, services/kommander/0.12.0/defaults/cm.yaml, services/kubefed/0.10.5/release/release.yaml, services/reloader/1.0.107/reloader.yaml, services/traefik-forward-auth-mgmt/0.3.11/traefik-forward-auth-mgmt.yaml, services/traefik/27.0.2/traefik.yaml
we decided to move SSO apps into kcore to install
https://jira.nutanix.com/browse/NCN-101330
```release-note
```
**Checklist**
=> feat(kommander): Remove SSO from default mgmt apps

licenses.d2iq.yaml
```release-note
```
**Checklist**
=> fix: remove orphaned images

licenses.d2iq.yaml
```release-note
```
**Checklist**
=> chore: add missing image mappings

services/kommander/0.12.0/defaults/cm.yaml
fix typo in `ai-navigator-cluster-clustrer-info-agent` name
```release-note
```
**Checklist**
=> fix(kommander): Typo in app name

licenses.d2iq.yaml, services/git-operator/0.1.0/additional-images.txt, services/git-operator/0.1.0/git-operator-manifests/all.yaml
Title says it all
```release-note
```
**Checklist**
=> feat: Bump git operator to v0.10.0

licenses.d2iq.yaml, services/nkp-insights-management/1.2.0/defaults/cm.yaml, services/nkp-insights-management/1.2.0/helmrelease/helmrelease.yaml, services/nkp-insights/1.2.0/defaults/cm.yaml, services/nkp-insights/1.2.0/helmrelease/helmrelease.yaml
Reverts mesosphere/kommander-applications#2531
=> feat: Release NKP-Insights v1.2.0-beta.5

services/thanos/metadata.yaml
Remove Thanos from `Pro` and `Essentials` to match the [Feature Matrix](https://docs.google.com/spreadsheets/d/1M2qhRebO3DPcrn662D7tw4DRXk8tuM4ICIMMGRS6rWw/edit?gid=1327181177#gid=1327181177).
https://jira.nutanix.com/browse/NCN-101897
```release-note
```
**Checklist**
=> fix: Remove Thanos from the Pro/Essentials Tier

licenses.d2iq.yaml, services/nkp-insights-management/1.2.0/defaults/cm.yaml, services/nkp-insights-management/1.2.0/helmrelease/helmrelease.yaml, services/nkp-insights/1.2.0/defaults/cm.yaml, services/nkp-insights/1.2.0/helmrelease/helmrelease.yaml
* feat: Release NKP-Insights Backend v1.2.0
Release NKP-Insights Backend v1.2.0
* feat: Release NKP-Insights Management v1.2.0
Release NKP-Insights Management v1.2.0
---------
Co-authored-by: d2iq-mergebot <ci-mergebot@d2iq.com>
(cherry picked from commit 8aec997b03772667e2625115035a41578b3fd2f1)
```release-note
```
**Checklist**
=> feat: Release NKP-Insights v1.2.0 (#2555)

charts/kommander-operator/crds/dkp.d2iq.io_kommandercores.yaml
Update kommandercore crd (crd generated from https://github.com/mesosphere/kommander/pull/5027)
https://jira.nutanix.com/browse/NCN-102134
```release-note
```
**Checklist**
=> fix(kcore): Update kommandercore crd

.github/dependabot.yml, .github/workflows/release.yml, .github/workflows/test.yaml, .include-airgapped, just/test.just, justfile, server/Dockerfile
- I decided to use much simpler server - `git daemon`, for more context: https://github.com/mesosphere/kommander/pull/5201
- This PR also enables server build on every release
https://jira.nutanix.com/browse/NCN-102822
```release-note
```
**Checklist**
=> build: Change docker image, enable server build

services/reloader/metadata.yaml
Update typo in reloader overview
=> fix: Update typo in reloader overview

.github/workflows/automerge.yaml
fixes a typo
```release-note
```
**Checklist**
=> fix(gha): Typo

licenses.d2iq.yaml, services/fluent-bit/0.47.7/defaults/cm.yaml
CVE fix: Bump cr.fluentbit.io/fluent/fluent-bit to 2.2.3-d2iq.1
https://jira.nutanix.com/browse/NCN-102776
=> feat: Bump cr.fluentbit.io/fluent/fluent-bit

licenses.d2iq.yaml, services/kubecost/0.37.7/defaults/cm.yaml
```release-note
```
**Checklist**
=> feat: bump configmap-reload to v0.14.0

licenses.d2iq.yaml, services/kommander/0.13.0/dynamic-helmreleases/mtls-proxy/list-images-values.yaml
```release-note
```
**Checklist**
=> chore: bump ghostunnel to 1.8.1

licenses.d2iq.yaml, services/kommander/0.13.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
```release-note
```
**Checklist**
=> fix: bump cluster-observer 1.4.0

.github/workflows/release.yml
set the type explicitly for richer formatting
This should be the final fix after #2819 
```release-note
```
**Checklist**
=> fix: use INCOMING_WEBHOOK for slack hook

licenses.d2iq.yaml, services/kommander/0.13.0/extra-images.txt
It seems we missed that one too while switching to ghcr
```release-note
```
**Checklist**
=> fix: One more reference to the wrong repo

services/ai-navigator-app/0.2.8/helmrelease/helmrelease.yaml
Bump the AIN chart to the new version to fix the upgrade issue.
https://jira.nutanix.com/browse/NCN-104562
```release-note
```
**Checklist**
=> feat: Update AI Navigator Cluster Info API chart to v0.2.7

licenses.d2iq.yaml, services/kommander/0.13.0/dynamic-helmreleases/cluster-observer/cluster-observer.yaml
```release-note
```
**Checklist**
=> fix: bump cluster observer 141

services/dex/2.13.15/dex.yaml
```release-note
```
**Checklist**
=> fix: dex cm reference bump

services/grafana-logging/metadata.yaml, services/grafana-loki/metadata.yaml, services/istio/metadata.yaml, services/traefik-forward-auth/metadata.yaml, services/traefik/metadata.yaml, services/velero/metadata.yaml
Supported should be replaced with qualified for all third-party applications.
https://jira.nutanix.com/browse/NCN-104856
```release-note
"Supported" badges will be replaced by "Qualified" for all third-party applications.
```
**Checklist**
=> feat: change supported to qualified for all third party apps

.bloodhound.yml
Bumps k8s version in bloodhound to 1.31.1
https://jira.nutanix.com/browse/NCN-103538
=> feat: bloodhound k8s bump1.31 

.github/service-labeler.yaml, common/helm-repositories/cloudnative-pg.yaml, common/helm-repositories/kustomization.yaml, licenses.d2iq.yaml, services/cloudnative-pg/0.23.0/cloudnative-pg.yaml, services/cloudnative-pg/0.23.0/defaults/cm.yaml, services/cloudnative-pg/0.23.0/defaults/kustomization.yaml, services/cloudnative-pg/0.23.0/kustomization.yaml, services/cloudnative-pg/metadata.yaml
```release-note
```
**Checklist**
=> feat: Add cloudnative-pg internal app

services/cloudnative-pg/0.23.0/grafana-dashboards/grafana-dashboard.json, services/cloudnative-pg/0.23.0/grafana-dashboards/kustomization.yaml, services/cloudnative-pg/0.23.0/kustomization.yaml
add official grafana dashboard to the cloudnative-pg app
https://github.com/cloudnative-pg/grafana-dashboards
=> feat: add cloudnative-pg grafana dashboard

services/harbor/1.16.0/defaults/valkey.yaml, services/harbor/1.16.0/valkey/valkey.yaml
Adds the `NetworkPolicy` and metrics to valkey installation.
```release-note
```
**Checklist**
=> feat: enable monitoring and network policy for valkey

services/knative/1.15.5/knative-serving.yaml
add optional overrides for knative to allow additional apps to configure it correctly
=> feat: add optional overrides for knative

services/harbor/1.16.0/pre-install/kustomization.yaml, services/harbor/1.16.0/pre-install/pre-install-jobs.yaml, services/harbor/1.16.0/pre-install/secrets.yaml
```release-note
```
**Checklist**
=> fix: track harbor generated secrets by flux

apptests/appscenarios/contants.go, common/build/list-images-values.yaml, licenses.d2iq.yaml, services/ai-navigator-app/0.2.9/defaults/cm.yaml, services/dex/2.14.0/defaults/cm.yaml, services/git-operator/0.1.3/kustomization.yaml, services/grafana-loki/0.79.5/grafana-loki-pre-install-jobs/pre-install.yaml, services/harbor/1.16.0/pre-install/pre-install-jobs.yaml, services/istio/1.23.3/defaults/cm.yaml, services/knative/1.15.5/defaults/cm.yaml, services/kommander/0.14.0/dynamic-helmreleases/cluster-observer/list-images-values.yaml, services/kube-prometheus-stack/67.6.0/defaults/cm.yaml, services/kubecost/2.5.2/cosi-storage/object-store-check.yaml, services/kubecost/2.5.2/pre-install/pre-install-jobs.yaml, services/kubefed/0.10.5/defaults/cm.yaml, services/kubetunnel/0.0.39/defaults/cm.yaml, services/nkp-insights-management/1.3.4/defaults/cm.yaml, services/nkp-insights/1.3.4/defaults/cm.yaml, services/project-grafana-loki/0.79.5/defaults/cm.yaml, services/rook-ceph-cluster/1.15.5/defaults/cm.yaml, services/rook-ceph-cluster/1.15.5/pre-install/ceph-crd-check.yaml, services/thanos/15.7.24/jobs/jobs.yaml, services/velero/8.2.0/defaults/cm.yaml, services/velero/8.2.0/velero-pre-install.yaml
```release-note
```
**Checklist**
=> feat: bump kubectl version to 1.31.4

services/rook-ceph-cluster/1.16.2/defaults/cm.yaml
Adds the stripprefix middleware to ceph dashboard
https://jira.nutanix.com/browse/NCN-105425
```release-note
```
**Checklist**
=> fix: ceph dashboard middleware

services/harbor/1.16.0/cosi-storage/cosi-bucket.yaml
I forgot to accept my own suggestion here https://github.com/mesosphere/kommander-applications/pull/3053#discussion_r1929262870 
```release-note
```
**Checklist**
=> chore: bump cosi-bucket-kit in harbor

services/harbor/1.16.2/defaults/harbor.yaml, services/harbor/1.16.2/release/certificates.yaml, services/harbor/1.16.2/release/kustomization.yaml
```release-note
```
**Checklist**
=> fix(harbor): cert-manager internal tls

services/harbor/1.16.2/defaults/database.yaml, services/harbor/1.16.2/defaults/harbor.yaml, services/harbor/1.16.2/defaults/valkey.yaml
Add missing priority classes
https://jira.nutanix.com/browse/NCN-105541
```release-note
```
**Checklist**
=> fix(harbor): add priority classes to all pods

services/kubernetes-dashboard/7.10.0/defaults/cm.yaml
update kong anonymous_reports=off
https://jira.nutanix.com/browse/NCN-105475
```release-note
```
**Checklist**
=> fix: update kong anonymous_reports to off

services/cosi-driver-nutanix/0.0.4/cosi-driver-nutanix.yaml
https://jira.nutanix.com/browse/NCN-105484
```release-note
```
**Checklist**
=> fix: bump nutanix cosi driver helm chart

services/traefik/34.1.0/crds/crds.yaml
set traefik-crd helmrelease interval to 15s to align with traefik helmrelease interval
=> fix: align traefik-crds interval with traefik

licenses.d2iq.yaml, services/ai-navigator-app/0.2.10/defaults/cm.yaml
```release-note
```
**Checklist**
=> fix: Use Docker Hub for weaviate image

licenses.d2iq.yaml, services/fluent-bit/0.48.5/defaults/cm.yaml, services/logging-operator/5.0.1/defaults/cm.yaml
```release-note
```
**Checklist**
=> fix: use fluentbit image from dockerhub

licenses.d2iq.yaml, services/harbor/1.16.2/database/cluster.yaml, services/harbor/1.16.2/database/extra-images.txt
Adds pg image to the bundle.
```release-note
```
**Checklist**
=> fix(harbor): add cloudnative/postgres image

services/harbor/metadata.yaml
Update harbor overview metadata to improve paragraph styling & making it consistent with other k-apps.
[NCN-105712](https://jira.nutanix.com/browse/NCN-105712)
```release-note
```
**Checklist**
=> chore: update harbor overview metadata

services/harbor/1.16.2/cosi-storage/cosi-bucket.yaml, services/harbor/1.16.2/manual-storage/manual-bucket.yaml, services/harbor/1.16.2/release/harbor.yaml
```release-note
```
**Checklist**
=> fix(harbor): add reference to UI created overrides

services/cosi-driver-nutanix/0.2.0/cosi-resources-nutanix.yaml, services/harbor/1.16.2/cosi-storage/cosi-bucket.yaml, services/kubecost/2.5.2/cosi-storage/cosi-bucket.yaml, services/rook-ceph-cluster/1.16.2/objectbucketclaims/cosi-bucket.yaml
https://github.com/mesosphere/charts/pull/1557
```release-note
```
**Checklist**
=> chore: bump cosi-bucket-kit to 0.0.2

.bloodhound.yml
bump k8s 1.32.2 to bloodhound 
https://jira.nutanix.com/browse/NCN-105344
=> feat: bump k8s 1.32.2 version to bloodhound

services/cosi-driver-nutanix/0.2.0/cosi-resources-nutanix.yaml, services/harbor/1.16.2/cosi-storage/cosi-bucket.yaml, services/harbor/1.16.2/defaults/harbor.yaml, services/kubecost/2.5.2/cosi-storage/cosi-bucket.yaml, services/rook-ceph-cluster/1.16.2/objectbucketclaims/cosi-bucket.yaml
https://jira.nutanix.com/browse/NCN-105847
```release-note
```
**Checklist**
=> feat: Bump cosi-bucket-kit deps to 0.0.3

services/nvidia-gpu-operator/24.9.2/grafana-dashboards/gpu-operator.json
in GPU dashboard the GPU Temperatur is not displaying correctly, we need to remove the instant flag
also add some tags on the dashboard for cosmetic
=> fix: gpu dashboard temp graph

.bloodhound.yml
```release-note
```
**Checklist**
=> feat: bump the k8s 1.30 to latest patch (2.13)

apptests/appscenarios/contants.go, common/build/list-images-values.yaml, licenses.d2iq.yaml, services/ai-navigator-app/0.2.8/defaults/cm.yaml, services/centralized-kubecost/0.37.7/defaults/cm.yaml, services/centralized-kubecost/0.37.7/post-install-jobs/post-install-jobs.yaml, services/centralized-kubecost/0.37.7/release/release.yaml, services/dex/2.14.0/defaults/cm.yaml, services/git-operator/0.1.2/kustomization.yaml, services/grafana-loki/0.79.5/grafana-loki-pre-install-jobs/pre-install.yaml, services/istio/1.23.3/defaults/cm.yaml, services/knative/1.15.5/defaults/cm.yaml, services/kommander/0.13.2/dynamic-helmreleases/cluster-observer/list-images-values.yaml, services/kube-prometheus-stack/65.5.0/defaults/cm.yaml, services/kubecost/0.37.8/defaults/cm.yaml, services/kubefed/0.10.5/defaults/cm.yaml, services/kubetunnel/0.0.38/defaults/cm.yaml, services/nkp-insights-management/1.3.4/defaults/cm.yaml, services/nkp-insights/1.3.4/defaults/cm.yaml, services/project-grafana-loki/0.79.5/defaults/cm.yaml, services/rook-ceph-cluster/1.14.5/defaults/cm.yaml, services/rook-ceph-cluster/1.14.5/pre-install/ceph-crd-check.yaml, services/thanos/15.7.23/jobs/jobs.yaml, services/traefik/27.0.3/defaults/cm.yaml, services/velero/7.2.2/defaults/cm.yaml, services/velero/7.2.2/velero-pre-install.yaml
bump kubectl version to 1.30.10
https://jira.nutanix.com/browse/NCN-105973
```release-note
```
**Checklist**
=> feat: bump kubectl version to 1.30.10

services/ai-navigator-app/0.2.10/ai-navigator-app.yaml
Bump ai-navigator-app to the latest version.
https://jira.nutanix.com/browse/NCN-106591
```release-note
```
**Checklist**
=> feat: Bump ai-navigator-app to v0.3.0

.bloodhound.yml, apptests/appscenarios/contants.go, common/build/list-images-values.yaml, licenses.d2iq.yaml, services/ai-navigator-app/0.2.10/defaults/cm.yaml, services/cosi-driver-nutanix/0.4.0/defaults/cm.yaml, services/dex/2.14.2/defaults/cm.yaml, services/git-operator/0.1.4/git-operator-manifests/all.yaml, services/git-operator/0.1.4/kustomization.yaml, services/grafana-loki/0.79.5/grafana-loki-pre-install-jobs/pre-install.yaml, services/harbor/1.16.2/defaults/harbor.yaml, services/harbor/1.16.2/pre-install/pre-install-jobs.yaml, services/istio/1.23.3/defaults/cm.yaml, services/knative/1.17.0/defaults/cm.yaml, services/kommander/0.16.0/dynamic-helmreleases/cluster-observer/list-images-values.yaml, services/kube-prometheus-stack/69.8.0/defaults/cm.yaml, services/kubecost/2.6.3/defaults/cm.yaml, services/kubecost/2.6.3/pre-install/pre-install-jobs.yaml, services/kubefed/0.11.1/defaults/cm.yaml, services/kubetunnel/0.0.39/defaults/cm.yaml, services/nkp-insights-management/1.4.4/defaults/cm.yaml, services/nkp-insights/1.4.4/defaults/cm.yaml, services/project-grafana-loki/0.79.5/defaults/cm.yaml, services/rook-ceph-cluster/1.16.2/defaults/cm.yaml, services/rook-ceph-cluster/1.16.2/pre-install/ceph-crd-check.yaml, services/thanos/15.7.24/jobs/jobs.yaml, services/velero/8.3.0/defaults/cm.yaml, services/velero/8.3.0/velero-pre-install.yaml
What problem does this PR solve?:
Bumped Kubectl to 1.32.3
https://jira.nutanix.com/browse/NCN-106652
=> feat: Bumped k8s to 1.32.3

charts/kommander-operator/Chart.yaml
There were significant changes to the app, let's change the chart version.
```release-note
```
**Checklist**
=> feat: Bump kommander operator chart to 0.4.0

.bloodhound.yml
backport PR
https://github.com/mesosphere/kommander-applications/pull/3532
```release-note
```
**Checklist**
=> feat: bump the k8s 1.31 to latest patch 1.31.9 (2.14)

.github/workflows/lint.yaml, .pre-commit-config.yaml, hack/validate-app-metadata.sh, make/pre-commit.mk
looks like we were never actually running our pre-commit checks. updated the validate script to validate that there is metadata.yaml in each app version dir.
```release-note
```
**Checklist**
=> ci: Fix pre-commit metadata check

applications
As interim step of `s/services/applications`, synmlyink `services/` to new dir `applications/`. Will follow up with removal of `services/` dir once tested with the rest of changes in various places needed to go along with the renaming
https://jira.nutanix.com/browse/NCN-107598
```release-note
```
**Checklist**
=> feat: Create applications symlink to services

licenses.d2iq.yaml, services/nvidia-gpu-operator/25.3.1/defaults/cm.yaml, services/nvidia-gpu-operator/25.3.1/helmrelease/extra-images.txt
Adds mig manager image
```release-note
```
**Checklist**
=> feat: adds mig manager to airgap bundle

.github/app-pr-labeler.yaml
remaining s/services/applications for this gha config file
```release-note
```
**Checklist**
=> build(gha): Update path in labeler config

applications/nvidia-gpu-operator/25.3.1/defaults/cm.yaml, applications/nvidia-gpu-operator/25.3.1/helmrelease/nvidia.yaml, licenses.d2iq.yaml
Bump to gpu-operator to latest 
https://jira.nutanix.com/browse/NCN-108018
=> feat: bump to gpu-operator to v.25.3.1

applications/kube-prometheus-stack/71.0.1/defaults/cm.yaml
Adds KB url incase of CERTIFICATE RENEWAL MIGHT FAIL/ CERTIFICATE EXPIRED
=> chore: Adds mock KB URL for cert expiry Prometheus alerts

applications/nkp-pulse-management/0.2.7/defaults/cm.yaml, applications/nkp-pulse-workspace/0.2.7/defaults/cm.yaml
Use Dockerhub Registry now that approvals for Pulse have been granted.
https://jira.nutanix.com/browse/NCN-106147
```release-note
```
**Checklist**
=> chore: Use Dockerhub as the registry for NKP-Pulse

applications/kubetunnel/0.0.40/kubetunnel.yaml
kubetunnel OCI migration
https://jira.nutanix.com/browse/NCN-108245
```release-note
```
**Checklist**
=> refactor: kubetunnel OCI migration

applications/ai-navigator-cluster-info-agent/0.3.0/defaults/cm.yaml, applications/cosi-driver-nutanix/0.6.0/defaults/cm.yaml, applications/dex/2.14.3/defaults/cm.yaml, applications/git-operator/0.13.10/kustomization.yaml, applications/grafana-loki/0.80.4/grafana-loki-pre-install-jobs/pre-install.yaml, applications/harbor/1.17.0/defaults/harbor.yaml, applications/harbor/1.17.0/pre-install/pre-install-jobs.yaml, applications/istio/1.23.4/defaults/cm.yaml, applications/kommander/0.16.0/dynamic-helmreleases/cluster-observer/list-images-values.yaml, applications/kube-prometheus-stack/71.0.1/defaults/cm.yaml, applications/kubecost/2.7.3/defaults/cm.yaml, applications/kubecost/2.7.3/pre-install/pre-install-jobs.yaml, applications/kubefed/0.11.2/defaults/cm.yaml, applications/kubetunnel/0.0.40/defaults/cm.yaml, applications/nkp-insights-management/1.4.5/defaults/cm.yaml, applications/nkp-insights/1.4.5/defaults/cm.yaml, applications/nkp-pulse-management/0.2.7/defaults/cm.yaml, applications/project-grafana-loki/0.80.4/defaults/cm.yaml, applications/rook-ceph-cluster/1.17.5/defaults/cm.yaml, applications/rook-ceph-cluster/1.17.5/pre-install/ceph-crd-check.yaml, applications/thanos/15.8.1/jobs/jobs.yaml, applications/velero/10.0.8/defaults/cm.yaml, applications/velero/10.0.8/velero-pre-install.yaml, apptests/appscenarios/constants.go, common/build/list-images-values.yaml, licenses.d2iq.yaml
bump kubectl to 1.33.2
```release-note
```
**Checklist**
=> feat: bump kubectl to 1.33.2

applications/kube-prometheus-stack/71.0.1/defaults/cm.yaml
=> chore: updates sentence

applications/prometheus-adapter/4.14.2/helmrelease/prometheus-adapter.yaml
Prometheus Adapter OCI Migration
**JIRA TICKET**:
https://jira.nutanix.com/browse/NCN-108422
=> feat: Prometheus Adapter OCI Migration

common/helm-repositories/kustomization.yaml
```release-note
```
**Checklist**
=> refactor: remove helm-repo ref

applications/project-grafana-loki/0.80.4/object-bucket-claims.yaml, applications/rook-ceph-cluster/1.17.5/objectbucketclaims/helmrelease.yaml
refactor: Migrate object-bucket-claim to OCI
=> refactor: Migrate object-bucket-claim to OCI

applications/kubefed/0.11.2/release/release.yaml
kubefed oci migration
https://jira.nutanix.com/browse/NCN-108189
```release-note
```
**Checklist**
=> refactor: kubefed oci migration

.bloodhound.yml
```release-note
```
**Checklist**
=> fix: cert-manager crd links

.github/workflows/single-chart-ghcr.yaml
push chart to ghcr (oci://ghcr.io/mesosphere/charts)
```release-note
```
**Checklist**
=> build: push chart to ghcr

.github/workflows/single-chart-ghcr.yaml
update the push chart to ghcr (oci://ghcr.io/mesosphere/charts)
```release-note
```
**Checklist**
=> fix: update single chart push

applications/kube-prometheus-stack/71.0.0/defaults/cm.yaml
updates names and descriptions for better readability.
=> chore: update states of prometheus alerts

applications/kommander/0.16.0/defaults/cm.yaml
Relates to https://github.com/mesosphere/kommander/pull/6213
```release-note
```
**Checklist**
=> refactor: default catalog configuration

justfile, make/validate.mk
Add support for creating full Kommander application bundles
https://jira.nutanix.com/browse/NCN-108501
=> feat: Add support for creating full Kommander application bundles

applications/gatekeeper/3.19.2/release/release.yaml
```release-note
```
**Checklist**
=> feat: controller synced values for gatekeeper proxy

applications/harbor/1.17.1/cosi-storage/cosi-bucket.yaml
```release-note
```
**Checklist**
=> chore: bump harbor cosi-bucket-kit to 0.0.8

applications/centralized-grafana/71.0.0/centralized-grafana.yaml, applications/cosi-driver-nutanix/0.6.0/cosi-resources-nutanix.yaml, applications/gateway-api-crds/1.9.0/gateway-api-crds.yaml, applications/grafana-loki/0.80.4/grafana-loki-helmrelease.yaml, applications/grafana-loki/0.80.4/grafana-loki-helmrelease/grafana-loki.yaml, applications/karma-traefik/0.0.3/karma-traefik.yaml, applications/project-grafana-logging/8.15.1/project-grafana.yaml, applications/project-grafana-loki/0.80.4/object-bucket-claims.yaml, applications/project-grafana-loki/0.80.4/project-grafana-loki.yaml, applications/prometheus-thanos-traefik/0.0.3/prometheus-thanos-traefik.yaml, applications/rook-ceph-cluster/1.17.6/object-bucket-claims.yaml, applications/rook-ceph-cluster/1.17.6/objectbucketclaims/cosi-bucket.yaml, applications/rook-ceph-cluster/1.17.6/objectbucketclaims/helmrelease.yaml, applications/traefik-forward-auth-mgmt/0.3.15/traefik-forward-auth-mgmt.yaml, apptests/appscenarios/rookceph.go
```release-note
```
**Checklist**
=> fix: use unique names for all oci repos

applications/ai-navigator-rag/0.7.1/metadata.yaml
- Add **must have** requirements.
- Typo of `futher` in application page for UI, should be `further`. Rest are just style things
n/a
n/a just app page info
n/a
**Checklist**
=> docs: Add must have and fix typo in ai nav rag app page

.bloodhound.yml
bump k8s 1.32.3 to latest patch 1.32.8
=> feat: bump k8s 1.32.3 to latest patch 1.32.8

.bloodhound.yml, devbox.json, devbox.lock, services/centralized-grafana/70.4.2/defaults/cm.yaml, services/grafana-logging/8.11.0/defaults/cm.yaml, services/kube-prometheus-stack/70.4.2/defaults/cm.yaml, services/project-grafana-logging/8.11.0/defaults/cm.yaml
backports https://github.com/mesosphere/kommander-applications/pull/3874 and https://github.com/mesosphere/kommander-applications/pull/3921
https://jira.nutanix.com/browse/NCN-109351
https://jira.nutanix.com/browse/NCN-108951
```release-note
```
**Checklist**
=> fix(grafana): Avoid errors in airgapped

.bloodhound.yml
Bumps k8s in bloodhound.yml 
https://jira.nutanix.com/browse/NCN-108684
=> feat: Bumped k8s in bloodhound
